"""Derived-property oracle execution for model-based formats.

generated_by: codex
"""

import importlib
import sys


# FF6-EVENT-000275: ipynb/nrrd/safetensors/ubl/xliff point at the shipped
# format_factory.{fmt} namespace, not the deprecated flat {fmt}.{fmt}_codec
# shim under src/python/{fmt}/ — the shim is excluded from the built wheel,
# so an oracle bound to it was never exercising the shipped code. mtlx is
# outside FF6 scope and is left on the legacy module intentionally.
ENRICHED_LOADERS = {
    "ipynb": ("format_factory.ipynb", "load_ipynb"),
    "mtlx": ("mtlx.mtlx_codec", "load_mtlx"),
    "nrrd": ("format_factory.nrrd", "load_nrrd"),
    "ora": ("format_factory.ora", "load"),
    "safetensors": ("format_factory.safetensors", "load"),
    "ubl": ("format_factory.ubl", "load"),
    "xliff": ("format_factory.xliff", "load_xliff"),
}

# FF6-EVENT-000281: UblDocument's root-type subclasses are generated by
# tools/generate_roots.py (model/root_types.py's own "Do not edit by hand"
# header) and know nothing about shared/qname-registry/ubl.yaml, which
# only covers 3 of ubl's 91 root types (Invoice, CreditNote, Order) so
# far. Kept here rather than hand-patched into the generated file.
_UBL_SPEC_QNAME_BY_ROOT_NAME = {
    "Invoice": "ubl:invoice",
    "CreditNote": "ubl:credit-note",
    "Order": "ubl:order",
}


def _enrich_model(result_val, format_id: str) -> dict:
    """Add derived properties used by expected_model_properties.

    ipynb and nrrd's shipped loaders still return plain dicts, so the
    original dict-shaped derivation applies unchanged. safetensors, ubl and
    xliff's shipped loaders return typed model objects (SafeTensorsDocument /
    UblDocument / XliffDocument) instead of the flat dicts the retired
    shadow codecs returned — each branch below uses that object's own real,
    tested accessor (.tensors, DocumentIndex(...).by_business_role("line"),
    .unit_count) rather than a dict key that no longer exists.
    """
    if isinstance(result_val, dict):
        enriched = dict(result_val)
        if format_id == "ipynb":
            cells = result_val.get("cells", [])
            enriched["cell_count"] = len(cells) if isinstance(cells, list) else 0
            # load_ipynb() is a deliberate alpha-compatibility facade that
            # returns the raw preserved notebook mapping (.raw), not
            # IpynbDocument.to_dict() — injecting spec_qname into that raw
            # mapping itself would pollute a faithful preservation view, so
            # it is added here instead, sourced from the model class's own
            # ClassVar rather than a second hardcoded copy of the string.
            from format_factory.ipynb import IpynbDocument

            enriched["spec_qname"] = IpynbDocument.spec_qname
        elif format_id == "mtlx":
            materials = result_val.get("materials", [])
            enriched["material_count"] = len(materials) if isinstance(materials, list) else 0
        elif format_id == "nrrd":
            shape = result_val.get("array_shape", result_val.get("header", {}).get("sizes", []))
            enriched["dimension"] = len(shape) if isinstance(shape, list) else 0
        return enriched

    enriched: dict = {"spec_qname": getattr(result_val, "spec_qname", None)}
    if format_id == "safetensors":
        tensors = getattr(result_val, "tensors", {})
        enriched["tensor_count"] = len(tensors)
        enriched["tensor_names"] = sorted(tensors)
    elif format_id == "ubl":
        from format_factory.ubl import DocumentIndex

        root_name = getattr(result_val, "root_name", None)
        enriched["document_type"] = root_name
        enriched["line_count"] = len(DocumentIndex(result_val.root).by_business_role("line"))
        enriched["spec_qname"] = _UBL_SPEC_QNAME_BY_ROOT_NAME.get(root_name)
    elif format_id == "xliff":
        enriched["unit_count"] = result_val.unit_count
    elif format_id == "ora":
        del enriched["spec_qname"]  # ora's model has no spec_qname concept
        enriched["declared_version"] = result_val.declared_version
        enriched["detected_version"] = result_val.detected_version
        enriched["width"] = result_val.document.width
        enriched["height"] = result_val.document.height
        enriched["layer_count"] = _count_ora_layers(result_val.document.root)
    return enriched


def _count_ora_layers(node) -> int:
    """Recursively count OraLayer descendants of an OraStack/OraNode."""
    count = 0
    for child in getattr(node, "children", ()):
        if type(child).__name__ == "OraLayer":
            count += 1
        elif type(child).__name__ == "OraStack":
            count += _count_ora_layers(child)
    return count


def execute_enriched_generic(core, case, pkg, format_id, module, callable_name):
    """Execute a generic loader and compare enriched model properties."""
    case_id = case["case_id"]
    sample_ref = case.get("input_ref") or case.get("sample_ref")
    _, authority_status = core.check_authority(case, True)
    common = {
        "oracle_id": pkg["oracle_id"],
        "oracle_version": pkg["oracle_version"],
        "format_id": format_id,
        "product_id": f"format-factory-{format_id}",
        "language": "python",
        "case_id": case_id,
        "profile": "PARSE_VALIDITY",
        "authority_status": authority_status,
    }
    if not sample_ref:
        return core.make_verdict(
            **common, result=core.RESULT_NOT_APPLICABLE, diagnostics=["No sample_ref"]
        )
    sample_path = core.REPO_ROOT / sample_ref
    if not sample_path.exists():
        return core.make_verdict(
            **common,
            result=core.RESULT_BLOCKED_MISSING_SAMPLE,
            diagnostics=[f"Sample not found: {sample_path}"],
        )
    input_hash = core.sha256_file(sample_path)
    try:
        sys.path.insert(0, str(core.REPO_ROOT))
        module_path = module if module.startswith("format_factory.") else f"src.python.{module}"
        fn = getattr(importlib.import_module(module_path), callable_name)
        result_val = _enrich_model(fn(str(sample_path)), format_id)
        expected = case.get("expected_model_properties", [])
        observed, deviations, depth, diagnostics = core._compare_model_properties(
            result_val, expected
        )
        return core.make_verdict(
            **common,
            result=core.RESULT_FAIL if deviations else core.RESULT_PASS,
            observed=observed,
            deviations=deviations,
            input_hash=input_hash,
            depth_level=depth,
            diagnostics=diagnostics,
        )
    except Exception as exc:
        return core.make_verdict(
            **common,
            result=core.RESULT_FAIL,
            diagnostics=[f"{type(exc).__name__}: {exc}"],
            input_hash=input_hash,
            depth_level=core.DEPTH_D0,
        )
