"""Exception coverage tests for zst format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from zst.zst_codec import ZstDecompressError, ZstFileNotFoundError, ZstReadError
from zst.zst_codec import ZstError as ZstCodecError
from zst.exceptions import ZstParseError, ZstWriteError
from zst.exceptions import ZstError as ZstExcError


def test_zstdecompresserror_is_raisable():
    with pytest.raises(ZstDecompressError):
        raise ZstDecompressError("test error message")


def test_zstdecompresserror_inherits_base():
    assert issubclass(ZstDecompressError, ZstCodecError)


def test_zstdecompresserror_message():
    exc = ZstDecompressError("specific error")
    assert "specific error" in str(exc)


def test_zstfilenotfounderror_is_raisable():
    with pytest.raises(ZstFileNotFoundError):
        raise ZstFileNotFoundError("test error message")


def test_zstfilenotfounderror_inherits_base():
    assert issubclass(ZstFileNotFoundError, ZstCodecError)


def test_zstfilenotfounderror_message():
    exc = ZstFileNotFoundError("specific error")
    assert "specific error" in str(exc)


def test_zstreaderror_is_raisable():
    with pytest.raises(ZstReadError):
        raise ZstReadError("test error message")


def test_zstreaderror_inherits_base():
    assert issubclass(ZstReadError, ZstCodecError)


def test_zstreaderror_message():
    exc = ZstReadError("specific error")
    assert "specific error" in str(exc)


def test_zstparseerror_is_raisable():
    with pytest.raises(ZstParseError):
        raise ZstParseError("test error message")


def test_zstparseerror_inherits_base():
    assert issubclass(ZstParseError, ZstExcError)


def test_zstparseerror_message():
    exc = ZstParseError("specific error")
    assert "specific error" in str(exc)


def test_zstwriteerror_is_raisable():
    with pytest.raises(ZstWriteError):
        raise ZstWriteError("test error message")


def test_zstwriteerror_inherits_base():
    assert issubclass(ZstWriteError, ZstExcError)


def test_zstwriteerror_message():
    exc = ZstWriteError("specific error")
    assert "specific error" in str(exc)
