"""Tests for zst_frame_sizes — generated via plan machinery (Train G).

Taskcard: TC-0350BD00 (ZST zst_frame_sizes)
Generated by: capability_compiler phase 2
SAL facts: ZST-FACT-001, ZST-FACT-002, ZST-FACT-003
"""

import sys
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(_REPO / "src" / "python"))

from zst import zst_frame_sizes, zst_frame_count


@pytest.fixture
def single_frame_zst(tmp_path):
    """Create a minimal single-frame ZST file."""
    try:
        import zstandard
    except ImportError:
        pytest.skip("zstandard not installed")
    data = b"Hello, World! " * 100
    cctx = zstandard.ZstdCompressor()
    compressed = cctx.compress(data)
    p = tmp_path / "single.zst"
    p.write_bytes(compressed)
    return p


@pytest.fixture
def multi_frame_zst(tmp_path):
    """Create a multi-frame ZST file (two frames concatenated)."""
    try:
        import zstandard
    except ImportError:
        pytest.skip("zstandard not installed")
    cctx = zstandard.ZstdCompressor()
    frame1 = cctx.compress(b"Frame one data " * 50)
    frame2 = cctx.compress(b"Frame two data " * 50)
    p = tmp_path / "multi.zst"
    p.write_bytes(frame1 + frame2)
    return p


@pytest.fixture
def empty_file(tmp_path):
    p = tmp_path / "empty.zst"
    p.write_bytes(b"")
    return p


class TestZstFrameSizes:
    def test_returns_list(self, single_frame_zst):
        result = zst_frame_sizes(single_frame_zst)
        assert isinstance(result, list)

    def test_single_frame_one_element(self, single_frame_zst):
        result = zst_frame_sizes(single_frame_zst)
        assert len(result) == 1

    def test_single_frame_size_matches_file(self, single_frame_zst):
        result = zst_frame_sizes(single_frame_zst)
        file_size = single_frame_zst.stat().st_size
        assert result[0] == file_size

    def test_multi_frame_two_elements(self, multi_frame_zst):
        result = zst_frame_sizes(multi_frame_zst)
        assert len(result) == 2

    def test_multi_frame_sizes_sum_to_file(self, multi_frame_zst):
        result = zst_frame_sizes(multi_frame_zst)
        file_size = multi_frame_zst.stat().st_size
        assert sum(result) == file_size

    def test_frame_sizes_positive(self, multi_frame_zst):
        result = zst_frame_sizes(multi_frame_zst)
        assert all(s > 0 for s in result)

    def test_empty_file_returns_empty(self, empty_file):
        result = zst_frame_sizes(empty_file)
        assert result == []

    def test_consistent_with_frame_count(self, single_frame_zst):
        sizes = zst_frame_sizes(single_frame_zst)
        count = zst_frame_count(single_frame_zst)
        assert len(sizes) == count

    def test_consistent_with_frame_count_multi(self, multi_frame_zst):
        sizes = zst_frame_sizes(multi_frame_zst)
        count = zst_frame_count(multi_frame_zst)
        assert len(sizes) == count

    def test_file_not_found(self, tmp_path):
        with pytest.raises(Exception, match="File not found"):
            zst_frame_sizes(tmp_path / "nonexistent.zst")

    def test_string_path(self, single_frame_zst):
        result = zst_frame_sizes(str(single_frame_zst))
        assert isinstance(result, list)
        assert len(result) == 1
