"""Generate PROJECT_STATUS.md — the canonical project status document.

Orchestrates all sub-generators (statistics, product inventory, architecture,
agent ecosystem) and assembles a single markdown document that serves as
the single source of truth for README, announcements, and presentations.

Usage:
    python tools/docs/generate_project_status.py
    python tools/docs/generate_project_status.py --dry-run
    python tools/docs/generate_project_status.py --json
    python tools/docs/generate_project_status.py --update-readme
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# Import sub-generators
sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_agent_inventory import collect_agent_inventory, render_agent_inventory_markdown
from generate_architecture_inventory import collect_architecture_inventory, render_architecture_markdown
from generate_product_inventory import collect_product_inventory, render_product_inventory_markdown
from generate_statistics import collect_statistics, render_statistics_markdown


def _read_json(path: Path):
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except Exception:
        return None


def _generate_header(timestamp: str) -> str:
    return "\n".join([
        "<!-- AUTO-GENERATED by tools/docs/generate_project_status.py -->",
        f"<!-- Generated: {timestamp} -->",
        "<!-- Re-generate: python tools/docs/generate_project_status.py -->",
        "<!-- DO NOT EDIT MANUALLY — changes will be overwritten -->",
        "",
        "# Format Factory — Project Status",
        "",
        "This document is auto-generated from repository evidence. Every number "
        "is traced to a canonical registry, oracle result, or test artifact.",
        "",
        "**Table of Contents**",
        "- [Statistics Summary](#statistics-summary)",
        "- [Product Inventory](#product-inventory)",
        "- [Architecture — Layer Inventory](#architecture--layer-inventory)",
        "- [Governance Validators](#governance-validators)",
        "- [Capabilities](#capabilities)",
        "- [Agent Ecosystem](#agent-ecosystem)",
        "- [Known Limitations](#known-limitations)",
        "",
        "---",
        "",
    ])


def _generate_limitations(repo_root: Path, stats: dict) -> str:
    """Generate known limitations section from evidence."""
    lines = [
        "## Known Limitations",
        "",
    ]

    # Formats without product source
    try:
        import yaml
        reg = yaml.safe_load(
            (repo_root / "registry" / "format-registry.yaml").read_text(
                encoding="utf-8", errors="replace"
            )
        )
        no_source = []
        for f in reg.get("formats", []):
            fid = f.get("format_id", "")
            if fid == "odf-shared":
                continue
            if not (repo_root / "src" / "python" / fid).is_dir():
                no_source.append(fid.upper())
        if no_source:
            lines.append(
                f"- **Formats without product source** ({len(no_source)}): "
                f"{', '.join(no_source)}"
            )
    except Exception:
        pass

    lines.extend([
        "- **Package publication**: All Python packages are local-only; none published to PyPI",
        "- **Commercial .NET release**: Gate 11 execution approval pending (Babar Raza)",
        "- **External users**: No external users yet; all testing is internal",
        "",
    ])
    return "\n".join(lines)


def _generate_footer(timestamp: str) -> str:
    return "\n".join([
        "---",
        "",
        f"*Generated at {timestamp} by `tools/docs/generate_project_status.py`*",
        "",
    ])


def generate_project_status(
    repo_root: Path = REPO_ROOT,
    output_path: Path | None = None,
    dry_run: bool = False,
) -> str:
    """Generate the full PROJECT_STATUS.md content."""
    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")

    # Collect all data
    stats = collect_statistics(repo_root)
    inventory = collect_product_inventory(repo_root)
    arch = collect_architecture_inventory(repo_root)
    agents = collect_agent_inventory(repo_root)

    # Assemble document
    parts = [
        _generate_header(timestamp),
        render_statistics_markdown(stats),
        render_product_inventory_markdown(inventory),
        render_architecture_markdown(arch),
        render_agent_inventory_markdown(agents),
        _generate_limitations(repo_root, stats),
        _generate_footer(timestamp),
    ]
    content = "\n".join(parts)

    if not dry_run:
        target = output_path or (repo_root / "PROJECT_STATUS.md")
        target.write_text(content, encoding="utf-8")
        print(f"Written to {target}", file=sys.stderr)

    return content


def update_readme(repo_root: Path, stats: dict) -> None:
    """Inject PROJECT_STATUS.md reference into README.md using markers."""
    readme_path = repo_root / "README.md"
    if not readme_path.exists():
        return

    readme = readme_path.read_text(encoding="utf-8")
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Build the injection block
    oracle = stats.get("oracle", {})
    gov = stats.get("governance", {})
    infra = stats.get("infrastructure", {})
    fmt = stats.get("formats", {})
    cert = stats.get("certification", {})

    block = "\n".join([
        f"<!-- BEGIN:PROJECT-STATUS-REF generated={timestamp} source=PROJECT_STATUS.md -->",
        f"**Quick numbers:** {fmt.get('active_with_source', 0)} active formats | "
        f"{oracle.get('pass_rate', 'N/A')} oracle cases | "
        f"{gov.get('validators', 0)} validators | "
        f"{gov.get('skills', 0)} skills | "
        f"{infra.get('sprint_count', 0)}+ sprints | "
        f"{cert.get('certified', 0)}/{cert.get('total', 0)} certified",
        "",
        "For the full auto-generated project status with per-format details, see "
        "[PROJECT_STATUS.md](PROJECT_STATUS.md).",
        "Re-generate: `python tools/docs/generate_project_status.py`",
        "<!-- END:PROJECT-STATUS-REF -->",
    ])

    begin_marker = "<!-- BEGIN:PROJECT-STATUS-REF"
    end_marker = "<!-- END:PROJECT-STATUS-REF -->"

    if begin_marker in readme:
        # Replace existing block
        pattern = re.compile(
            r"<!-- BEGIN:PROJECT-STATUS-REF[^\n]*-->.*?<!-- END:PROJECT-STATUS-REF -->",
            re.DOTALL,
        )
        readme = pattern.sub(block, readme)
    else:
        # Insert before "## Keeping This README Current" or at end
        insert_point = readme.find("## Keeping This README Current")
        if insert_point >= 0:
            readme = readme[:insert_point] + block + "\n\n" + readme[insert_point:]
        else:
            readme = readme.rstrip() + "\n\n" + block + "\n"

    readme_path.write_text(readme, encoding="utf-8")
    print("Updated README.md with PROJECT_STATUS.md reference", file=sys.stderr)

    # Also add to drift table if not present
    if "PROJECT_STATUS.md" not in readme:
        pass  # Already handled by the injection block


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate PROJECT_STATUS.md")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--dry-run", action="store_true",
                        help="Print to stdout, don't write file")
    parser.add_argument("--json", action="store_true",
                        help="Output raw collected data as JSON")
    parser.add_argument("--update-readme", action="store_true",
                        help="Also inject reference into README.md")
    args = parser.parse_args()

    if args.json:
        data = {
            "statistics": collect_statistics(args.repo_root),
            "product_inventory": collect_product_inventory(args.repo_root),
            "architecture": collect_architecture_inventory(args.repo_root),
            "agents": collect_agent_inventory(args.repo_root),
        }
        print(json.dumps(data, indent=2, default=str))
        return 0

    content = generate_project_status(args.repo_root, args.output, args.dry_run)

    if args.dry_run:
        print(content)

    if args.update_readme:
        stats = collect_statistics(args.repo_root)
        update_readme(args.repo_root, stats)

    return 0


if __name__ == "__main__":
    sys.exit(main())
