"""Generate PROJECT_STATUS.md — canonical two-lane project status document.

Produces a structured document with stable HTML anchors separating Machinery Lane
(governance, validators, capabilities, skills, supervisor) from Product Lane
(formats, oracle, certification, gates, implementations).

Usage:
    python tools/docs/generate_project_status.py
    python tools/docs/generate_project_status.py --dry-run
    python tools/docs/generate_project_status.py --validate
    python tools/docs/generate_project_status.py --update-readme
    python tools/docs/generate_project_status.py --timestamp 2026-01-01T00:00:00+00:00
    python tools/docs/generate_project_status.py --output /tmp/status.md
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# Import sub-generators
sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_agent_inventory import collect_agent_inventory
from generate_architecture_inventory import collect_architecture_inventory
from generate_product_inventory import collect_product_inventory
from generate_statistics import collect_statistics

# Stable anchor names — exported for test assertions
REQUIRED_ANCHORS = [
    "status-at-a-glance",
    "machinery-lane",
    "product-lane",
    "shared-boundaries",
    "known-limitations",
    "generation-evidence",
]

# Layer paths that are gitignored local state — suppress file counts for these
GITIGNORED_LAYER_PATHS = {".local/supervisor/", ".local/evidences/"}


def _anchor(name: str) -> str:
    """Return a stable HTML anchor tag."""
    return f'<a name="{name}"></a>'


def _read_yaml(path: Path):
    if not path.exists():
        return None
    try:
        import yaml
        return yaml.safe_load(path.read_text(encoding="utf-8", errors="replace"))
    except Exception:
        return None


def _read_json(path: Path):
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except Exception:
        return None


def _get_head_revision(repo_root: Path) -> str:
    """Return short git HEAD SHA, or 'UNKNOWN' if not available."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, cwd=str(repo_root), timeout=10,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return "UNKNOWN"


def _atomic_write(target: Path, content: str) -> None:
    """Write content to target atomically via a .tmp file."""
    tmp = target.with_suffix(".tmp")
    try:
        tmp.write_text(content, encoding="utf-8")
        tmp.replace(target)
    except Exception:
        if tmp.exists():
            try:
                tmp.unlink()
            except Exception:
                pass
        raise


def validate_output(content: str) -> list[str]:
    """Validate generated content against the two-lane contract.

    Returns a list of violation strings; empty list means PASS.
    """
    violations = []

    if "DO NOT EDIT MANUALLY" not in content:
        violations.append("Missing 'DO NOT EDIT MANUALLY' marker")

    required_sections = [
        "## Machinery Lane",
        "## Product Lane",
        "## Shared Boundaries",
        "## Generation and Evidence",
    ]
    for section in required_sections:
        if section not in content:
            violations.append(f"Missing required section: {section!r}")

    for anchor in REQUIRED_ANCHORS:
        count = content.count(f'name="{anchor}"')
        if count == 0:
            violations.append(f"Missing required anchor: {anchor!r}")
        elif count > 1:
            violations.append(f"Duplicate anchor: {anchor!r} appears {count} times")

    return violations


def _generate_header(timestamp: str) -> str:
    lines = [
        "<!-- AUTO-GENERATED by tools/docs/generate_project_status.py -->",
        f"<!-- Generated: {timestamp} -->",
        "<!-- Re-generate: python tools/docs/generate_project_status.py -->",
        "<!-- DO NOT EDIT MANUALLY — changes will be overwritten -->",
        "",
        "# Format Factory — Project Status",
        "",
        "Auto-generated from repository evidence. Every number traces to a canonical "
        "source. Machinery and Product lanes are separated to avoid mixing governance "
        "health with delivery progress.",
        "",
        "**Table of Contents**",
        "- [Status at a Glance](#status-at-a-glance)",
        "- [Machinery Lane](#machinery-lane)",
        "  - [Architecture and Layer Inventory](#machinery-architecture)",
        "  - [Governance Validators](#machinery-validators)",
        "  - [Capabilities and Skills](#machinery-capabilities)",
        "  - [Supervisor and Autonomous Execution](#machinery-supervision)",
        "  - [Machinery Limitations](#machinery-limitations)",
        "- [Product Lane](#product-lane)",
        "  - [Format and Family Inventory](#product-inventory)",
        "  - [Oracle Verification](#product-oracle)",
        "  - [Certification Status](#product-certification)",
        "  - [Gate Progress](#product-gates)",
        "  - [Product Maturity](#product-maturity)",
        "  - [Product Limitations](#product-limitations)",
        "- [Shared Boundaries](#shared-boundaries)",
        "- [Known Limitations](#known-limitations)",
        "- [Generation and Evidence](#generation-evidence)",
        "",
        "---",
        "",
    ]
    return "\n".join(lines)


def _render_status_at_a_glance(stats: dict, agents: dict) -> str:
    gov = stats.get("governance", {})
    oracle = stats.get("oracle", {})
    fmt = stats.get("formats", {})
    cert = stats.get("certification", {})
    infra = stats.get("infrastructure", {})

    lines = [
        _anchor("status-at-a-glance"),
        "## Status at a Glance",
        "",
        "| Lane | Metric | Value |",
        "|---|---|---|",
        f"| Machinery | Governance validators | {gov.get('validators', 0)} |",
        f"| Machinery | Active capabilities | {gov.get('capabilities_active', 0)} of {gov.get('capabilities_total', 0)} |",
        f"| Machinery | Skills registered | {gov.get('skills', 0)} |",
        f"| Machinery | Autonomous sprints | {infra.get('sprint_count', 0)} |",
        f"| Product | Formats in registry | {fmt.get('total_in_registry', 0)} |",
        f"| Product | Active (with source) | {fmt.get('active_with_source', 0)} |",
        f"| Product | Oracle pass rate | {oracle.get('pass_rate', 'N/A')} |",
        f"| Product | Certified formats | {cert.get('certified', 0)} of {cert.get('total', 0)} with source |",
        "",
    ]
    return "\n".join(lines)


def _render_machinery_lane(stats: dict, arch: dict, agents: dict) -> str:
    gov = stats.get("governance", {})
    layers = arch.get("layers", [])
    validators_data = arch.get("validators", {})
    capabilities_data = arch.get("capabilities", {})
    skills_data = arch.get("skills", {})
    gates = arch.get("gates", [])

    policies = agents.get("policies", {})
    prohibitions = policies.get("hard_prohibitions", [])
    infra = stats.get("infrastructure", {})

    lines = [
        _anchor("machinery-lane"),
        "## Machinery Lane",
        "",
        "Governance, supervision, validators, capabilities, and skills. "
        "These metrics describe the health of the autonomous machinery itself.",
        "",
    ]

    # Architecture and Layer Inventory
    lines += [
        _anchor("machinery-architecture"),
        "### Architecture and Layer Inventory",
        "",
        "Format Factory uses 11 independent layers, each with defined responsibilities.",
        "",
        "| Layer | Name | Purpose | Files |",
        "|---|---|---|---|",
    ]
    for layer in layers:
        paths = layer.get("paths", [])
        is_gitignored = any(
            any(gs in p for gs in GITIGNORED_LAYER_PATHS)
            for p in paths
        )
        if is_gitignored:
            file_count = "(gitignored local state)"
        else:
            file_count = str(layer.get("file_count", 0))
        lines.append(
            f"| {layer['id']} | {layer['name']} | {layer['purpose']} | {file_count} |"
        )
    lines.append("")

    # Governance Validators
    lines += [
        _anchor("machinery-validators"),
        "### Governance Validators",
        "",
        f"**{validators_data.get('total', 0)} validators** across "
        f"**{validators_data.get('module_count', 0)} modules** "
        f"(source: `tools/supervisor/governance_validators*.py`)",
        "",
        "| Module | Validators |",
        "|---|---|",
    ]
    for mod_name, names in validators_data.get("modules", {}).items():
        lines.append(f"| `{mod_name}` | {len(names)} |")
    lines.append("")

    # Capabilities and Skills
    cap_active = capabilities_data.get("active", 0)
    cap_total = capabilities_data.get("total", 0)
    tracks = capabilities_data.get("tracks", {})

    lines += [
        _anchor("machinery-capabilities"),
        "### Capabilities and Skills",
        "",
        f"**{cap_active} active** of {cap_total} total capabilities "
        f"(source: `.governance/capabilities/registry.yaml`)",
        "",
        "| Product Track | Count |",
        "|---|---|",
    ]
    for track, count in sorted(tracks.items()):
        display_track = "(no product_track)" if track == "unclassified" else track
        lines.append(f"| {display_track} | {count} |")
    if any(t == "unclassified" for t in tracks):
        lines.append("")
        lines.append(
            "_Note: (no product_track) = no product_track assigned — machinery/infra tier_"
        )
    lines.append("")

    skill_total = skills_data.get("total", 0)
    skill_statuses = skills_data.get("statuses", {})
    lines += [
        f"**{skill_total} skills** registered (source: `.supervisor/skill-registry.yaml`)",
        "",
    ]
    if skill_statuses:
        lines += ["| Status | Count |", "|---|---|"]
        for st, count in sorted(skill_statuses.items()):
            lines.append(f"| {st} | {count} |")
        lines.append("")

    # Supervisor and Autonomous Execution
    max_iter = policies.get("max_iterations", "N/A")
    ckpt = policies.get("checkpoint_interval")
    ckpt_display = "not configured" if ckpt is None else str(ckpt)
    sprint_count = infra.get("sprint_count", 0)
    avg_quality = infra.get("avg_quality", 0.0)

    lines += [
        _anchor("machinery-supervision"),
        "### Supervisor and Autonomous Execution",
        "",
        f"- **Autonomous sprints completed:** {sprint_count} "
        f"(source: `reports/supervisor/maturity-trend.json`)",
        f"- **Avg evidence quality:** {avg_quality:.2f} (0.0–1.0 scale)",
        f"- **Max iterations per session:** {max_iter} "
        f"(source: `.supervisor/policies.yaml`)",
        f"- **Checkpoint interval:** {ckpt_display}",
        "",
    ]

    if prohibitions:
        lines += [
            "**Hard prohibitions** (from `.supervisor/policies.yaml`):",
            "",
        ]
        for p in prohibitions:
            note = ""
            # Cross-check: gate_N_approval prohibition with autonomous gates
            gate_match = re.match(r"gate_(\d+)_approval", p)
            if gate_match:
                gate_num = gate_match.group(1)
                matching_gates = [
                    g for g in gates
                    if str(g.get("gate_id", "")).endswith(gate_num)
                    and g.get("autonomous", True)
                ]
                if matching_gates:
                    note = (
                        " _(business security sign-off, distinct from "
                        f"executing Gate {gate_num} technical steps)_"
                    )
            lines.append(f"- `{p}`{note}")
        lines.append("")

    # Machinery Limitations
    lines += [
        _anchor("machinery-limitations"),
        "### Machinery Limitations",
        "",
        "- **LAYER_DEFINITIONS is hardcoded** in `generate_architecture_inventory.py` — "
        "layer paths are not derived from a registry. Adding a new layer requires "
        "updating the constant manually.",
        "- **L08/L09 file counts** are gitignored local state — counts vary by machine "
        "and session; not meaningful for cross-machine comparison.",
        "- **Governance validator runner** is not integrated into pre-commit hooks for "
        "all validators — only a subset are enforced at commit time.",
        "",
    ]

    return "\n".join(lines)


def _render_product_lane(stats: dict, inventory: list, arch: dict) -> str:
    oracle = stats.get("oracle", {})
    fmt = stats.get("formats", {})
    cert = stats.get("certification", {})
    gates = arch.get("gates", [])

    formats_list = inventory if isinstance(inventory, list) else []
    total_in_registry = fmt.get("total_in_registry", 0)
    active_with_source = fmt.get("active_with_source", 0)
    families = fmt.get("families", {})

    lines = [
        _anchor("product-lane"),
        "## Product Lane",
        "",
        "Format implementations, oracle verification, certification, and gates. "
        "These metrics describe the health and completeness of the product itself.",
        "",
    ]

    # Format and Family Inventory
    lines += [
        _anchor("product-inventory"),
        "### Format and Family Inventory",
        "",
        f"**{total_in_registry} formats** in registry (excluding odf-shared shared library). "
        f"**{active_with_source} formats** have Python source. "
        f"**{len(families)} families**: {', '.join(sorted(families.keys()))}.",
        "",
        "Source: `registry/format-registry.yaml`",
        "",
    ]

    # Per-format table
    if formats_list:
        lines += [
            "| Format | Family | Source | Oracle | Certified | Gate |",
            "|---|---|---|---|---|---|",
        ]
        for f in formats_list:
            fid = f.get("format_id", "?")
            family = f.get("family", "?")
            has_src = f.get("has_source", False)
            src_mark = "yes" if has_src else "-"
            oracle_rate = f.get("oracle_pass_rate", "N/A")
            if not has_src and oracle_rate in ("N/A", None):
                oracle_rate = "- (no source)"
            cert_status = f.get("certification_status", "N/A")
            if not has_src and cert_status in ("N/A", None):
                cert_status = "- (no source)"
            gate_summary = f.get("gate_summary", "N/A")
            lines.append(
                f"| {fid} | {family} | {src_mark} | {oracle_rate} | {cert_status} | {gate_summary} |"
            )
        lines.append("")

    # Oracle Verification
    formats_verified = oracle.get("formats_verified", 0)
    total_cases = oracle.get("total_cases", 0)
    total_pass = oracle.get("total_pass", 0)
    pass_rate = oracle.get("pass_rate", "0/0")

    lines += [
        _anchor("product-oracle"),
        "### Oracle Verification",
        "",
        f"**{formats_verified} of {total_in_registry - 1} tracked formats** have oracle results. "
        f"Pass rate: **{pass_rate}** ({total_pass}/{total_cases} cases).",
        "",
        "Source: `oracle/formats/*/reports/oracle-run-summary.json`",
        "",
    ]

    # Certification Status
    certified = cert.get("certified", 0)
    cert_total = cert.get("total", 0)

    lines += [
        _anchor("product-certification"),
        "### Certification Status",
        "",
        f"**{certified} of {cert_total} formats with source** are certified. "
        "Formats without source are excluded from this count.",
        "",
        "Source: `reports/certification/portfolio-certification-matrix.json`",
        "",
    ]

    # Gate Progress
    lines += [
        _anchor("product-gates"),
        "### Gate Progress",
        "",
        f"**{len(gates)} gates** in the acquisition pipeline "
        f"(source: `registry/gate-contract-registry.yaml`).",
        "",
    ]
    if gates:
        lines += [
            "| Gate | Title | Agent-Executable |",
            "|---|---|---|",
        ]
        for g in gates:
            auto = "Yes" if g.get("autonomous", True) else "No (human required)"
            lines.append(f"| {g['gate_id']} | {g['title']} | {auto} |")
        lines.append("")

    # Product Maturity
    lines += [
        _anchor("product-maturity"),
        "### Product Maturity",
        "",
        "Maturity dimensions per format: REGISTERED → SOURCE_PRESENT → ORACLE_VERIFIED → CERTIFIED",
        "",
        f"- **REGISTERED**: {total_in_registry} formats",
        f"- **SOURCE_PRESENT**: {active_with_source} formats",
        f"- **ORACLE_VERIFIED**: {formats_verified} formats",
        f"- **CERTIFIED**: {certified} formats",
        "",
    ]

    # Product Limitations
    no_source_formats = [
        f.get("format_id", "?").upper()
        for f in formats_list
        if not f.get("has_source", False)
    ]

    lines += [
        _anchor("product-limitations"),
        "### Product Limitations",
        "",
    ]
    if no_source_formats:
        lines.append(
            f"- **Formats without source** ({len(no_source_formats)}): "
            f"{', '.join(no_source_formats)}"
        )
        # Mention ORA explicitly if in the list
        if "ORA" in no_source_formats:
            lines.append(
                "  - ORA and similar imaging formats have no Python source — "
                "oracle and certification not applicable"
            )
    lines.append("")

    return "\n".join(lines)


def _render_shared_boundaries(stats: dict) -> str:
    infra = stats.get("infrastructure", {})
    src = stats.get("source", {})
    tests = stats.get("tests", {})

    lines = [
        _anchor("shared-boundaries"),
        "## Shared Boundaries",
        "",
        "Resources shared between Machinery and Product lanes.",
        "",
        "| Resource | Count | Source |",
        "|---|---|---|",
        f"| Python source files | {src.get('python_files', 0)} | `src/python/` |",
        f"| .NET source files | {src.get('dotnet_files', 0)} | `src/net/` |",
        f"| Python tests | {tests.get('python', 0)} | `tests/python/` |",
        f"| .NET tests | {tests.get('dotnet', 0)} | `tests/net/` |",
        f"| Supervisor tests | {tests.get('supervisor', 0)} | `tests/supervisor/` |",
        f"| Sample files | {infra.get('sample_count', 0)} | `samples/by-format/` |",
        f"| Documentation files | {infra.get('doc_count', 0)} | `docs/` |",
        "",
    ]
    return "\n".join(lines)


def _generate_limitations(repo_root: Path, stats: dict, inventory: dict | None = None) -> str:
    lines = [
        _anchor("known-limitations"),
        "## Known Limitations",
        "",
    ]

    # Machinery Limitations
    lines += [
        "### Machinery Limitations",
        "",
        "- **LAYER_DEFINITIONS is hardcoded** in `generate_architecture_inventory.py` — "
        "not derived from a registry. Manual update required when adding layers.",
        "- **L08/L09** are gitignored local state; file counts vary by machine.",
        "- **Checkpoint interval** is not configured in `.supervisor/policies.yaml`.",
        "",
    ]

    # Product Limitations
    lines += [
        "### Product Limitations",
        "",
    ]

    # Formats without source — derive from inventory or registry
    no_source = []
    if inventory:
        inv_list = inventory if isinstance(inventory, list) else inventory.get("formats", [])
        no_source = [
            f.get("format_id", "?").upper()
            for f in inv_list
            if not f.get("has_source", False)
        ]
    else:
        try:
            import yaml
            reg = yaml.safe_load(
                (repo_root / "registry" / "format-registry.yaml").read_text(
                    encoding="utf-8", errors="replace"
                )
            )
            for f in reg.get("formats", []):
                fid = f.get("format_id", "")
                if fid == "odf-shared":
                    continue
                if not (repo_root / "src" / "python" / fid).is_dir():
                    no_source.append(fid.upper())
        except Exception:
            pass

    if no_source:
        lines.append(
            f"- **Formats without source** ({len(no_source)}): "
            f"{', '.join(no_source)} (no product_track)"
        )
    lines += [
        "- **PyPI publication**: All Python packages are local-only; not published to PyPI",
        "",
    ]

    # Release Limitations
    lines += [
        "### Release Limitations",
        "",
        "- **Commercial .NET release**: Gate 11 execution approval pending (Babar Raza)",
        "- **External users**: No external users yet; all testing is internal",
        "",
    ]

    return "\n".join(lines)


def _render_generation_evidence(timestamp: str, head_revision: str, repo_root: Path) -> str:
    lines = [
        _anchor("generation-evidence"),
        "## Generation and Evidence",
        "",
        "- **Generator**: `tools/docs/generate_project_status.py`",
        f"- **Generated at**: {timestamp}",
        f"- **HEAD revision**: {head_revision}",
        "- **Regen command**: `python tools/docs/generate_project_status.py`",
        "",
        "**Canonical sources read by this generator:**",
        "",
        "| Source | Purpose |",
        "|---|---|",
        "| `registry/format-registry.yaml` | Format list, families, gate status |",
        "| `.governance/capabilities/registry.yaml` | Capability tracks and counts |",
        "| `.supervisor/skill-registry.yaml` | Skill count and status |",
        "| `oracle/formats/*/reports/oracle-run-summary.json` | Per-format oracle results |",
        "| `reports/certification/portfolio-certification-matrix.json` | Certification status |",
        "| `reports/supervisor/maturity-trend.json` | Sprint count, avg quality |",
        "| `tools/supervisor/governance_validators*.py` | Validator count |",
        "| `.supervisor/policies.yaml` | Hard prohibitions, checkpoint |",
        "| `src/python/`, `src/net/` | Source file counts |",
        "| `tests/` | Test file counts |",
        "| `registry/gate-contract-registry.yaml` | Gate definitions |",
        "",
    ]
    return "\n".join(lines)


def generate_project_status(
    repo_root: Path = REPO_ROOT,
    output_path: Path | None = None,
    dry_run: bool = False,
    timestamp_override: str | None = None,
) -> str:
    """Generate the full two-lane PROJECT_STATUS.md content."""
    timestamp = timestamp_override or datetime.now(timezone.utc).isoformat(timespec="seconds")
    head_revision = _get_head_revision(repo_root)

    # Collect all data
    stats = collect_statistics(repo_root)
    inventory = collect_product_inventory(repo_root)
    arch = collect_architecture_inventory(repo_root)
    agents = collect_agent_inventory(repo_root)

    # Assemble two-lane document
    parts = [
        _generate_header(timestamp),
        _render_status_at_a_glance(stats, agents),
        _render_machinery_lane(stats, arch, agents),
        _render_product_lane(stats, inventory, arch),
        _render_shared_boundaries(stats),
        _generate_limitations(repo_root, stats, inventory),
        _render_generation_evidence(timestamp, head_revision, repo_root),
    ]
    content = "\n".join(parts)

    if not dry_run:
        target = output_path or (repo_root / "PROJECT_STATUS.md")
        _atomic_write(target, content)
        print(f"Written to {target}", file=sys.stderr)

    return content


def update_readme(repo_root: Path, stats: dict) -> None:
    """Inject PROJECT_STATUS.md reference into README.md using markers."""
    readme_path = repo_root / "README.md"
    if not readme_path.exists():
        return

    readme = readme_path.read_text(encoding="utf-8")
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    oracle = stats.get("oracle", {})
    gov = stats.get("governance", {})
    infra = stats.get("infrastructure", {})
    fmt = stats.get("formats", {})
    cert = stats.get("certification", {})

    block = "\n".join([
        f"<!-- BEGIN:PROJECT-STATUS-REF generated={timestamp} source=PROJECT_STATUS.md -->",
        f"**Quick numbers (machinery):** {gov.get('validators', 0)} validators | "
        f"{gov.get('skills', 0)} skills | "
        f"{infra.get('sprint_count', 0)} sprints",
        "",
        f"**Quick numbers (product):** {fmt.get('active_with_source', 0)} active formats | "
        f"{oracle.get('pass_rate', 'N/A')} oracle cases | "
        f"{cert.get('certified', 0)}/{cert.get('total', 0)} certified",
        "",
        "For full auto-generated project status with per-format details and two-lane "
        "(machinery / product) breakdown, see "
        "[PROJECT_STATUS.md](PROJECT_STATUS.md#status-at-a-glance).",
        "<!-- END:PROJECT-STATUS-REF -->",
    ])

    begin_marker = "<!-- BEGIN:PROJECT-STATUS-REF"
    end_marker = "<!-- END:PROJECT-STATUS-REF -->"

    if begin_marker in readme:
        pattern = re.compile(
            r"<!-- BEGIN:PROJECT-STATUS-REF[^\n]*-->.*?<!-- END:PROJECT-STATUS-REF -->",
            re.DOTALL,
        )
        readme = pattern.sub(block, readme)
    else:
        insert_point = readme.find("## Keeping This README Current")
        if insert_point >= 0:
            readme = readme[:insert_point] + block + "\n\n" + readme[insert_point:]
        else:
            readme = readme.rstrip() + "\n\n" + block + "\n"

    readme_path.write_text(readme, encoding="utf-8")
    print("Updated README.md with PROJECT_STATUS.md reference", file=sys.stderr)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate PROJECT_STATUS.md")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--dry-run", action="store_true",
                        help="Return content without writing file")
    parser.add_argument("--validate", action="store_true",
                        help="Validate structure and exit 0/1")
    parser.add_argument("--timestamp", type=str, default=None,
                        help="Override timestamp for deterministic output")
    parser.add_argument("--json", action="store_true",
                        help="Output raw collected data as JSON")
    parser.add_argument("--update-readme", action="store_true",
                        help="Also inject reference into README.md")
    args = parser.parse_args()

    if args.json:
        data = {
            "statistics": collect_statistics(args.repo_root),
            "product_inventory": collect_product_inventory(args.repo_root),
            "architecture": collect_architecture_inventory(args.repo_root),
            "agents": collect_agent_inventory(args.repo_root),
        }
        print(json.dumps(data, indent=2, default=str))
        return 0

    if args.validate:
        content = generate_project_status(
            args.repo_root,
            dry_run=True,
            timestamp_override=args.timestamp,
        )
        violations = validate_output(content)
        if violations:
            print("VIOLATIONS:", file=sys.stderr)
            for v in violations:
                print(f"  - {v}", file=sys.stderr)
            return 1
        print("VALID: PROJECT_STATUS.md contract satisfied")
        return 0

    content = generate_project_status(
        args.repo_root,
        args.output,
        args.dry_run,
        timestamp_override=args.timestamp,
    )

    if args.dry_run:
        print(content)

    if args.update_readme:
        stats = collect_statistics(args.repo_root)
        update_readme(args.repo_root, stats)

    return 0


if __name__ == "__main__":
    sys.exit(main())
