"""AI test generation — proposal-based test generation with authority lifecycle.

Generated tests are proposals with authority state ai_draft.
They must pass authority lifecycle and reviewer gate before entering test suites.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from typing import Any

from tools.ai.schemas.models import ArtifactAuthorityStateValue


@dataclass
class GeneratedTestProposal:
    """A proposed test case generated by AI."""
    proposal_id: str = ""
    source_requirement_ids: list[str] = field(default_factory=list)
    source_chunk_ids: list[str] = field(default_factory=list)
    proposed_test_name: str = ""
    target_file: str = ""
    risk_covered: str = ""
    expected_oracle: str = ""
    authority_state: ArtifactAuthorityStateValue = ArtifactAuthorityStateValue.ai_draft
    test_code: str = ""
    rationale: str = ""
    created_at: str = ""
    proposal_hash: str = ""

    def compute_hash(self) -> str:
        raw = f"{self.proposed_test_name}|{self.test_code}|{self.target_file}"
        self.proposal_hash = hashlib.sha256(raw.encode()).hexdigest()[:16]
        return self.proposal_hash

    def validate(self) -> list[str]:
        errors: list[str] = []
        if not self.proposal_id:
            errors.append("missing proposal_id")
        if not self.proposed_test_name:
            errors.append("missing proposed_test_name")
        if not self.target_file:
            errors.append("missing target_file")
        if not self.test_code:
            errors.append("missing test_code")
        if not self.source_requirement_ids and not self.source_chunk_ids:
            errors.append("must have at least one source_requirement_id or source_chunk_id")
        if self.authority_state != ArtifactAuthorityStateValue.ai_draft:
            errors.append(f"initial authority_state must be ai_draft, got {self.authority_state.value}")
        return errors

    def to_dict(self) -> dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "source_requirement_ids": self.source_requirement_ids,
            "source_chunk_ids": self.source_chunk_ids,
            "proposed_test_name": self.proposed_test_name,
            "target_file": self.target_file,
            "risk_covered": self.risk_covered,
            "expected_oracle": self.expected_oracle,
            "authority_state": self.authority_state.value,
            "test_code": self.test_code,
            "rationale": self.rationale,
            "created_at": self.created_at,
            "proposal_hash": self.proposal_hash,
        }


class ProposalReviewer:
    """Reviews test proposals for acceptance or rejection."""

    def __init__(self):
        self._accepted: list[GeneratedTestProposal] = []
        self._rejected: list[tuple[GeneratedTestProposal, str]] = []

    def review(self, proposal: GeneratedTestProposal) -> tuple[bool, list[str]]:
        """Review a proposal. Returns (accepted, errors)."""
        errors = proposal.validate()
        if errors:
            self._rejected.append((proposal, "; ".join(errors)))
            return False, errors

        if not proposal.proposal_hash:
            proposal.compute_hash()

        self._accepted.append(proposal)
        return True, []

    def reject(self, proposal: GeneratedTestProposal, reason: str) -> None:
        """Explicitly reject a proposal."""
        proposal.authority_state = ArtifactAuthorityStateValue.rejected
        self._rejected.append((proposal, reason))

    @property
    def accepted_count(self) -> int:
        return len(self._accepted)

    @property
    def rejected_count(self) -> int:
        return len(self._rejected)

    def get_accepted_metadata(self) -> list[dict[str, Any]]:
        return [p.to_dict() for p in self._accepted]


class EvidenceReviewHelper:
    """Inspects evidence bundles/reports and produces ai_draft gap findings."""

    def review_directory(self, directory: Path) -> list[dict[str, str]]:  # noqa: F821
        """Scan a directory for evidence gaps. Returns ai_draft findings."""
        from pathlib import Path as P
        findings: list[dict[str, str]] = []
        dir_path = P(directory) if not isinstance(directory, P) else directory

        if not dir_path.exists():
            findings.append({
                "type": "missing_directory",
                "path": str(dir_path),
                "severity": "high",
                "authority_state": "ai_draft",
            })
            return findings

        md_files = list(dir_path.rglob("*.md"))
        yaml_files = list(dir_path.rglob("*.yaml"))

        if not md_files:
            findings.append({
                "type": "no_markdown_reports",
                "path": str(dir_path),
                "severity": "medium",
                "authority_state": "ai_draft",
            })

        if not yaml_files:
            findings.append({
                "type": "no_yaml_contracts",
                "path": str(dir_path),
                "severity": "low",
                "authority_state": "ai_draft",
            })

        for md in md_files:
            content = md.read_text(encoding="utf-8", errors="ignore")
            if "PENDING" in content or "TODO" in content:
                findings.append({
                    "type": "incomplete_report",
                    "path": str(md),
                    "severity": "medium",
                    "authority_state": "ai_draft",
                })

        return findings
