"""autonomy_route_models.py — Shared constants for autonomy routing.

No dependency on action_queue.py or other heavy supervisor modules.
"""
from __future__ import annotations

# --- Routes ---
ROUTE_AUTONOMOUS_ACCELERATED_DEFAULT = "AUTONOMOUS_ACCELERATED_DEFAULT"
ROUTE_AGENT_GOVERNED_DECISION_REQUIRED = "AGENT_GOVERNED_ROUTE_DECISION_REQUIRED"
ROUTE_GOVERNED_DIRECT_EXECUTION = "GOVERNED_DIRECT_EXECUTION"
ROUTE_HUMAN_APPROVAL_REQUIRED = "HUMAN_APPROVAL_REQUIRED"
ROUTE_BLOCKED = "BLOCKED_UNSAFE_OR_UNCLASSIFIED"

ALL_ROUTES = frozenset({
    ROUTE_AUTONOMOUS_ACCELERATED_DEFAULT,
    ROUTE_AGENT_GOVERNED_DECISION_REQUIRED,
    ROUTE_GOVERNED_DIRECT_EXECUTION,
    ROUTE_HUMAN_APPROVAL_REQUIRED,
    ROUTE_BLOCKED,
})

# --- Task categories ---
TASK_CATEGORY_PRODUCT_IMPLEMENTATION = "PRODUCT_IMPLEMENTATION"
TASK_CATEGORY_PRODUCT_TESTING = "PRODUCT_TESTING"
TASK_CATEGORY_PRODUCT_CAPABILITY_EXPANSION = "PRODUCT_CAPABILITY_EXPANSION"
TASK_CATEGORY_PRODUCT_EXPORT_OR_DOGFOOD = "PRODUCT_EXPORT_OR_DOGFOOD"

TASK_CATEGORY_SPEC_AUTHORITY_MACHINERY = "SPEC_AUTHORITY_MACHINERY"
TASK_CATEGORY_REQUIREMENT_CAPABILITY_MACHINERY = "REQUIREMENT_CAPABILITY_MACHINERY"
TASK_CATEGORY_ACTION_QUEUE_MACHINERY = "ACTION_QUEUE_MACHINERY"
TASK_CATEGORY_AUTONOMY_ORCHESTRATOR_MACHINERY = "AUTONOMY_ORCHESTRATOR_MACHINERY"
TASK_CATEGORY_SUPERVISOR_VERDICT_MACHINERY = "SUPERVISOR_VERDICT_MACHINERY"
TASK_CATEGORY_VALIDATOR_OR_EVIDENCE_MACHINERY = "VALIDATOR_OR_EVIDENCE_MACHINERY"
TASK_CATEGORY_PROMPT_GENERATION_MACHINERY = "PROMPT_GENERATION_MACHINERY"
TASK_CATEGORY_GOVERNED_SKILL_MACHINERY = "GOVERNED_SKILL_OR_GENERATOR_MACHINERY"
TASK_CATEGORY_UNKNOWN = "UNKNOWN_OR_AMBIGUOUS"

TASK_CATEGORIES_PRODUCT = frozenset({
    TASK_CATEGORY_PRODUCT_IMPLEMENTATION,
    TASK_CATEGORY_PRODUCT_TESTING,
    TASK_CATEGORY_PRODUCT_CAPABILITY_EXPANSION,
    TASK_CATEGORY_PRODUCT_EXPORT_OR_DOGFOOD,
})

TASK_CATEGORIES_MACHINERY = frozenset({
    TASK_CATEGORY_SPEC_AUTHORITY_MACHINERY,
    TASK_CATEGORY_REQUIREMENT_CAPABILITY_MACHINERY,
    TASK_CATEGORY_ACTION_QUEUE_MACHINERY,
    TASK_CATEGORY_AUTONOMY_ORCHESTRATOR_MACHINERY,
    TASK_CATEGORY_SUPERVISOR_VERDICT_MACHINERY,
    TASK_CATEGORY_VALIDATOR_OR_EVIDENCE_MACHINERY,
    TASK_CATEGORY_PROMPT_GENERATION_MACHINERY,
    TASK_CATEGORY_GOVERNED_SKILL_MACHINERY,
})

ALL_TASK_CATEGORIES = TASK_CATEGORIES_PRODUCT | TASK_CATEGORIES_MACHINERY | {TASK_CATEGORY_UNKNOWN}

# --- Schema ---
SCHEMA_VERSION = "1.0"
DECISION_ACTOR_DEFAULT = "autonomy_route_decider"
ROUTE_DECISIONS_DIR = ".local/supervisor/route-decisions"

# --- Source-mutating action types ---
SOURCE_MUTATING_ACTION_TYPES = frozenset({
    "IMPLEMENT_SMALL_PRODUCT_FEATURE",
    "PRODUCT_SOURCE_PATCH_BOUNDED",
})

# --- Required fields for route decision ---
REQUIRED_DECISION_FIELDS = frozenset({
    "task_id", "task_category", "task_summary", "proposed_route", "final_route",
    "risk_level", "decision_status", "autonomous_allowed", "acceleration_allowed",
    "product_source_mutation_allowed", "machinery_mutation_allowed",
    "human_approval_required", "blocked", "required_evidence", "required_tests",
    "allowed_paths", "forbidden_paths", "reason", "timestamp", "decision_actor",
    "schema_version",
})
