"""dom_maturity_gap_generator.py — TC-VPR-002 (serialized-petting-crab)

Generates DOM maturity boundary gaps as durable supplemental entries in gap-ledger.json.
These are the missing Stage 1 pipeline component for dual-lane DOM gap scheduling.

Root cause addressed: No tool existed to generate DOM gaps and inject them into the
gap pipeline. Without supplemental=True DOM entries, the compiler's lane_balance_penalty
has nothing to boost, making the dual-lane architecture inert.

Usage:
    python tools/supervisor/dom_maturity_gap_generator.py [--dry-run] [--format FODS]
"""
from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parents[2]

DEFAULT_LEDGER_PATH = REPO_ROOT / "registry" / "product-deepening-ledger.yaml"
DEFAULT_GAP_LEDGER_PATH = REPO_ROOT / "reports" / "capability-layer" / "gap-ledger.json"

# DOM maturity boundary → gap_type key
DOM_BOUNDARY_TYPES: dict[str, str] = {
    "D2": "dom_maturity_d2",
    "D3": "dom_maturity_d3",
    "D4": "dom_maturity_d4",
    "D5": "dom_maturity_d5",
}

DOM_BOUNDARY_CAPABILITY_NAMES: dict[str, str] = {
    "D2": "dom_typed_children for {fmt}",
    "D3": "dom_traversal for {fmt}",
    "D4": "dom_mutation for {fmt}",
    "D5": "dom_roundtrip for {fmt}",
}

MATURITY_ORDER: dict[str, int] = {
    "D0": 0, "D1": 1, "D2": 2, "D3": 3, "D4": 4, "D5": 5,
}

BOUNDARY_PRIORITY: dict[str, str] = {
    "D2": "P1", "D3": "P2", "D4": "P2", "D5": "P3",
}

APPLICABLE_STATUSES = {"FULL", "PARTIAL"}


@dataclass
class GenerationResult:
    added: int = 0
    updated: int = 0
    closed: int = 0
    unchanged: int = 0
    errors: list[str] = field(default_factory=list)
    dry_run: bool = False
    details: list[dict] = field(default_factory=list)


def _next_boundary(current: str, ceiling: str) -> Optional[str]:
    """Return the immediate next maturity level above current, if below ceiling."""
    levels = ["D0", "D1", "D2", "D3", "D4", "D5"]
    try:
        ci = levels.index(current)
        cei = levels.index(ceiling)
    except ValueError:
        return None
    next_i = ci + 1
    return levels[next_i] if next_i <= cei else None


def _make_gap_id(format_name: str, boundary: str) -> str:
    return f"GAP-{format_name.upper()}-DOM-MATURITY-{boundary.upper()}-001"


def _make_gap_record(
    format_name: str,
    boundary: str,
    current: str,
    ceiling: str,
    product_type: str = "foss",
) -> dict:
    gap_id = _make_gap_id(format_name, boundary)
    fmt_lower = format_name.lower()
    cap_name = DOM_BOUNDARY_CAPABILITY_NAMES[boundary].format(fmt=fmt_lower)
    return {
        "gap_id": gap_id,
        "format": format_name.upper(),
        "product_type": product_type,
        "capability_name": cap_name,
        "current_state": "not_implemented",
        "gap_type": DOM_BOUNDARY_TYPES[boundary],
        "status": "open",
        "deepening_lane": "dom",
        "supplemental": True,
        "dom_maturity_boundary": boundary,
        "dom_maturity_current": current,
        "dom_maturity_ceiling": ceiling,
        "blocks_poc": False,
        "blocks_readiness": True,
        "commercial_impact": "MEDIUM",
        "foss_impact": "HIGH",
        "priority": BOUNDARY_PRIORITY[boundary],
        "owning_lane": 1,
        "suggested_taskcard": "",
        "suggested_verification": f"python -m pytest tests/python/{fmt_lower}/ -v",
        "blockers": [],
        "spec_facts": [],
        "notes": (
            f"Auto-generated by dom_maturity_gap_generator (TC-VPR-002). "
            f"Advance {format_name.upper()} from {current} to {boundary}."
        ),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": "dom_maturity_gap_generator",
    }


def _load_ledger(ledger_path: Path) -> list[dict]:
    """Load product-deepening-ledger.yaml, skipping duplicate format entries."""
    try:
        import yaml
        data = yaml.safe_load(ledger_path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise RuntimeError(f"Cannot load ledger {ledger_path}: {exc}") from exc

    if not isinstance(data, list):
        raise RuntimeError(f"Ledger must be a list, got {type(data)}")

    # Deduplicate: use first occurrence of each format (case-insensitive)
    seen: set[str] = set()
    result: list[dict] = []
    for entry in data:
        fmt = str(entry.get("format", "")).lower()
        if fmt and fmt not in seen:
            seen.add(fmt)
            result.append(entry)
    return result


def _load_gap_ledger(gap_ledger_path: Path) -> dict:
    """Load gap-ledger.json."""
    try:
        return json.loads(gap_ledger_path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise RuntimeError(f"Cannot load gap-ledger {gap_ledger_path}: {exc}") from exc


def generate_dom_gaps(
    ledger_path: Path = DEFAULT_LEDGER_PATH,
    gap_ledger_path: Path = DEFAULT_GAP_LEDGER_PATH,
    dry_run: bool = False,
    format_filter: Optional[str] = None,
) -> GenerationResult:
    """Generate or refresh DOM maturity gaps in gap-ledger.json.

    For each format with dom_applicability in (FULL, PARTIAL):
      - Reads current lane_b_maturity and lane_b_ceiling from ledger
      - If current < ceiling: writes/refreshes gap for the IMMEDIATE NEXT boundary
      - If boundary already passed (maturity >= boundary): marks gap closed
      - Uses supplemental=True so capability_map_generator.py preserves it on regeneration

    Is idempotent: running twice produces identical results.
    """
    result = GenerationResult(dry_run=dry_run)

    try:
        ledger = _load_ledger(ledger_path)
        gap_ledger = _load_gap_ledger(gap_ledger_path)
    except RuntimeError as exc:
        result.errors.append(str(exc))
        return result

    gaps: list[dict] = gap_ledger.get("gaps", [])

    # Build index of existing supplemental DOM gaps by gap_id
    existing_dom: dict[str, int] = {}  # gap_id → index in gaps list
    for idx, gap in enumerate(gaps):
        if gap.get("supplemental") and gap.get("deepening_lane") == "dom":
            existing_dom[gap["gap_id"]] = idx

    # Track which non-supplemental gap IDs exist (must not mutate these)
    non_supplemental_ids: set[str] = {
        g["gap_id"] for g in gaps
        if not (g.get("supplemental") and g.get("deepening_lane") == "dom")
    }

    now_iso = datetime.now(timezone.utc).isoformat()

    for entry in ledger:
        fmt = str(entry.get("format", "")).upper()
        applicability = str(entry.get("dom_applicability", "")).upper()

        if applicability not in APPLICABLE_STATUSES:
            continue

        if format_filter and fmt.upper() != format_filter.upper():
            continue

        current = str(entry.get("lane_b_maturity", "D0")).upper()
        ceiling = str(entry.get("lane_b_ceiling", "D0")).upper()

        if current not in MATURITY_ORDER or ceiling not in MATURITY_ORDER:
            result.errors.append(f"{fmt}: unrecognized maturity/ceiling value ({current}/{ceiling})")
            continue

        next_boundary = _next_boundary(current, ceiling)

        if next_boundary is None:
            # Format is at its ceiling — close any lingering open DOM gaps for this format
            for gap_id, idx in list(existing_dom.items()):
                if not gap_id.startswith(f"GAP-{fmt}-DOM-MATURITY-"):
                    continue
                gap = gaps[idx]
                if gap.get("status") == "open":
                    if not dry_run:
                        gaps[idx]["status"] = "closed"
                        gaps[idx]["closed_at"] = now_iso
                        gaps[idx]["closed_by_engine"] = True
                        gaps[idx]["closure_evidence"] = f"format at ceiling {ceiling}"
                    result.closed += 1
                    result.details.append({
                        "format": fmt, "action": "CLOSED",
                        "gap_id": gap_id, "reason": f"at ceiling {ceiling}",
                    })
            continue

        # Close any DOM gaps for this format whose boundary <= current (already passed)
        for gap_id, idx in list(existing_dom.items()):
            if not gap_id.startswith(f"GAP-{fmt}-DOM-MATURITY-"):
                continue
            gap = gaps[idx]
            boundary = gap.get("dom_maturity_boundary", "D5")
            if (MATURITY_ORDER.get(boundary, 99) <= MATURITY_ORDER.get(current, 0)
                    and gap.get("status") == "open"):
                if not dry_run:
                    gaps[idx]["status"] = "closed"
                    gaps[idx]["closed_at"] = now_iso
                    gaps[idx]["closed_by_engine"] = True
                    gaps[idx]["closure_evidence"] = f"maturity advanced to {current}"
                result.closed += 1
                result.details.append({
                    "format": fmt, "action": "CLOSED",
                    "gap_id": gap_id, "reason": f"maturity advanced to {current}",
                })

        # Handle the immediate next boundary gap
        target_gap_id = _make_gap_id(fmt, next_boundary)

        if target_gap_id in non_supplemental_ids:
            result.errors.append(f"{fmt}: {target_gap_id} exists as non-supplemental gap — skipping")
            continue

        if target_gap_id in existing_dom:
            idx = existing_dom[target_gap_id]
            existing_gap = gaps[idx]
            if existing_gap.get("status") == "open":
                result.unchanged += 1
                result.details.append({
                    "format": fmt, "action": "UNCHANGED",
                    "gap_id": target_gap_id, "boundary": next_boundary,
                })
            else:
                # Reopen if maturity is still below the boundary
                if MATURITY_ORDER.get(current, 0) < MATURITY_ORDER.get(next_boundary, 99):
                    if not dry_run:
                        gaps[idx]["status"] = "open"
                        gaps[idx]["dom_maturity_current"] = current
                        gaps[idx].pop("closed_at", None)
                        gaps[idx].pop("closed_by_engine", None)
                        gaps[idx].pop("closure_evidence", None)
                    result.updated += 1
                    result.details.append({
                        "format": fmt, "action": "REOPENED",
                        "gap_id": target_gap_id, "boundary": next_boundary,
                    })
                else:
                    result.unchanged += 1
        else:
            # Create new supplemental DOM gap
            new_gap = _make_gap_record(fmt, next_boundary, current, ceiling)
            if not dry_run:
                gaps.append(new_gap)
            result.added += 1
            result.details.append({
                "format": fmt, "action": "ADDED",
                "gap_id": target_gap_id, "boundary": next_boundary,
                "current": current, "ceiling": ceiling,
            })

    if not dry_run:
        gap_ledger["gaps"] = gaps
        gap_ledger_path.write_text(
            json.dumps(gap_ledger, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

    return result


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Generate DOM maturity gaps (TC-VPR-002)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Preview changes without writing to gap-ledger.json")
    parser.add_argument("--format", dest="format_filter", default=None,
                        help="Generate gaps for a single format only")
    parser.add_argument("--ledger-path", default=str(DEFAULT_LEDGER_PATH),
                        help="Path to product-deepening-ledger.yaml")
    parser.add_argument("--gap-ledger-path", default=str(DEFAULT_GAP_LEDGER_PATH),
                        help="Path to gap-ledger.json")
    args = parser.parse_args()

    result = generate_dom_gaps(
        ledger_path=Path(args.ledger_path),
        gap_ledger_path=Path(args.gap_ledger_path),
        dry_run=args.dry_run,
        format_filter=args.format_filter,
    )

    mode = "(dry-run)" if result.dry_run else ""
    print(f"DOM Gap Generation {mode}:")
    for d in result.details:
        action = d["action"]
        fmt = d["format"]
        gap_id = d.get("gap_id", "")
        boundary = d.get("boundary", "")
        reason = d.get("reason", "")
        if action == "ADDED":
            print(f"  {fmt}: {d.get('current')} -> {boundary} (gap_id={gap_id}, status=NEW)")
        elif action == "CLOSED":
            print(f"  {fmt}: CLOSED {gap_id} ({reason})")
        elif action == "UNCHANGED":
            print(f"  {fmt}: UNCHANGED {gap_id}")
        elif action == "REOPENED":
            print(f"  {fmt}: REOPENED {gap_id}")

    print(f"Total: {result.added} new, {result.updated} updated, "
          f"{result.closed} closed, {result.unchanged} unchanged")

    if result.errors:
        print("Errors:", file=sys.stderr)
        for e in result.errors:
            print(f"  {e}", file=sys.stderr)

    return 1 if result.errors else 0


if __name__ == "__main__":
    sys.exit(main())
