"""Format-test promotion lifecycle for drivers/ subsystem.

Implements the SCAFFOLD -> MAINTAINED state machine for test scaffolds
generated by test_drivers.py and product_feature_factory.py.

Every rendered scaffold creates a GeneratedTestPromotionTask that tracks
incomplete markers, required fixtures, and assertions until the test
is promoted to MAINTAINED status.

Language: Python only (PYTHON_ONLY_BY_DESIGN — matches test_drivers.py).
"""
from __future__ import annotations

import re
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

try:
    import yaml  # type: ignore[import]
    _HAS_YAML = True
except ImportError:
    _HAS_YAML = False


# ---------------------------------------------------------------------------
# Promotion task states
# ---------------------------------------------------------------------------

PROMOTION_STATES = (
    "SCAFFOLD_GENERATED",
    "FORMAT_ADAPTATION_REQUIRED",
    "FIXTURES_READY",
    "ASSERTIONS_READY",
    "EXECUTABLE",
    "VERIFIED",
    "MAINTAINED",
)

# ---------------------------------------------------------------------------
# Incomplete marker detection
# ---------------------------------------------------------------------------

_INCOMPLETE_MARKER_PATTERNS = [
    r"#\s*FIXTURE_REQUIRED[^\n]*",
    r"#\s*EXPECTED_VALUE_REQUIRED[^\n]*",
    r"#\s*ORACLE_REQUIRED[^\n]*",
    r"#\s*TEST_SCAFFOLD_INCOMPLETE[^\n]*",
    r"#\s*FORMAT_ADAPTATION_REQUIRED[^\n]*",
    r"#\s*SCAFFOLD_STATUS:\s*FORMAT_ADAPTATION_REQUIRED[^\n]*",
]


def scan_incomplete_markers(code: str) -> list[str]:
    """Return a list of incomplete marker strings found in the generated code.

    A non-empty return means the test is a scaffold and must NOT be promoted
    to MAINTAINED status until all markers are resolved.
    """
    found = []
    for pattern in _INCOMPLETE_MARKER_PATTERNS:
        for match in re.finditer(pattern, code):
            found.append(match.group().strip())
    return found


def validate_maintained_gate(code: str) -> bool:
    """Return True only if no incomplete markers remain in the code.

    A maintained test has real fixtures, meaningful assertions, and no scaffold markers.
    """
    return len(scan_incomplete_markers(code)) == 0


# ---------------------------------------------------------------------------
# Promotion task dataclass
# ---------------------------------------------------------------------------

@dataclass
class GeneratedTestPromotionTask:
    """Tracks the promotion state of a generated test scaffold."""

    task_id: str
    product_id: str
    format_id: str
    language: str
    pattern_id: str
    template_id: str
    renderer_id: str
    generated_path: str
    target_path: str
    incomplete_markers: list[str] = field(default_factory=list)
    required_fixtures: list[str] = field(default_factory=list)
    required_expected_values: list[str] = field(default_factory=list)
    capability_refs: list[str] = field(default_factory=list)
    gap_ids: list[str] = field(default_factory=list)
    required_assertions: list[str] = field(default_factory=list)
    required_negative_cases: list[str] = field(default_factory=list)
    status: str = "SCAFFOLD_GENERATED"
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> dict:
        """Serialize to a plain dict for YAML output."""
        return {
            "task_id": self.task_id,
            "product_id": self.product_id,
            "format_id": self.format_id,
            "language": self.language,
            "pattern_id": self.pattern_id,
            "template_id": self.template_id,
            "renderer_id": self.renderer_id,
            "generated_path": self.generated_path,
            "target_path": self.target_path,
            "incomplete_markers": self.incomplete_markers,
            "required_fixtures": self.required_fixtures,
            "required_expected_values": self.required_expected_values,
            "capability_refs": self.capability_refs,
            "gap_ids": self.gap_ids,
            "required_assertions": self.required_assertions,
            "required_negative_cases": self.required_negative_cases,
            "status": self.status,
            "created_at": self.created_at,
        }


# ---------------------------------------------------------------------------
# Task creation
# ---------------------------------------------------------------------------

def create_promotion_task(
    rendered_code: str,
    format_id: str,
    pattern_id: str,
    template_id: str,
    renderer_id: str,
    generated_path: str,
    target_path: str,
    product_id: str = "",
    capability_refs: Optional[list[str]] = None,
    gap_ids: Optional[list[str]] = None,
) -> GeneratedTestPromotionTask:
    """Create a promotion task from a rendered scaffold.

    Scans incomplete markers, derives required fixtures and assertions,
    and sets the initial status to FORMAT_ADAPTATION_REQUIRED if any
    markers are found, otherwise SCAFFOLD_GENERATED.
    """
    markers = scan_incomplete_markers(rendered_code)
    required_fixtures = [m for m in markers if "FIXTURE_REQUIRED" in m]
    required_expected_values = [m for m in markers if "EXPECTED_VALUE_REQUIRED" in m]
    required_assertions = [m for m in markers if "ORACLE_REQUIRED" in m]

    initial_status = "FORMAT_ADAPTATION_REQUIRED" if markers else "SCAFFOLD_GENERATED"

    return GeneratedTestPromotionTask(
        task_id=f"PROMO-{format_id.upper()}-{pattern_id}-{uuid.uuid4().hex[:8].upper()}",
        product_id=product_id or format_id,
        format_id=format_id,
        language="python",
        pattern_id=pattern_id,
        template_id=template_id,
        renderer_id=renderer_id,
        generated_path=generated_path,
        target_path=target_path,
        incomplete_markers=markers,
        required_fixtures=required_fixtures,
        required_expected_values=required_expected_values,
        capability_refs=capability_refs or [],
        gap_ids=gap_ids or [],
        required_assertions=required_assertions,
        required_negative_cases=[],
        status=initial_status,
    )


def get_promotion_status(task: GeneratedTestPromotionTask) -> str:
    """Return the current promotion status of a task."""
    return task.status


# ---------------------------------------------------------------------------
# Task persistence
# ---------------------------------------------------------------------------

def write_promotion_task(
    task: GeneratedTestPromotionTask,
    output_dir: Path,
) -> Path:
    """Write a promotion task to a YAML file in output_dir.

    Returns the path of the written file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{task.task_id}.yaml"
    task_dict = task.to_dict()

    if _HAS_YAML:
        content = "---\n" + yaml.dump(task_dict, default_flow_style=False, sort_keys=False)
    else:
        # Minimal YAML serialization without PyYAML
        lines = ["---"]
        for key, value in task_dict.items():
            if isinstance(value, list):
                lines.append(f"{key}:")
                for item in value:
                    lines.append(f"  - {item!r}")
            else:
                lines.append(f"{key}: {value!r}")
        content = "\n".join(lines) + "\n"

    out_path.write_text(content, encoding="utf-8")
    return out_path
