"""
generate_next_worker_prompt.py -- Next Worker Prompt Generator
Generates a comprehensive mega-train execution prompt from supervisor review results,
POC target matrix, gap extraction fixtures, and a structural template.

Hybrid approach:
  - Fixed sections (prohibitions, validation, verdicts) come from mega-train-template.md
  - Variable sections (trains, groups, rework items) are synthesized programmatically

Exit codes:
  0 -- prompt generated
  1 -- missing inputs
  9 -- unexpected error
"""

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

import yaml

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent.parent

TEMPLATE_PATH = REPO_ROOT / ".supervisor" / "prompts" / "mega-train-template.md"

# Stop Reason Adjudicator advisory — included in every generated prompt.
# Prevents future agents from stopping for invalid reasons.
STOP_REASON_ADVISORY = """
## ADVISORY: Stop Reason Adjudicator — Read Before Treating Any Task As Blocked

**ADVISORY ONLY** — generated by generate_next_worker_prompt.py

Before treating any task as blocked, approval-blocked, or human-required:

1. Run: `python tools/supervisor/stop_reason_adjudicator.py "<signal>"`
2. If decision is NOT `TRUE_EXTERNAL_GATE` or `UNSAFE_WORKSPACE` → repair/continue
3. If decision is `RUFLO_FALLBACK_LOCAL_CONTINUE` → use local coordinator
4. If decision is `CHECKPOINT_ROLLOVER_CONTINUE` → increment iteration, continue
5. If decision is `RELEASE_APPROVAL_PENDING_NOT_IMPLEMENTATION_BLOCKER` → Gate 11 packet prep only

**Permanent false stops (NEVER stop for these):**
- Supervisor ACCEPTED → continue
- Evidence package built → continue
- max_iterations reached → checkpoint rollover
- Gate 11 pending (implementation incomplete) → continue implementation
- MODE 5 approval pending → local coordinator fallback
- Ruflo/claude-flow unavailable → local coordinator fallback
- evidence_quality_zero (repairable) → repair declaration
- Generic "approval-blocked"/"blocked" labels → reclassify first

**TRUE_EXTERNAL_GATE (only these warrant a stop):**
- git commit/push/merge (requires human authorization)
- NuGet/PyPI publication (requires human authorization)
- Credentials/secrets (no safe fallback)
- Gate 11 approval EXECUTION (not preparation)

**Policy:** `docs/governance/autonomous-stop-reason-policy.md`
**Adjudicator:** `tools/supervisor/stop_reason_adjudicator.py`
"""
SELECTED_PRODUCT_GAPS_PATH = ".local/supervisor/selected-product-gaps.json"
SKILL_REGISTRY_PATH = ".supervisor/skill-registry.yaml"
PRODUCT_CODE_LEDGER_PATH = "reports/r90/product-code-change-ledger.json"

# Python Netpbm is split into three packages (pbm/pgm/ppm) — no src/python/netpbm/ exists.
# This override maps the poc-targets format name to actual Python src/test directories.
PYTHON_PACKAGE_DIR_OVERRIDE: dict[str, list[str]] = {
    "netpbm": ["pbm", "pgm", "ppm"],
}

READ_BEFORE_EXECUTION = [
    "AGENTS.md",
    "GOVERNANCE.md",
    "plans/master-plan.md",
    "registry/format-registry.yaml",
    "reports/supervisor/session-resume.md",
    "reports/supervisor/latest-review.md",
    ".supervisor/policies.yaml",
    SKILL_REGISTRY_PATH,
    SELECTED_PRODUCT_GAPS_PATH,
    "product-capability-matrix/poc-targets.yaml",
    "CLAUDE.md",
]

TRAIN_LETTERS = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")

# Gap IDs that are architecture-blocked: no FF target writer library exists for .NET.
# Agents must NOT invoke /add-dogfood-export for these gaps.
# Route to architecture-decision lane instead.
# See: reports/dotnet-dogfood-architecture-gap/architecture-gap-decision-record.md
BLOCKED_ARCHITECTURE_GAPS: frozenset = frozenset({
    "commercial-net-fods-dogfood-status-fods-to-csv-dotnet",
    "commercial-net-fods-dogfood-status-fods-to-html-dotnet",
    "commercial-net-fodt-dogfood-status-fodt-to-markdown-dotnet",
    "commercial-net-fodt-dogfood-status-fodt-to-txt-dotnet",
})

# Group definitions -- trains are organized into these groups
GROUP_DEFS = [
    {"id": "G1", "name": "Governance + Preflight", "priority": 1},
    {"id": "G2", "name": "Rework / Repair", "priority": 2},
    {"id": "G3", "name": "Commercial .NET Product", "priority": 3},
    {"id": "G4", "name": "FOSS / Reduced Product", "priority": 4},
    {"id": "G5", "name": "Dogfood Exports", "priority": 5},
    {"id": "G6", "name": "Package / Install Proof", "priority": 6},
    {"id": "G7", "name": "State / Memory / POC Matrix", "priority": 7},
    {"id": "G8", "name": "Evidence + Supervisor Loop", "priority": 8},
]


def load_poc_targets(repo_root: Path) -> dict:
    """Load POC target matrix."""
    path = repo_root / "product-capability-matrix" / "poc-targets.yaml"
    if not path.exists():
        return {}
    try:
        return yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def load_gap_ledger_ids(repo_root: Path) -> set[str]:
    """Load all valid gap IDs from gap-ledger.json for phantom-ID validation."""
    path = repo_root / "reports" / "capability-layer" / "gap-ledger.json"
    if not path.exists():
        return set()
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        gaps = data.get("gaps", []) if isinstance(data, dict) else data
        return {g.get("gap_id", "") for g in gaps if g.get("gap_id")}
    except Exception:
        return set()


def load_gap_extraction(repo_root: Path) -> dict:
    """Load the most recent gap extraction fixture."""
    fixtures_dir = repo_root / ".supervisor" / "fixtures"
    if not fixtures_dir.exists():
        return {}
    gap_files = list(fixtures_dir.glob("*-poc-gap-extraction.yaml"))
    if not gap_files:
        return {}
    latest = max(gap_files, key=lambda p: p.stat().st_mtime)
    try:
        return yaml.safe_load(latest.read_text(encoding="utf-8"))
    except Exception:
        return {}


def load_template(template_path: Path = None) -> str:
    """Load the mega-train template."""
    path = template_path or TEMPLATE_PATH
    if path.exists():
        return path.read_text(encoding="utf-8")
    return ""


def suggest_next_sprint_id(prior_sprint_id: str) -> str:
    """Suggest next R-number from prior sprint ID."""
    m = re.search(r"R(\d+)", prior_sprint_id, re.IGNORECASE)
    if m:
        return f"R{int(m.group(1)) + 1}"
    return "RNEXT"


def detect_venv_path(repo_root: Path) -> str:
    """Detect the Python venv path."""
    venv = repo_root / ".local" / "venv"
    if (venv / "Scripts" / "python.exe").exists():
        return ".local/venv/Scripts/python"
    if (venv / "bin" / "python").exists():
        return ".local/venv/bin/python"
    return "python"


def synthesize_trains(review: dict, poc_targets: dict, gaps: dict) -> list[dict]:
    """Synthesize trains from review grades, POC targets, and gap fixtures.

    Each train is a dict with:
      letter, group, title, description, acceptance_criteria, files_touched, verification_command
    """
    trains = []
    letter_idx = 0

    def next_letter():
        nonlocal letter_idx
        if letter_idx < len(TRAIN_LETTERS):
            l = TRAIN_LETTERS[letter_idx]
            letter_idx += 1
            return l
        return f"Z{letter_idx - 25}"

    # --- G1: Governance preflight (always first) ---
    trains.append({
        "letter": next_letter(),
        "group": "G1",
        "title": "Governance Preflight",
        "description": "Read all governance files. Verify no policy violations from prior sprint. "
                       "Confirm MCP status, supervisor mode, and gate states. Load "
                       f"`{SELECTED_PRODUCT_GAPS_PATH}` and `{SKILL_REGISTRY_PATH}` before "
                       "selecting product work.",
        "acceptance_criteria": [
            "All preflight files read",
            "No policy violations detected",
            "Gate states documented",
        ],
        "files_touched": ["reports/<run_id>/00-preflight.md"],
        "verification_command": "",
    })

    # --- G2: Rework trains (from review grades) ---
    rework_items = [
        g for g in review.get("item_grades", [])
        if g.get("supervisor_grade") in ("REWORK_REQUIRED", "OVERCLAIMED", "REJECTED")
    ]
    for item in rework_items:
        trains.append({
            "letter": next_letter(),
            "group": "G2",
            "title": f"Rework: {item.get('item_title', item.get('item_id', 'unknown'))}",
            "description": item.get("required_rework", "Fix issues identified in supervisor review."),
            "acceptance_criteria": [
                f"Evidence for {item['item_id']} passes supervisor inspection",
                "Tests pass for affected code",
            ],
            "files_touched": item.get("evidence_paths", []),
            "verification_command": "",
        })

    # --- G3: Commercial .NET product trains ---
    commercial = poc_targets.get("commercial_net_products", [])
    for product in commercial:
        fmt = product.get("format", "unknown")
        next_action = product.get("next_action", "")
        gate_11 = product.get("gate_11_status", "")
        dotnet_status = product.get("dotnet_status", {})

        # Find gaps for this product
        gap_report = gaps.get("poc_gap_report", {})
        product_gaps = [
            g for g in gap_report.get("capability_gaps", [])
            if fmt.lower() in g.get("product", "").lower()
            and g.get("suggested_sprint", "HOLD") != "HOLD"
        ]

        if product_gaps:
            for gap in product_gaps[:2]:  # Max 2 trains per product
                trains.append({
                    "letter": next_letter(),
                    "group": "G3",
                    "title": f"{fmt} .NET: {gap.get('capability', gap['id'])}",
                    "description": f"{gap.get('note', '')}. Status: {gap.get('current_status', 'unknown')}.",
                    "acceptance_criteria": [
                        f"New tests pass for {gap['id']}",
                        f"{fmt} .NET capability implemented or documented",
                    ],
                    "files_touched": [
                        f"src/net/{fmt.lower()}/",
                        f"tests/net/{fmt.lower()}/",
                        PRODUCT_CODE_LEDGER_PATH,
                    ],
                    "verification_command": f"dotnet test tests/net/{fmt.lower()}/ --verbosity quiet",
                })
        elif gate_11 not in ("passed", "not_applicable"):
            # Generic advancement train — sanitize next_action: never embed external-gate wording
            safe_next_action = (
                "Prepare commit-ready packet only. Do not commit or push. "
                "External gate: classify specific blocker per AGENTS.md §AG."
                if _next_action_requires_external_gate(next_action)
                else next_action
            )
            trains.append({
                "letter": next_letter(),
                "group": "G3",
                "title": f"{fmt} .NET Product Deepening",
                "description": f"Continue {fmt} commercial .NET product advancement. {safe_next_action}",
                "acceptance_criteria": [
                    f"{fmt} .NET test count increased or new API proven",
                    "dotnet_status in poc-targets.yaml updated",
                ],
                "files_touched": [
                    f"src/net/{fmt.lower()}/",
                    f"tests/net/{fmt.lower()}/",
                    PRODUCT_CODE_LEDGER_PATH,
                ],
                "verification_command": f"dotnet test tests/net/{fmt.lower()}/ --verbosity quiet",
            })

    # --- G4: FOSS/Reduced product trains ---
    foss = poc_targets.get("foss_reduced_products", [])
    for product in foss:
        fmt = product.get("format", "unknown")
        next_action = product.get("next_action", "")
        python_status = product.get("python_status", {})

        # Resolve actual Python package directories (some formats split across multiple packages)
        fmt_key = fmt.lower()
        python_dirs = PYTHON_PACKAGE_DIR_OVERRIDE.get(fmt_key, [fmt_key])
        src_files = [f"src/python/{d}/" for d in python_dirs]
        test_files = [f"tests/python/{d}/" for d in python_dirs]
        # Use first dir for verification command (pytest can accept multiple paths)
        verify_dirs = " ".join(f"tests/python/{d}/" for d in python_dirs)
        verify_cmd = f"python -m pytest {verify_dirs} -x -q"

        # Find NOT_IMPLEMENTED capabilities
        not_impl = [k for k, v in python_status.items()
                    if isinstance(v, str) and v in ("NOT_IMPLEMENTED", "PARTIAL")]

        if not_impl:
            cap = not_impl[0]
            trains.append({
                "letter": next_letter(),
                "group": "G4",
                "title": f"{fmt} Python: {cap.replace('_', ' ').title()}",
                "description": f"Implement {cap} for {fmt}. {next_action}",
                "acceptance_criteria": [
                    f"{cap} tests pass",
                    f"python_status.{cap} updated to PASS in poc-targets.yaml",
                ],
                "files_touched": src_files + test_files + [PRODUCT_CODE_LEDGER_PATH],
                "verification_command": verify_cmd,
            })
        else:
            trains.append({
                "letter": next_letter(),
                "group": "G4",
                "title": f"{fmt} Python Improvement",
                "description": f"Continue {fmt} FOSS product. {next_action}",
                "acceptance_criteria": [
                    f"{fmt} Python test count maintained or increased",
                ],
                "files_touched": src_files + test_files + [PRODUCT_CODE_LEDGER_PATH],
                "verification_command": verify_cmd,
            })

    # --- G5: Dogfood export trains ---
    dogfood_gaps = gaps.get("poc_gap_report", {}).get("dogfood_gaps", [])
    actionable_dogfood = [
        g for g in dogfood_gaps
        if g.get("suggested_sprint", "HOLD") != "HOLD"
        and g.get("current_status") != "IMPLEMENTED"
        and g.get("id", g.get("gap_id", "")) not in BLOCKED_ARCHITECTURE_GAPS
    ]
    for gap in actionable_dogfood[:2]:  # Max 2 dogfood trains
        trains.append({
            "letter": next_letter(),
            "group": "G5",
            "title": f"Dogfood: {gap.get('format', '?')} -> {gap.get('export_target', '?')}",
            "description": f"{gap.get('dogfood_blocker', '')}. Prerequisite: {gap.get('prerequisite', 'none')}.",
            "acceptance_criteria": [
                "Export test passes using FF library",
                "Dogfood status updated in poc-targets.yaml",
            ],
            "files_touched": [],
            "verification_command": "",
        })

    if not actionable_dogfood:
        # At least one dogfood maintenance train
        trains.append({
            "letter": next_letter(),
            "group": "G5",
            "title": "Dogfood Export Verification",
            "description": "Verify existing dogfood exports still pass. "
                           "Update dogfood-export-map.md if any new exports were added.",
            "acceptance_criteria": [
                "All existing dogfood export tests pass",
                "No regression in export chain",
            ],
            "files_touched": ["docs/export/dogfood-export-map.md"],
            "verification_command": "",
        })

    # --- G6: Package/install proof ---
    trains.append({
        "letter": next_letter(),
        "group": "G6",
        "title": "Package Build + Install Proof",
        "description": "Rebuild wheels/sdists for any changed packages. "
                       "Run installed-workflow smoke test from extracted wheel. Treat missing "
                       "artifacts as failures, not skips.",
        "acceptance_criteria": [
            "All changed packages rebuilt",
            "Installed import test passes",
            "Package artifacts present in evidence directory",
        ],
        "files_touched": ["packaging/"],
        "verification_command": "python -m pytest tests/evidence/ -x -q",
    })

    # --- G7: State/memory/POC matrix sync ---
    trains.append({
        "letter": next_letter(),
        "group": "G7",
        "title": "State + Memory + POC Matrix Sync",
        "description": "Update state/current-state.md, .supervisor/project-memory.md, "
                       "and product-capability-matrix/poc-targets.yaml with sprint results.",
        "acceptance_criteria": [
            "poc-targets.yaml reflects actual status (no overclaiming)",
            "state/current-state.md updated",
            "project-memory.md entry appended",
        ],
        "files_touched": [
            "state/current-state.md",
            ".supervisor/project-memory.md",
            "product-capability-matrix/poc-targets.yaml",
        ],
        "verification_command": "",
    })

    # --- G8: Evidence declaration + supervisor loop ---
    trains.append({
        "letter": next_letter(),
        "group": "G8",
        "title": "Evidence Declaration + Supervisor Autonomous-Cycle",
        "description": "Write evidence-declaration.yaml listing ALL work items. "
                       "Run autonomous-cycle. Verify session-resume.md is regenerated. Validate "
                       f"`{PRODUCT_CODE_LEDGER_PATH}` for any governed product source edit.",
        "acceptance_criteria": [
            "evidence-declaration.yaml written with all work items",
            "autonomous-cycle exits 0 or 3",
            "session-resume.md regenerated with current data",
            "approval-gates.md shows correct AUTONOMOUS_CONTINUE",
        ],
        "files_touched": [
            ".local/evidences/<run_id>/evidence-declaration.yaml",
            "reports/supervisor/session-resume.md",
        ],
        "verification_command": (
            "python tools/supervisor/supervisor_loop.py autonomous-cycle "
            "--declaration .local/evidences/<run_id>/evidence-declaration.yaml"
        ),
    })

    return trains


def format_train_manifest_table(trains: list[dict]) -> str:
    """Build a markdown table summarizing all trains."""
    lines = ["| Train | Group | Title |", "|-------|-------|-------|"]
    for t in trains:
        lines.append(f"| {t['letter']} | {t['group']} | {t['title']} |")
    return "\n".join(lines)


def format_train_details(trains: list[dict]) -> str:
    """Build detailed per-train sections."""
    sections = []
    current_group = None

    for t in trains:
        if t["group"] != current_group:
            current_group = t["group"]
            group_def = next((g for g in GROUP_DEFS if g["id"] == current_group), None)
            group_name = group_def["name"] if group_def else current_group
            sections.append(f"## Group {current_group}: {group_name}\n")

        sections.append(f"### Train {t['letter']}: {t['title']}\n")
        sections.append(f"{t['description']}\n")

        if t["acceptance_criteria"]:
            sections.append("**Acceptance Criteria:**")
            for criterion in t["acceptance_criteria"]:
                sections.append(f"- {criterion}")
            sections.append("")

        if t["files_touched"]:
            sections.append("**Files:**")
            for f in t["files_touched"]:
                sections.append(f"- `{f}`")
            sections.append("")

        if t["verification_command"]:
            sections.append("**Verification:**")
            sections.append(f"```bash\n{t['verification_command']}\n```")
            sections.append("")

    return "\n".join(sections)


def format_preflight_list() -> str:
    """Format the preflight file list."""
    lines = ["Read these files before writing any code:\n"]
    for i, f in enumerate(READ_BEFORE_EXECUTION, 1):
        lines.append(f"{i}. `{f}`")
    return "\n".join(lines)


def build_sprint_goal(review: dict, rework_items: list, trains: list,
                      stream: str = "mainstream") -> str:
    """Synthesize the sprint goal from review context."""
    rework_count = len(rework_items)
    product_trains = [t for t in trains if t["group"] in ("G3", "G4", "G5")]

    parts = []
    if rework_count > 0:
        parts.append(f"Repair {rework_count} item(s) flagged by supervisor review")
    if product_trains:
        product_names = [t["title"] for t in product_trains[:4]]
        parts.append(f"Advance product POC: {'; '.join(product_names)}")
    # R110: Stream-specific advancement goal for non-mainstream
    if stream not in ("mainstream", "product") and not product_trains:
        stream_label = stream.title() if stream else "Stream"
        forward_items = STREAM_FORWARD_WORK.get(stream, [])
        if forward_items:
            titles = [fw["title"] for fw in forward_items[:3]]
            parts.append(f"Advance {stream_label} tooling: {'; '.join(titles)}")
    parts.append("Build evidence declaration and run supervisor autonomous-cycle")

    return "**Goal:** " + ". ".join(parts) + "."


STREAM_GROUPS = {
    "product": ("G1", "G2", "G3", "G4", "G5", "G6", "G7", "G8"),
    "acceleration": ("G1", "G2", "G7", "G8"),
    "skills": ("G1", "G2", "G7", "G8"),
    "supervisor": ("G1", "G2", "G7", "G8"),
}

# TC-P2-003 / REQ-TRK-005, REQ-TRK-006: Two-track work group partitioning.
# Track P (product): format deepening, spec parity, product code, dogfood exports.
# Track M (machinery): governance, rework/repair, package/install, state/memory, supervisor loop.
TRACK_GROUPS = {
    "product": ("G3", "G4", "G5"),
    "machinery": ("G1", "G2", "G6", "G7", "G8"),
}


def _build_spec_parity_section(repo_root: Path) -> str:
    """Build spec-parity requirements section from skill registry.

    Reads .supervisor/skill-registry.yaml to find skills with
    spec_qname_required: true and injects a requirements section into the
    generated prompt. Advisory-only — gracefully returns empty string if
    registry is unavailable.
    """
    try:
        registry_path = repo_root / SKILL_REGISTRY_PATH
        if not registry_path.exists():
            return ""
        registry = yaml.safe_load(registry_path.read_text(encoding="utf-8"))
        skills = registry.get("skills", [])
        if not skills:
            return ""
        qname_skills = [s for s in skills if s.get("spec_qname_required")]
        if not qname_skills:
            return ""
        lines = [
            "",
            "## Spec-Parity Requirements (from skill registry)",
            "",
            "The following skills require `spec_qname` mapping when invoked for product model work.",
            "Any product model task using these skills MUST declare which spec QNames are addressed",
            "and MUST NOT invent arbitrary flat class names without spec authority.",
            "",
        ]
        for s in qname_skills:
            sid = s.get("skill_id", "unknown")
            lines.append(f"- **{sid}**: spec_qname_required=true")
        lines.extend([
            "",
            "**Enforcement:** If a product model change is made without citing spec_fact_refs,",
            "governance validator V8 (spec_fact_references) will FAIL the item.",
            "Use SAL output at `.local/sal-output/sal-facts-latest.json` for valid FACT-* refs.",
            "",
        ])
        return "\n".join(lines)
    except Exception:
        return ""


def generate_prompt(review: dict, next_work: dict | None = None,
                    repo_root: Path = None, stream: str = None,
                    work_groups: list | None = None) -> str:
    """Generate the mega-train execution prompt from review results and project data.

    Args:
        stream: Optional stream filter (R99: D99-PROMPT-01). One of:
            - None/"product" — full mega-train (default, all groups)
            - "acceleration" — rework + evidence only (no product trains)
            - "skills" — rework + evidence only (for governed skill work)
            - "supervisor" — rework + evidence only (for supervisor infrastructure)
        work_groups: TC-P2-003 — when set, restricts generated trains to specified groups.
            E.g. ["G3","G4","G5"] for Track P, ["G1","G2","G6","G7","G8"] for Track M.
    """
    if repo_root is None:
        repo_root = REPO_ROOT

    # Lane 5: Inject durable failure memory into prompt
    failure_warnings = []
    try:
        from failure_memory import FailureMemory
        fm = FailureMemory(repo_root)
        escalated = fm.find_escalated()
        for e in escalated:
            failure_warnings.append(
                f"ESCALATED FAILURE ({e['category']}): {e['root_cause']} "
                f"(seen {e['occurrence_count']}x, last: {e.get('last_seen_sprint', 'unknown')})"
            )
        unresolved = fm.find_unresolved()
        if len(unresolved) > 5:
            failure_warnings.append(
                f"WARNING: {len(unresolved)} unresolved failures in failure memory"
            )
    except Exception:
        pass

    # HEAL-RECT-002/006: Inject learning-based governance advisories
    learning_advisories = ""
    try:
        from learning_consumer import LearningConsumer
        lc = LearningConsumer(repo_root)
        lc.scan_all_learnings()
        proposals = lc.generate_proposals(threshold=3)
        if proposals:
            lc.save_proposals()
            learning_advisories = lc.format_governance_advisories(proposals)
        # Also include any previously saved proposals
        if not learning_advisories:
            learning_advisories = lc.format_governance_advisories()
    except Exception:
        pass

    # Load data sources
    poc_targets = load_poc_targets(repo_root)
    gaps = load_gap_extraction(repo_root)
    template = load_template()

    # Extract review context
    sprint_id = review.get("sprint_id", "unknown")
    verdict = review.get("overall_verdict", "unknown")
    autonomous = review.get("autonomous_continue", False)
    test_passed = review.get("test_results", {}).get("passed", 0)
    test_failed = review.get("test_results", {}).get("failed", 0)
    test_skipped = review.get("test_results", {}).get("skipped", 0)

    next_sprint = suggest_next_sprint_id(sprint_id)
    venv_path = detect_venv_path(repo_root)

    # Synthesize trains
    trains = synthesize_trains(review, poc_targets, gaps)

    # R99: Filter trains by stream (D99-PROMPT-01)
    if stream and stream in STREAM_GROUPS:
        allowed_groups = STREAM_GROUPS[stream]
        trains = [t for t in trains if t["group"] in allowed_groups]

    # TC-P2-003: Filter trains by work_groups when provided (two-track separation).
    # work_groups takes precedence over stream-based filtering for track-specific runs.
    if work_groups:
        _wg = set(work_groups)
        trains = [t for t in trains if t["group"] in _wg]

    # R110: Add stream-specific advancement trains for non-mainstream streams
    if stream and stream not in ("mainstream", "product", None):
        forward_items = STREAM_FORWARD_WORK.get(stream, [])
        if forward_items:
            # Insert advancement trains before the last two (G7, G8)
            insert_idx = max(0, len(trains) - 2)
            for i, fw in enumerate(forward_items):
                trains.insert(insert_idx + i, {
                    "letter": "",  # Re-lettered below
                    "group": "G2",
                    "title": fw["title"],
                    "description": fw["desc"],
                    "acceptance_criteria": ["Tests pass for affected tools", "Evidence declared"],
                    "files_touched": ["tools/supervisor/", "tests/supervisor/"],
                    "verification_command": "",
                })
            # Re-letter all trains after insertion
            for idx, t in enumerate(trains):
                t["letter"] = TRAIN_LETTERS[idx] if idx < len(TRAIN_LETTERS) else f"Z{idx - 25}"

    rework_items = [
        g for g in review.get("item_grades", [])
        if g.get("supervisor_grade") in ("REWORK_REQUIRED", "OVERCLAIMED", "REJECTED")
    ]

    effective_stream = stream or "mainstream"

    # Build template variables
    test_line = f"{test_passed} passed, {test_failed} failed, {test_skipped} skipped"
    sprint_goal = build_sprint_goal(review, rework_items, trains, stream=effective_stream)

    # Determine .NET test command
    has_dotnet_trains = any(t["group"] == "G3" for t in trains)
    dotnet_test_cmd = "dotnet test tests/net/ --verbosity quiet" if has_dotnet_trains else "# (no .NET work this sprint)"

    if template:
        # Use template with variable substitution
        result = template.replace("{sprint_id}", next_sprint)
        result = result.replace("{timestamp}", datetime.now().isoformat())
        result = result.replace("{prior_sprint_id}", sprint_id)
        result = result.replace("{prior_verdict}", verdict)
        result = result.replace("{prior_test_line}", test_line)
        result = result.replace("{autonomous_continue}", str(autonomous))
        result = result.replace("{sprint_goal}", sprint_goal)
        result = result.replace("{stream_identity}", effective_stream)
        result = result.replace("{preflight_file_list}", format_preflight_list())
        result = result.replace("{train_manifest_table}", format_train_manifest_table(trains))
        result = result.replace("{train_details}", format_train_details(trains))
        result = result.replace("{python_venv}", venv_path)
        result = result.replace("{dotnet_test_command}", dotnet_test_cmd)
        deterministic_prompt = result
    else:
        # Fallback: build prompt without template
        deterministic_prompt = _build_fallback_prompt(
            review, trains, sprint_goal, test_line,
            next_sprint, venv_path, dotnet_test_cmd, effective_stream,
        )

    # Lane 5: Inject failure memory warnings into prompt
    if failure_warnings:
        fw_section = "\n\n## Durable Failure Memory Warnings\n\n"
        fw_section += "The following failures have been recorded in durable failure memory.\n"
        fw_section += "Address escalated failures with priority.\n\n"
        for fw in failure_warnings:
            fw_section += f"- {fw}\n"
        fw_section += "\n"
        deterministic_prompt += fw_section

    # HEAL-RECT-002/006: Inject learning-based governance advisories
    if learning_advisories:
        deterministic_prompt += "\n\n" + learning_advisories

    # Inject spec-parity requirements from skill registry (advisory)
    spec_section = _build_spec_parity_section(repo_root)
    if spec_section:
        deterministic_prompt += spec_section

    # LLM-enhanced prompt rewrite (optional — preserves governance sections)
    rewritten = rewrite_prompt_with_context(deterministic_prompt, review, effective_stream)
    return rewritten if rewritten else deterministic_prompt


def _build_fallback_prompt(review, trains, sprint_goal, test_line,
                           next_sprint, venv_path, dotnet_test_cmd,
                           stream="mainstream"):
    """Build prompt when template file is not available."""
    lines = []
    lines.append(f"# FORMAT-FACTORY-{next_sprint}-MEGA-TRAIN-001")
    lines.append(f"# Stream: {stream}")
    lines.append(f"Generated: {datetime.now().isoformat()}")
    lines.append(f"Prior Sprint: {review.get('sprint_id', 'unknown')}")
    lines.append(f"Prior Verdict: {review.get('overall_verdict', 'unknown')}")
    lines.append(f"Tests: {test_line}")
    lines.append("")
    lines.append(sprint_goal)
    lines.append("")

    lines.append("## Preflight")
    lines.append(format_preflight_list())
    lines.append("")

    lines.append("## Train Manifest")
    lines.append(format_train_manifest_table(trains))
    lines.append("")

    lines.append(format_train_details(trains))

    lines.append(STOP_REASON_ADVISORY)
    lines.append("")

    lines.append("## Hard Prohibitions")
    lines.append("- No git push: SCM Agent task (AGENTS.md §AG4.2) — execute when credentials and branch policy allow; classify EXTERNAL_BLOCKER otherwise.")
    lines.append("- No git commit: SCM Agent task (AGENTS.md §AG4.1) — execute when sprint policy authorizes, tests pass, diff clean; classify specific blocker otherwise.")
    lines.append("- No Gate 11 G11-G approval (sole TRUE_EXTERNAL_GATE — Babar Raza only).")
    lines.append("- No commercial_product_ready: true.")
    lines.append("- No PyPI/NuGet/GitHub release publication.")
    lines.append("- No paid external AI API or web automation.")
    lines.append("- No MCP activation unless MODE 4 already authorized.")
    lines.append("- No destructive git operations.")
    lines.append("- No PENDING markers in final state files.")
    lines.append(f"- No ad-hoc `src/` edits: use `{SKILL_REGISTRY_PATH}` or a generated execution handoff.")
    lines.append(f"- Any `src/` edit requires an entry in `{PRODUCT_CODE_LEDGER_PATH}`.")
    lines.append("")

    lines.append("## Final Validation Sequence")
    lines.append(f"1. `{venv_path} -m pytest tests/ -x -q --tb=short`")
    lines.append(f"2. `{venv_path} -m py_compile tools/supervisor/autonomous_cycle.py`")
    lines.append(f"3. `{dotnet_test_cmd}`")
    lines.append("4. Write evidence-declaration.yaml")
    lines.append("5. Run autonomous-cycle")
    lines.append("")

    lines.append("## Evidence Declaration Requirements")
    lines.append("At sprint end, create `.local/evidences/<run_id>/evidence-declaration.yaml`")
    lines.append("Then run:")
    lines.append("```")
    lines.append(f"{venv_path} tools/supervisor/supervisor_loop.py autonomous-cycle \\")
    lines.append("  --declaration .local/evidences/<run_id>/evidence-declaration.yaml")
    lines.append("```")
    lines.append("")

    return "\n".join(lines)


# R108: Stream-specific forward work descriptions
STREAM_FORWARD_WORK = {
    "acceleration": [
        {"id": "ACCEL-DETECT", "title": "Expand anti-skip detectors or severity mapping",
         "desc": "Add new detectors, refine severity levels, or improve detection accuracy."},
        {"id": "ACCEL-GRADE", "title": "Improve grading engine or evidence quality scoring",
         "desc": "Enhance grade_declared_work.py or evidence quality heuristics."},
        {"id": "ACCEL-GATE", "title": "Harden hard gates and continuation policy",
         "desc": "Strengthen autonomous-cycle enforcement and stop conditions."},
    ],
    "skills": [
        {"id": "SKILL-GOV", "title": "Expand governed skill commands",
         "desc": "Add new governed skills or improve skill validation."},
        {"id": "SKILL-TRANSCRIPT", "title": "Strengthen transcript validation",
         "desc": "Improve transcript ledger, validation fixtures, or governance checks."},
    ],
    "supervisor": [
        {"id": "SUP-PIPE", "title": "Improve supervisor pipeline components",
         "desc": "Enhance inspection, grading, prompt generation, or context-pack building."},
        {"id": "SUP-EVIDENCE", "title": "Strengthen evidence model or declaration schema",
         "desc": "Improve declaration validation, manifest generation, or materialization."},
    ],
}


# R-NMPC: Patterns that always require external human authorization — never agent-executable
_EXTERNAL_GATE_PATTERNS = [
    "gate 11",
    "g11-g",
    "publication",
    "publish to nuget",
    "nuget publish",
    "human required for commercial",
    "commercial release",
]


def _next_action_requires_external_gate(next_action: str) -> bool:
    """Return True if next_action text indicates an external gate (commit/push/Gate/publication)."""
    if not next_action:
        return False
    lower = next_action.lower()
    return any(p in lower for p in _EXTERNAL_GATE_PATTERNS)


def _make_task_adjudication_fields(task_label: str, task_title: str, context: dict | None = None) -> dict:
    """Add stop-reason-adjudicator fields to a generated task.

    Every generated task must have owner_classification, gate_classification,
    stop_reason_decision, agent_can_execute, human_required, execution_status,
    allowed_next_action. This prevents future agents from treating agent-owned
    work as blocked.
    """
    # If the caller has already determined this is an external gate (via
    # _next_action_requires_external_gate), honour that directly instead of
    # letting the adjudicator re-derive signal from the generic task title.
    label_normalized = task_label.lower().strip().lstrip("[").rstrip("]")
    if label_normalized == "external-gate":
        decision = "TRUE_EXTERNAL_GATE"
        agent_can_execute = False
        new_label = "external-gate"
        reason = "next_action text contains commit/push/Gate/publication wording"
    else:
        try:
            sys.path.insert(0, str(SCRIPT_DIR))
            from stop_reason_adjudicator import reclassify_task_label
            classification = reclassify_task_label(task_label, task_title, context)
            decision = classification["adjudication"]["decision"]
            agent_can_execute = classification["agent_can_execute"]
            new_label = classification["new_label"]
            reason = classification["adjudication"]["reason"]
        except Exception:
            # If adjudicator unavailable, default to agent-owned (safest non-blocking default)
            decision = "CONTINUE_NEXT_ITERATION"
            agent_can_execute = True
            new_label = "agent-owned"
            reason = "Adjudicator unavailable — defaulting to agent-owned"

    return {
        "owner_classification": new_label,
        "gate_classification": decision,
        "stop_reason_decision": decision,
        "agent_can_execute": agent_can_execute,
        "human_required": not agent_can_execute,
        "execution_status": "executable" if agent_can_execute else "external-gate-pending",
        "allowed_next_action": (
            "Execute this task directly" if agent_can_execute
            else "Classify specific blocker per AGENTS.md §AG — execute if agent policy allows, else record EXTERNAL_BLOCKER"
        ),
        "stop_reason_reason": reason,
    }


def _run_capability_consumer(repo_root: Path, max_gaps: int = 3) -> list[dict]:
    """Subprocess-invoke capability_queue_consumer.py and return compiled taskcard dicts.

    TC-WIRE-001: production wiring of the capability compiler into the supervisor pipeline
    via subprocess dispatch (not library import — consistent with system's subprocess pattern).

    Returns [] on any failure (non-blocking); never raises.
    """
    import subprocess
    import tempfile

    consumer_script = repo_root / "tools" / "supervisor" / "capability_queue_consumer.py"
    if not consumer_script.exists():
        return []

    with tempfile.TemporaryDirectory() as tmp_dir:
        try:
            result = subprocess.run(
                [sys.executable, str(consumer_script),
                 "--max-gaps", str(max_gaps),
                 "--output-dir", tmp_dir],
                capture_output=True, text=True, timeout=60,
                cwd=str(repo_root),
            )
        except Exception:
            return []

        if result.returncode != 0:
            return []

        taskcards = []
        for tc_path in sorted(Path(tmp_dir).glob("TC-*.json")):
            try:
                tc = json.loads(tc_path.read_text(encoding="utf-8"))
                taskcards.append(tc)
            except Exception:
                continue
        return taskcards


def generate_next_work_items(review: dict, stream: str = None, plan_lock: dict | None = None,
                            work_groups: list | None = None) -> dict:
    """Generate next-work-items.yaml from review.

    R108: When stream is specified, only include items relevant to that stream.
    Product-factory items are only included for mainstream (or None).
    Non-mainstream streams get stream-specific forward work.

    Every generated task includes stop_reason_adjudicator fields to prevent
    false stops. The labels [approval-blocked], [blocked], [human-required]
    are replaced with correct classifications.

    plan_lock: if provided and status != COMPLETE, suppresses all system-ledger items
    and returns a single PLAN-ACTIVE work item scoped to the active plan.

    work_groups: TC-P2-003 / REQ-TRK-005, REQ-TRK-006 — when set, restricts generated items
    to the specified work groups (e.g. ["G3","G4","G5"] for Track P,
    ["G1","G2","G6","G7","G8"] for Track M). None = include all groups.
    """
    # Plan-lock guard: if a per-chat plan is active, suppress system ledger entirely.
    if plan_lock and plan_lock.get("status") != "COMPLETE":
        _plan_path = plan_lock.get("plan_path", "unknown")
        _last_tc = plan_lock.get("last_taskcard", "unknown")
        return {
            "items": [
                {
                    "item_id": "PLAN-ACTIVE",
                    "title": "Execute next taskcard in active per-chat plan",
                    "lane": "per-chat-plan",
                    "priority": 1,
                    "description": (
                        f"A per-chat plan is active and must be completed before ledger work. "
                        f"Plan: {_plan_path}. Last completed taskcard: {_last_tc!r}. "
                        f"Read the plan file, find the next open taskcard after {_last_tc!r}, "
                        f"and execute it. Run write_plan_lock.py after each taskcard completes."
                    ),
                    "acceptance_criteria": "All plan taskcards CLOSED, plan status=COMPLETE",
                    "verification_command": (
                        f"python tools/supervisor/write_plan_lock.py "
                        f"--plan-path \"{_plan_path}\" --complete"
                    ),
                    "evidence_expected": "plan lock status=COMPLETE",
                    "source": "per-chat-plan",
                    "stop_reason_adjudication": "agent-owned",
                    "human_required": False,
                    "blocked_by": None,
                    "external_gate": False,
                }
            ],
            "work_selection_mode": "PLAN_LOCKED",
            "stream": stream or "mainstream",
            "active_plan": _plan_path,
            "last_taskcard": _last_tc,
            "ledger_items_suppressed": True,
        }

    items = []
    priority = 1
    effective_stream = stream or "mainstream"

    # TC-P2-003: Determine effective group set for filtering.
    # work_groups=None means no filter (all groups included).
    _wg_set = set(work_groups) if work_groups else None

    def _group_allowed(group_id: str) -> bool:
        """Return True if group_id is in the allowed work_groups (or no filter set)."""
        return _wg_set is None or group_id in _wg_set

    # Rework items (G2): included when G2 is allowed (or no filter)
    if _group_allowed("G2"):
        for g in review.get("item_grades", []):
            if g["supervisor_grade"] in ("REWORK_REQUIRED", "OVERCLAIMED"):
                title = f"Rework: {g['item_title']}"
                adj = _make_task_adjudication_fields("[agent-owned]", title)
                items.append({
                    "item_id": f"REWORK-{g['item_id']}",
                    "title": title,
                    "lane": "rework",
                    "priority": priority,
                    "description": g.get("required_rework", ""),
                    "acceptance_criteria": "Evidence found and tests pass",
                    "verification_command": "",
                    "evidence_expected": f"Evidence at declared paths for {g['item_id']}",
                    "source": "rework-from-prior",
                    **adj,
                })
                priority += 1

    # Capability-compiler-generated work items (TC-WIRE-001: subprocess invocation)
    # Non-blocking: if consumer fails or returns nothing, continues with existing items.
    # These are G4 product items — only include when Track P groups allowed.
    _product_groups_allowed = any(_group_allowed(g) for g in ("G3", "G4", "G5"))
    if effective_stream in ("mainstream", "product", None) and _product_groups_allowed:
        compiled_taskcards = _run_capability_consumer(REPO_ROOT)
        for tc in compiled_taskcards:
            func_name = tc.get("function_name", "capability_function")
            title = tc.get("title", f"Implement {func_name}")
            adj = _make_task_adjudication_fields("[agent-owned]", title)
            items.append({
                "item_id": tc.get("taskcard_id", f"CAP-{func_name.upper()}"),
                "title": title,
                "lane": "capability-compiler",
                "priority": priority,
                "description": (
                    f"Compiler-generated taskcard from gap {tc.get('source_gap_id', '')}. "
                    f"Implement {func_name} in {tc.get('expected_module', 'src/python/<format>/')}. "
                    f"Min tests: {tc.get('test_obligations', {}).get('min_test_count', 10)}. "
                    f"Evidence: {', '.join(tc.get('evidence_obligations', []))}."
                ),
                "acceptance_criteria": tc.get("acceptance_criteria", f"{func_name} passes 10+ tests"),
                "verification_command": f"python -m pytest {tc.get('governance_requirements', {}).get('source_diff_paths', [''])[0].replace('src/', 'tests/')}",
                "evidence_expected": ", ".join(tc.get("evidence_obligations", [])),
                "source": "capability-compiler",
                **adj,
            })
            priority += 1

    if effective_stream in ("mainstream", "product") and _product_groups_allowed:
        # Product-factory forward work from POC targets (mainstream only, Track P allowed)
        poc_targets = load_poc_targets(REPO_ROOT)
        for product in poc_targets.get("commercial_net_products", []):
            fmt = product.get("format", "unknown")
            title = f"Advance {fmt} commercial .NET product"
            _net_label = "[external-gate]" if _next_action_requires_external_gate(product.get("next_action", "")) else "[agent-owned]"
            adj = _make_task_adjudication_fields(_net_label, title)
            desc = (
                f"Product target: {fmt} commercial .NET. "
                f"{product.get('next_action', f'Continue {fmt} product deepening')}. "
                f"Select work from {SELECTED_PRODUCT_GAPS_PATH}; use {SKILL_REGISTRY_PATH}; "
                f"record any src edit in {PRODUCT_CODE_LEDGER_PATH}."
            )
            items.append({
                "item_id": f"PRODUCT-{fmt.upper()}",
                "title": title,
                "lane": "product-advancement",
                "priority": priority,
                "description": desc,
                "acceptance_criteria": "Test count increased, new APIs or features proven",
                "verification_command": "",
                "evidence_expected": "Test results, code changes",
                "source": "product-factory",
                **adj,
            })
            priority += 1

        for product in poc_targets.get("foss_reduced_products", []):
            fmt = product.get("format", "unknown")
            title = f"Advance {fmt} FOSS product"
            _foss_label = "[external-gate]" if _next_action_requires_external_gate(product.get("next_action", "")) else "[agent-owned]"
            adj = _make_task_adjudication_fields(_foss_label, title)
            desc = (
                f"Product target: {fmt} FOSS Python. "
                f"{product.get('next_action', f'Continue {fmt} FOSS work')}. "
                f"Select work from {SELECTED_PRODUCT_GAPS_PATH}; use {SKILL_REGISTRY_PATH}; "
                f"record any src edit in {PRODUCT_CODE_LEDGER_PATH}."
            )
            items.append({
                "item_id": f"FOSS-{fmt.upper()}",
                "title": title,
                "lane": "product-advancement",
                "priority": priority,
                "description": desc,
                "acceptance_criteria": "Test count maintained or increased",
                "verification_command": "",
                "evidence_expected": "Test results",
                "source": "product-factory",
                **adj,
            })
            priority += 1
    else:
        # R108: Non-mainstream streams get stream-specific forward work
        forward_items = STREAM_FORWARD_WORK.get(effective_stream, [])
        for fw in forward_items:
            title = fw["title"]
            adj = _make_task_adjudication_fields("[agent-owned]", title)
            items.append({
                "item_id": fw["id"],
                "title": title,
                "lane": f"{effective_stream}-advancement",
                "priority": priority,
                "description": fw["desc"],
                "acceptance_criteria": "Tests pass, evidence declared",
                "verification_command": "",
                "evidence_expected": "Test results, code changes",
                "source": f"{effective_stream}-forward",
                **adj,
            })
            priority += 1

    return {
        "run_id": review.get("run_id", "unknown"),
        "sprint_id": review.get("sprint_id", "unknown"),
        "stream": effective_stream,
        "work_groups_filter": list(work_groups) if work_groups else None,
        "generated_at": datetime.now().isoformat(),
        "items": items,
        "stop_reason_adjudicator_advisory": (
            "ADVISORY ONLY. Run tools/supervisor/stop_reason_adjudicator.py before treating "
            "any task as blocked. If decision is not TRUE_EXTERNAL_GATE or UNSAFE_WORKSPACE, "
            "repair/continue. Use local coordinator if Ruflo/claude-flow unavailable."
        ),
        "false_stop_labels_forbidden": [
            "approval-blocked", "blocked", "human-required", "stop"
        ],
    }


# ---------------------------------------------------------------------------
# LLM-enhanced prompt rewriter — optional, with governance-section preservation
# ---------------------------------------------------------------------------

# Sections that MUST survive any rewrite unchanged (governance-critical)
_GOVERNANCE_SECTION_HEADERS = [
    "## Hard Prohibitions",
    "## STOP CONDITIONS",
    "## FORBIDDEN",
    "## EVIDENCE REQUIREMENTS",
    "## Evidence Declaration Requirements",
    "## Final Validation Sequence",
    "## ADVISORY: Stop Reason Adjudicator",
]


def _extract_governance_sections(prompt: str) -> list[tuple[str, str]]:
    """Extract governance-critical sections as (header, content) pairs."""
    sections = []
    lines = prompt.split("\n")
    current_header = None
    current_lines = []

    for line in lines:
        is_header = any(line.strip().startswith(h) for h in _GOVERNANCE_SECTION_HEADERS)
        if is_header:
            if current_header:
                sections.append((current_header, "\n".join(current_lines)))
            current_header = line.strip()
            current_lines = [line]
        elif current_header:
            # Stop collecting if we hit a new ## section that isn't governance
            if line.startswith("## ") and not any(line.strip().startswith(h) for h in _GOVERNANCE_SECTION_HEADERS):
                sections.append((current_header, "\n".join(current_lines)))
                current_header = None
                current_lines = []
            else:
                current_lines.append(line)

    if current_header:
        sections.append((current_header, "\n".join(current_lines)))

    return sections


def rewrite_prompt_with_context(
    prompt_text: str, review: dict, stream: str
) -> str | None:
    """LLM-enhanced prompt rewriter. Returns rewritten prompt or None on failure.

    Preserves governance-critical sections verbatim. Enriches the prompt with:
    - Sprint review learnings (what failed, what was overclaimed)
    - Stream-specific context and priorities
    - Removal of stale/irrelevant sections

    Returns None if:
    - LLM gateway is unavailable
    - Rewrite fails prompt quality validation
    """
    try:
        # SCRIPT_DIR = tools/supervisor, repo_root = tools/supervisor/../.. = repo root
        repo_root_for_import = str(SCRIPT_DIR.parent.parent)
        if repo_root_for_import not in sys.path:
            sys.path.insert(0, repo_root_for_import)
        from tools.ai.control_plane.gateway import gateway_chat
        from tools.ai.control_plane.config import load_ai_config
        cfg = load_ai_config()
        if not cfg.is_configured:
            return None
    except Exception:
        return None

    # Extract governance sections to preserve
    gov_sections = _extract_governance_sections(prompt_text)
    gov_headers = [h for h, _ in gov_sections]

    # Build review summary for context
    verdict = review.get("overall_verdict", "unknown")
    rework_items = [
        g for g in review.get("item_grades", [])
        if g.get("supervisor_grade") in ("REWORK_REQUIRED", "OVERCLAIMED", "REJECTED")
    ]
    rework_summary = "; ".join(
        f"{g.get('item_title', g['item_id'])}: {g.get('required_rework', 'unknown issue')}"
        for g in rework_items[:5]
    ) if rework_items else "None"

    quality_score = review.get("evidence_quality_score", 0.0)
    verified_count = review.get("verified_item_count", 0)
    accepted_count = len(review.get("accepted_items", []))

    # Semantic verification summary
    sv_downgrades = []
    for g in review.get("item_grades", []):
        sv = g.get("semantic_verification", {})
        if sv.get("llm_used") and not sv.get("adequate"):
            sv_downgrades.append(f"{g.get('item_title', g['item_id'])}: {sv.get('deficiencies', [])}")

    review_context = (
        f"Prior sprint verdict: {verdict}\n"
        f"Evidence quality: {quality_score:.0%} ({verified_count}/{accepted_count} verified)\n"
        f"Rework items: {rework_summary}\n"
        f"Semantic verification downgrades: {'; '.join(sv_downgrades) if sv_downgrades else 'None'}\n"
        f"Stream: {stream}"
    )

    messages = [
        {"role": "system", "content": (
            "You are a sprint prompt editor for a software build system. "
            "Given a generated sprint prompt and a review summary of the prior sprint, "
            "improve the prompt by:\n"
            "1. Adding a 'Sprint Context' section after the header that summarizes what "
            "went wrong last sprint and what to prioritize differently\n"
            "2. Making acceptance criteria more specific based on prior failures\n"
            "3. Removing sections that are clearly stale or duplicated\n\n"
            "CRITICAL RULES:\n"
            f"- PRESERVE these sections EXACTLY as-is (do not modify, reorder, or remove): "
            f"{gov_headers}\n"
            "- Keep the same markdown structure (# headers, ## sections, ### trains)\n"
            "- Do not add new trains or remove existing ones\n"
            "- Do not change train letters or group assignments\n"
            "- Output the complete rewritten prompt, not a diff"
        )},
        {"role": "user", "content": (
            f"REVIEW CONTEXT:\n{review_context}\n\n"
            f"PROMPT TO IMPROVE:\n{prompt_text[:8000]}"
        )},
    ]

    try:
        resp, _record = gateway_chat(
            config=cfg,
            model="recommended",
            messages=messages,
            role="summarization",
            operation="rewrite_prompt_with_context",
        )
        rewritten = resp.get("content", "")
        # If gateway returned empty (e.g. litellm import failure), try direct SDK
        if not rewritten and _record and getattr(_record, "status", None) and "error" in str(_record.status).lower():
            rewritten = _rewrite_sdk_fallback(messages, cfg) or ""
        if not rewritten or len(rewritten) < 200:
            return None

        # Validate governance sections survived
        for header, content in gov_sections:
            if header not in rewritten:
                return None  # Governance section lost — discard rewrite

        # Validate with prompt quality checker
        try:
            from validate_prompt_quality import validate_prompt_quality
            pq = validate_prompt_quality(rewritten, stream, has_repairs=bool(rework_items))
            if not pq["valid"]:
                return None  # Rewrite failed quality validation — discard
        except Exception:
            pass  # Quality checker unavailable, accept rewrite cautiously

        return rewritten

    except Exception:
        return None


def _rewrite_sdk_fallback(messages: list[dict], cfg) -> str | None:
    """Fallback: call endpoint directly via SDK when litellm fails."""  # policy-allowed
    import os
    import time
    _max_attempts = 3
    _backoff = [1, 2, 4]
    key = os.environ.get("GPT_OSS_API_KEY", "").strip()
    if not key or not cfg.endpoint:
        return None
    for attempt in range(_max_attempts):
        try:
            _sdk = __import__("openai")  # policy-approved endpoint only
            _Client = _sdk.OpenAI  # policy-approved
            client = _Client(base_url=cfg.endpoint, api_key=key)
            resp = client.chat.completions.create(
                model="recommended",
                messages=messages,
                max_tokens=4000,
                temperature=0,
            )
            return resp.choices[0].message.content or None
        except Exception as exc:
            print(f"  [LLM] SDK fallback attempt {attempt + 1}/{_max_attempts} failed: {type(exc).__name__}")
            if attempt < _max_attempts - 1:
                time.sleep(_backoff[attempt])
    print("  [LLM] All SDK fallback attempts exhausted")
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate next worker prompt")
    parser.add_argument("--review", type=Path, required=True, help="Path to supervisor-review.json")
    parser.add_argument("--output-dir", type=Path, required=True, help="Output directory")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT, help="Repository root")
    parser.add_argument("--stream", type=str, default=None,
                        choices=["mainstream", "acceleration", "skills", "supervisor"],
                        help="Target stream for prompt generation (R108)")
    args = parser.parse_args()

    if not args.review.exists():
        print(f"ERROR: Review not found: {args.review}", file=sys.stderr)
        return 1

    review = json.loads(args.review.read_text(encoding="utf-8"))

    args.output_dir.mkdir(parents=True, exist_ok=True)

    # R108: Auto-detect stream from sprint_id if not specified
    stream = args.stream
    if stream is None:
        sprint_id = review.get("sprint_id", "")
        import re as _re
        m = _re.match(r"FORMAT-FACTORY-(SUPERVISOR|ACCELERATION|SKILLS|MAINSTREAM)-R\d+", sprint_id.upper())
        if m:
            stream = m.group(1).lower()

    # Generate prompt
    prompt = generate_prompt(review, repo_root=args.repo_root, stream=stream)
    prompt_path = args.output_dir / "combined-next-worker-prompt.md"
    prompt_path.write_text(prompt, encoding="utf-8")

    # Generate next work items
    next_work = generate_next_work_items(review, stream=stream)
    work_path = args.output_dir / "next-work-items.yaml"
    work_path.write_text(yaml.dump(next_work, default_flow_style=False, sort_keys=False), encoding="utf-8")
    (args.output_dir / "next-work-items.json").write_text(json.dumps(next_work, indent=2), encoding="utf-8")

    print(f"PROMPT_GENERATED: {prompt_path}")
    print(f"NEXT_WORK_ITEMS: {work_path}")
    print(f"  Rework items: {len([i for i in next_work['items'] if i['lane'] == 'rework'])}")
    print(f"  Product items: {len([i for i in next_work['items'] if i['lane'] == 'product-advancement'])}")
    print(f"  Train count: {len(prompt.splitlines())} lines in mega-train prompt")

    return 0


if __name__ == "__main__":
    sys.exit(main())
