"""V91 (TC-ROOT-005): Root structure architecture governance validator.

Validates repository top-level directories against registry/repository-root-folders.yaml.

Checks:
  1. Registry completeness — every top-level directory on disk is registered
  2. README presence — every RETAIN folder with readme_required has its README
  3. Resurrection detection — DELETED folders must not exist on disk
  4. Format coverage contract — format-scoped folders match coverage baseline

FAIL + blocks_sprint=True for unregistered directories.
WARN for missing READMEs, resurrected deleted dirs, coverage gaps.
"""
from __future__ import annotations
from governance_validators_contract import validator  # noqa: F401

import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]


def _check_source_test_parity(repo_root: Path) -> list[dict]:
    """
    TC-RR-004 (C3): For every src/python/{fmt}/ that exists, verify tests/python/{fmt}/ exists.
    For every src/net/{fmt}/ that exists, verify tests/net/{fmt}/ exists.
    No external file dependency. Returns list of FORMAT_COVERAGE_GAP findings (WARN, non-blocking).
    """
    findings = []
    skip_prefix = ("_", ".")

    src_python = repo_root / "src" / "python"
    tests_python = repo_root / "tests" / "python"
    if src_python.is_dir():
        for fmt_dir in sorted(src_python.iterdir()):
            if not fmt_dir.is_dir():
                continue
            if any(fmt_dir.name.startswith(p) for p in skip_prefix):
                continue
            expected_test = tests_python / fmt_dir.name
            if not expected_test.is_dir():
                findings.append({
                    "check": "format_coverage_gap",
                    "path": f"tests/python/{fmt_dir.name}",
                    "severity": "WARN",
                    "category": "FORMAT_COVERAGE_GAP",
                    "message": f"src/python/{fmt_dir.name} exists but tests/python/{fmt_dir.name} is missing",
                })

    src_net = repo_root / "src" / "net"
    tests_net = repo_root / "tests" / "net"
    if src_net.is_dir():
        for fmt_dir in sorted(src_net.iterdir()):
            if not fmt_dir.is_dir():
                continue
            if any(fmt_dir.name.startswith(p) for p in skip_prefix):
                continue
            expected_test = tests_net / fmt_dir.name
            if not expected_test.is_dir():
                findings.append({
                    "check": "format_coverage_gap",
                    "path": f"tests/net/{fmt_dir.name}",
                    "severity": "WARN",
                    "category": "FORMAT_COVERAGE_GAP",
                    "message": f"src/net/{fmt_dir.name} exists but tests/net/{fmt_dir.name} is missing",
                })

    return findings


def _check_readme_content_floor(readme_path: Path) -> list[str]:
    """
    TC-RR-005 (C4): Returns list of missing structural markers. Empty = passes floor.
    Only catches absolute floor failures (stubs, empty files). WARN severity.
    """
    try:
        size = readme_path.stat().st_size
    except OSError:
        return ["file_unreadable"]
    if size < 200:
        return ["too_short"]
    try:
        content = readme_path.read_text(encoding="utf-8", errors="replace").lower()
    except OSError:
        return ["file_unreadable"]
    missing = []
    if not any(kw in content for kw in
               ["purpose", "what this", "this folder", "this directory", "# "]):
        missing.append("no_purpose_statement")
    if not any(kw in content for kw in
               ["producer", "created by", "written by", "generated by",
                "who creates", "origin", "source:"]):
        missing.append("no_producer_declaration")
    if not any(kw in content for kw in
               ["agent", "validation", "command", "run ", "python ", "pytest"]):
        missing.append("no_actionable_guidance")
    return missing


def _check_registry_producer_integrity(entry: dict, repo_root: Path) -> str | None:
    """
    TC-RR-008 (C6): Returns a warning message if producers list has no resolvable tool path.
    A producer is 'resolvable' if it names a file that exists in the repo.
    """
    producers = entry.get("producers", [])
    if not producers:
        return None
    non_verifiable = {
        "developers", "humans", "agents", "users", "ci",
        "source generators", "test generators", "acquisition workflow",
        "supervisor", "oracle", "spec-parity tools",
    }
    all_non_verifiable = all(p.lower() in non_verifiable for p in producers)
    if all_non_verifiable:
        return (
            f"Folder '{entry['folder_path']}' lists only non-verifiable producers "
            f"{producers}. Consider adding at least one tool path."
        )
    return None


@validator(rule_id="V_VALIDATE_ROOT_STRUCTURE", domain="root_struct")
def validate_root_structure(
    declaration: dict, repo_root: "Path | None" = None
) -> dict:
    """V91: Root structure architecture governance."""
    from governance_validator_utils import _make_result  # noqa: PLC0415

    _r = repo_root or _REPO_ROOT
    registry_path = _r / "registry" / "repository-root-folders.yaml"

    if not registry_path.exists():
        return _make_result(
            "root_structure_validator", "WARN", [],
            "registry/repository-root-folders.yaml not found — skipping",
            blocks_sprint=False,
        )

    import yaml  # noqa: PLC0415
    with open(registry_path, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    folders = data.get("folders", [])
    if not folders:
        return _make_result(
            "root_structure_validator", "WARN", [],
            "Registry has no folder entries", blocks_sprint=False,
        )

    # Build lookup
    by_path: dict[str, dict] = {}
    for entry in folders:
        fp = entry.get("folder_path", "").rstrip("/")
        by_path[fp] = entry

    items: list[dict] = []
    has_fail = False

    # --- Check 1: Every top-level directory on disk is registered ---
    skip_names = {"__pycache__", "node_modules", "dist"}
    for child in sorted(_r.iterdir()):
        if not child.is_dir():
            continue
        name = child.name
        if name in skip_names:
            continue
        key = name
        if key not in by_path:
            items.append({
                "check": "unregistered_directory",
                "path": name,
                "severity": "FAIL",
                "message": f"Top-level directory '{name}' is not in repository-root-folders.yaml",
            })
            has_fail = True

    # --- Check 2: README presence + content floor for RETAIN folders ---
    for entry in folders:
        if entry.get("retention") != "RETAIN":
            continue
        if not entry.get("readme_required"):
            continue
        fp = entry["folder_path"].rstrip("/")
        folder = _r / fp
        if not folder.exists():
            continue
        convention = entry.get("readme_convention", "README.md")
        readme = folder / convention
        if not readme.exists():
            items.append({
                "check": "missing_readme",
                "path": f"{fp}/{convention}",
                "severity": "WARN",
                "message": f"RETAIN folder '{fp}' is missing {convention}",
            })
        else:
            floor_issues = _check_readme_content_floor(readme)
            if floor_issues:
                items.append({
                    "check": "readme_floor_fail",
                    "path": f"{fp}/{convention}",
                    "severity": "WARN",
                    "message": f"README floor check failed for '{fp}': {floor_issues}",
                })
        integrity_warn = _check_registry_producer_integrity(entry, _r)
        if integrity_warn:
            items.append({
                "check": "registry_producer_integrity",
                "path": entry["folder_path"],
                "severity": "WARN",
                "message": integrity_warn,
            })

    # --- Check 3: Resurrection detection ---
    for entry in folders:
        if entry.get("retention") != "DELETED":
            continue
        fp = entry["folder_path"].rstrip("/")
        folder = _r / fp
        if folder.exists():
            items.append({
                "check": "resurrected_deleted",
                "path": fp,
                "severity": "FAIL",
                "message": f"Deleted folder '{fp}' has reappeared on disk",
            })
            has_fail = True

    # --- Check 4: Source-test parity (in-memory, no external file required) ---
    items.extend(_check_source_test_parity(_r))

    # Determine result
    if has_fail:
        result = "FAIL"
    elif items:
        result = "WARN"
    else:
        result = "PASS"

    fail_count = sum(1 for i in items if i.get("severity") == "FAIL")
    warn_count = sum(1 for i in items if i.get("severity") == "WARN")
    summary = f"Root structure: {fail_count} FAIL, {warn_count} WARN, {len(by_path)} registered folders"

    return _make_result(
        "root_structure_validator", result, items, summary,
        blocks_sprint=has_fail,
    )


def main() -> int:
    """CLI entry point."""
    import argparse  # noqa: PLC0415
    parser = argparse.ArgumentParser(description="Validate repository root structure")
    parser.add_argument("--repo-root", type=Path, default=None)
    parser.add_argument("--json", action="store_true", help="Output JSON")
    args = parser.parse_args()

    result = validate_root_structure({}, args.repo_root)

    if args.json:
        print(json.dumps(result, indent=2, default=str))
    else:
        print(f"Result: {result['result']}")
        print(f"Summary: {result['summary']}")
        if result.get("items"):
            for item in result["items"]:
                print(f"  [{item['severity']}] {item['message']}")

    return 0 if result["result"] != "FAIL" else 1


if __name__ == "__main__":
    sys.exit(main())
