"""Exception coverage tests for pgm format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from pgm.exceptions import PgmParseError, PgmWriteError
from pgm.exceptions import PgmError


def test_pgmparseerror_is_raisable():
    with pytest.raises(PgmParseError):
        raise PgmParseError("test error message")


def test_pgmparseerror_inherits_base():
    assert issubclass(PgmParseError, PgmError)


def test_pgmparseerror_message():
    exc = PgmParseError("specific error")
    assert "specific error" in str(exc)


def test_pgmwriteerror_is_raisable():
    with pytest.raises(PgmWriteError):
        raise PgmWriteError("test error message")


def test_pgmwriteerror_inherits_base():
    assert issubclass(PgmWriteError, PgmError)


def test_pgmwriteerror_message():
    exc = PgmWriteError("specific error")
    assert "specific error" in str(exc)
