"""Exception coverage tests for gnumeric format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from gnumeric.exceptions import GnumericWriteError
from gnumeric.exceptions import GnumericError


def test_gnumericwriteerror_is_raisable():
    with pytest.raises(GnumericWriteError):
        raise GnumericWriteError("test error message")


def test_gnumericwriteerror_inherits_base():
    assert issubclass(GnumericWriteError, GnumericError)


def test_gnumericwriteerror_message():
    exc = GnumericWriteError("specific error")
    assert "specific error" in str(exc)
