"""
Gnumeric JSON Export Example
==============================
Demonstrates export_to_json() added in R120.

Usage:
    python examples/python/gnumeric/json_export_example.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "src" / "python"))

from gnumeric.gnumeric_codec import create_gnumeric, write_gnumeric, export_to_json

# --- Create a workbook ---
sheets = [
    {
        "name": "Q4 Revenue",
        "rows": [
            ["Region", "Revenue", "Growth %"],
            ["North", "162000", "12.5"],
            ["South", "125000", "8.3"],
            ["East", "108000", "9.1"],
            ["West", "189000", "15.2"],
        ],
    },
    {
        "name": "Notes",
        "rows": [
            ["Generated by", "Format Factory"],
            ["Format", "Gnumeric (.gnumeric)"],
        ],
    },
]

model = create_gnumeric(sheets)
output_path = Path(__file__).parent / "example_output.gnumeric"
write_gnumeric(model, output_path)
print(f"Written: {output_path}")

# --- Export to JSON ---
json_str = export_to_json(output_path)
json_path = Path(__file__).parent / "example_output.json"
json_path.write_text(json_str, encoding="utf-8")
print(f"JSON export ({len(json_str)} chars): {json_path}")

parsed = json.loads(json_str)
for sheet_data in parsed:
    print(f"\nSheet: {sheet_data['name']}")
    for row in sheet_data["rows"]:
        print("  ", row)

# --- Cleanup ---
output_path.unlink(missing_ok=True)
json_path.unlink(missing_ok=True)
