"""
edit_save_export_fods.py — Example: load, edit, save, and export a FODS spreadsheet.

This example demonstrates the complete R78 FODS product workflow:

1. Parse an existing FODS file into the neutral model
2. Inspect the workbook using analysis APIs
3. Edit cells using workbook_set_cell_value()
4. Add a new summary sheet using workbook_add_sheet()
5. Write the modified workbook back to FODS
6. Export the primary sheet to CSV using csv_exporter

Requirements:
    pip install format-factory-fods

Usage:
    python examples/python/fods/edit_save_export_fods.py

License: Apache-2.0 — Format Factory Python FOSS track
"""
from __future__ import annotations

import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))

from src.python.fods import (
    parse_fods,
    write_fods,
    workbook_stats,
    workbook_sheet_order,
    workbook_sheet_summary,
    workbook_set_cell_value,
    workbook_warnings_for_unsupported_edit,
    workbook_add_sheet,
)
try:
    from fods.csv_exporter import export_fods_to_csv_file
except ImportError:
    import sys
    from pathlib import Path as _Path
    sys.path.insert(0, str(_Path(__file__).resolve().parents[3]))
from src.python.fods.csv_exporter import export_fods_to_csv_file

SAMPLE_FODS = REPO_ROOT / "samples" / "by-format" / "fods" / "minimal-spreadsheet.fods"


def main() -> None:
    print("=== FODS Edit-Save-Export Example ===\n")

    # Step 1: Parse
    print(f"Loading: {SAMPLE_FODS.name}")
    wb = parse_fods(SAMPLE_FODS)
    stats = workbook_stats(wb)
    print(f"Sheets: {stats.get('sheet_count', 0)}")
    print(f"Total cells: {stats.get('total_cells', 0)}")

    sheets = workbook_sheet_order(wb)
    print(f"Sheet names: {sheets}")

    if not wb.get("sheets"):
        print("No sheets found in workbook")
        return

    # Step 2: Inspect sheet structure
    summary = workbook_sheet_summary(wb)
    for s in summary:
        print(f"  Sheet '{s['name']}': {s.get('row_count', 0)} rows")

    primary_sheet = sheets[0]

    # Step 3: Check for edit warnings before editing
    warnings = workbook_warnings_for_unsupported_edit(wb, primary_sheet, 0, 0)
    if warnings:
        print(f"\nEdit warnings for ({primary_sheet}, 0, 0):")
        for w in warnings:
            print(f"  WARNING: {w}")
    else:
        print(f"\nNo edit warnings for sheet '{primary_sheet}', cell (0,0)")

    # Step 4: Edit a cell value
    original_rows = wb["sheets"][0].get("rows", [])
    if original_rows and original_rows[0].get("cells"):
        original_val = original_rows[0]["cells"][0].get("value", "(empty)")
        print(f"\nBefore edit: {original_val!r}")
        ok, msg = workbook_set_cell_value(wb, primary_sheet, 0, 0, "Edited by Format Factory")
        print(f"Edit result: {msg}")
        print(f"After edit: {wb['sheets'][0]['rows'][0]['cells'][0]['value']!r}")
    else:
        print("\nSkipping cell edit (no rows in sheet)")

    # Step 5: Add a summary sheet
    ok, msg = workbook_add_sheet(wb, "R78_Summary")
    if ok:
        # Add a header row to the new sheet
        workbook_set_cell_value(wb, "R78_Summary", 0, 0, "Generated by R78 Example")
        print(f"\nAdded sheet 'R78_Summary': {msg}")
    else:
        print(f"\nAdd sheet note: {msg}")

    # Step 6: Save modified workbook
    with tempfile.NamedTemporaryFile(suffix=".fods", delete=False) as tf:
        fods_out = Path(tf.name)

    write_fods(wb, fods_out)
    print(f"\nSaved FODS to: {fods_out}")

    # Step 7: Export primary sheet to CSV
    with tempfile.NamedTemporaryFile(suffix=".csv", delete=False, mode="w") as tf:
        csv_out = Path(tf.name)

    primary_sheet_index = workbook_sheet_order(wb).index(primary_sheet)
    export_fods_to_csv_file(wb, csv_out, sheet_index=primary_sheet_index)
    csv_content = csv_out.read_text()
    line_count = len(csv_content.splitlines())
    print(f"Exported '{primary_sheet}' to CSV: {csv_out.name} ({line_count} lines)")

    # Step 8: Verify round-trip
    wb2 = parse_fods(fods_out)
    sheets2 = workbook_sheet_order(wb2)
    print(f"\nRound-trip sheets: {sheets2}")
    assert "R78_Summary" in sheets2, "R78_Summary sheet survived round-trip"
    print("Round-trip verification: PASS")

    print("\n=== Edit-Save-Export Example Complete ===")


if __name__ == "__main__":
    main()
