"""
generate_discovery_indexes.py — Capability Sync Tool 3/7

Pure functions (no file I/O) that generate capability discovery sections
for CLAUDE.md and AGENTS.md.

Both functions produce stable Markdown tables wrapped in BEGIN/END markers.
The drift hash strips the 'generated=' timestamp attribute so that
timestamp changes alone don't cause false drift detection.
"""
import hashlib
import re
from typing import Any


CLAUDE_BEGIN_TMPL = "<!-- BEGIN:CAPABILITY-INDEX generated={ts} source=.governance/capabilities/registry.yaml -->"
CLAUDE_END = "<!-- END:CAPABILITY-INDEX -->"
AGENTS_BEGIN_TMPL = "<!-- BEGIN:CAPABILITY-DISCOVERY generated={ts} source=.governance/capabilities/registry.yaml -->"
AGENTS_END = "<!-- END:CAPABILITY-DISCOVERY -->"

_TS_PATTERN = re.compile(r'generated=[^\s>]+')


def compute_content_hash(content: str) -> str:
    """Strip timestamp attribute from generated markers before hashing for stable drift detection."""
    normalized = _TS_PATTERN.sub("generated=STRIPPED", content)
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def _active_sorted(registry: dict) -> list[dict]:
    """Return active capabilities sorted by product_track then capability_id."""
    caps = [c for c in registry.get("capabilities", []) if c.get("status") == "active"]
    return sorted(caps, key=lambda c: (c.get("product_track", ""), c.get("capability_id", "")))


def generate_claude_index(registry: dict, timestamp: str) -> str:
    """Generate the CLAUDE.md capability index section."""
    caps = _active_sorted(registry)
    lines = [
        CLAUDE_BEGIN_TMPL.format(ts=timestamp),
        "",
        "## Generated Capability Index",
        "",
        "This section is auto-generated by `tools/capability_sync/run_sync.py`.",
        "**Do not edit manually.** Run `/sync-capabilities` to update.",
        "",
        f"Total active capabilities: {len(caps)} | "
        f"Canonical registry: `.governance/capabilities/registry.yaml`",
        "",
        "| capability_id | status | product_track | parity_status | claude_code | codex |",
        "|---|---|---|---|---|---|",
    ]
    for c in caps:
        surf = c.get("agent_surfaces", {})
        lines.append(
            f"| `{c['capability_id']}` "
            f"| {c.get('status', '')} "
            f"| {c.get('product_track', '')} "
            f"| {c.get('parity_status', '')} "
            f"| {'Y' if surf.get('claude_code') else 'N'} "
            f"| {'Y' if surf.get('codex') else 'N'} |"
        )
    lines.append("")
    lines.append(CLAUDE_END)
    return "\n".join(lines)


def generate_agents_index(registry: dict, timestamp: str) -> str:
    """Generate the AGENTS.md capability discovery section."""
    caps = _active_sorted(registry)
    lines = [
        AGENTS_BEGIN_TMPL.format(ts=timestamp),
        "",
        "## A2b. Capability Discovery Index (generated — do not edit manually)",
        "",
        "This section is auto-generated by `tools/capability_sync/run_sync.py`.",
        "Run `/sync-capabilities` or `python tools/capability_sync/run_sync.py --mode full` to update.",
        "",
        "**Canonical capability registry:** `.governance/capabilities/registry.yaml`",
        "**Skill contracts:** `.supervisor/skill-registry.yaml`",
        "**Capability routing:** `.supervisor/capability-routing-registry.yaml`",
        "",
        f"Total active capabilities: {len(caps)}",
        "",
        "| capability_id | product_track | parity_status | claude_code | codex | ci | routing_routes |",
        "|---|---|---|---|---|---|---|",
    ]
    for c in caps:
        surf = c.get("agent_surfaces", {})
        routes = ", ".join(c.get("routing_routes", [])) or "—"
        lines.append(
            f"| `{c['capability_id']}` "
            f"| {c.get('product_track', '')} "
            f"| {c.get('parity_status', '')} "
            f"| {'Y' if surf.get('claude_code') else 'N'} "
            f"| {'Y' if surf.get('codex') else 'N'} "
            f"| {'Y' if surf.get('ci') else 'N'} "
            f"| {routes} |"
        )
    lines.append("")
    lines.append(AGENTS_END)
    return "\n".join(lines)
