"""
update_agent_instructions.py — Capability Sync Tool 5/7

Splice the generated capability discovery section into AGENTS.md between stable BEGIN/END markers.
First run: inserts after the §A2a closing line (before **A3.**).
Subsequent runs: replaces content between markers.
Idempotent: no write if content unchanged.
Backs up AGENTS.md before first modification.

Also updates docs/governance/codex-adapter.md to reference .governance/capabilities/registry.yaml
if no reference exists (additive only — no content removed).
"""
import re
from datetime import datetime, timezone
from pathlib import Path

import yaml

_REPO = Path(__file__).resolve().parent.parent.parent
_AGENTS_MD = _REPO / "AGENTS.md"
_CODEX_ADAPTER = _REPO / "docs" / "governance" / "codex-adapter.md"
_REGISTRY = _REPO / ".governance" / "capabilities" / "registry.yaml"
_BACKUP_DIR = _REPO / ".local" / "archive"

BEGIN_PREFIX = "<!-- BEGIN:CAPABILITY-DISCOVERY"
END_MARKER = "<!-- END:CAPABILITY-DISCOVERY -->"

# Pattern to find §A2a closing line for first-run insertion
_A2A_CLOSE_PATTERN = re.compile(r"DEC-014 status.*activated")


def find_marker_bounds(lines: list[str]) -> tuple[int, int] | None:
    for i, line in enumerate(lines):
        stripped = line.rstrip('\n').rstrip('\r')
        if BEGIN_PREFIX in stripped:
            begin_idx = i
            for j in range(i + 1, len(lines)):
                if END_MARKER in lines[j]:
                    return begin_idx, j
    return None


def find_a2a_insertion_point(lines: list[str]) -> int | None:
    """Find line index after §A2a closing line for first-run insertion."""
    for i, line in enumerate(lines):
        if _A2A_CLOSE_PATTERN.search(line):
            return i + 1  # insert after this line
    return None


def splice_section(content: str, new_block: str) -> str:
    lines = content.splitlines(keepends=True)
    flat = [l.rstrip('\n').rstrip('\r') for l in lines]
    bounds = find_marker_bounds(flat)

    if bounds is not None:
        begin_idx, end_idx = bounds
        new_lines = lines[: begin_idx] + [new_block + "\n"] + lines[end_idx + 1:]
        return "".join(new_lines)
    else:
        # First run: insert after §A2a block
        insert_after = find_a2a_insertion_point(flat)
        if insert_after is not None:
            new_lines = lines[: insert_after + 1] + ["\n" + new_block + "\n"] + lines[insert_after + 1:]
            return "".join(new_lines)
        # Fallback: append at end
        sep = "\n" if content.endswith("\n") else "\n\n"
        return content + sep + new_block + "\n"


def _strip_timestamps(text: str) -> str:
    import re
    return re.sub(r'generated=[^\s>]+', 'generated=STRIPPED', text)


def write_with_backup(path: Path, new_content: str, original_content: str, label: str) -> bool:
    if _strip_timestamps(new_content) == _strip_timestamps(original_content):
        print(f"NO CHANGE — {path.name} already up to date")
        return False
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
    stem = path.stem.lower().replace(".", "-")
    backup = _BACKUP_DIR / f"{stem}-pre-sync-{ts}.md"
    backup.parent.mkdir(parents=True, exist_ok=True)
    backup.write_text(original_content, encoding="utf-8")
    path.write_text(new_content, encoding="utf-8")
    print(f"Wrote backup to {backup}; Updated {label}")
    return True


def update_codex_adapter() -> None:
    """Add .governance/capabilities/registry.yaml reference to codex-adapter.md if absent."""
    if not _CODEX_ADAPTER.exists():
        return
    content = _CODEX_ADAPTER.read_text(encoding="utf-8")
    ref = ".governance/capabilities/registry.yaml"
    if ref in content:
        print(f"NO CHANGE — {_CODEX_ADAPTER.name} already references {ref}")
        return
    # Find the list of registries in Section 1 and append after it
    # Look for the last "- Command registry" line in the section
    lines = content.splitlines(keepends=True)
    insert_idx = None
    for i, line in enumerate(lines):
        if "Capability routing registry" in line or "capability-routing-registry" in line:
            insert_idx = i + 1
        elif "Command registry" in line or "command-registry" in line:
            if insert_idx is None:
                insert_idx = i + 1
    if insert_idx is not None:
        new_line = f"- Capability registry (compiled): `{ref}` (generated by `tools/capability_sync/run_sync.py`)\n"
        lines.insert(insert_idx, new_line)
        _CODEX_ADAPTER.write_text("".join(lines), encoding="utf-8")
        print(f"Updated {_CODEX_ADAPTER.name}: added reference to {ref}")
    else:
        print(f"NOTE: Could not find insertion point in {_CODEX_ADAPTER.name}; skipping registry reference update")


def main() -> int:
    import sys as _sys
    if str(_REPO) not in _sys.path:
        _sys.path.insert(0, str(_REPO))

    if not _REGISTRY.exists():
        print("ERROR: Registry not found. Run inventory_capabilities.py first.")
        return 1
    if not _AGENTS_MD.exists():
        print(f"ERROR: {_AGENTS_MD} not found.")
        return 1

    registry = yaml.safe_load(_REGISTRY.read_text(encoding="utf-8")) or {}
    from tools.capability_sync.generate_discovery_indexes import generate_agents_index
    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    new_block = generate_agents_index(registry, timestamp)

    original = _AGENTS_MD.read_text(encoding="utf-8")
    new_content = splice_section(original, new_block)
    write_with_backup(_AGENTS_MD, new_content, original, "AGENTS.md")

    # Also update codex-adapter.md (additive only)
    update_codex_adapter()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
