"""Exception coverage tests for ndjson format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from ndjson.exceptions import NdjsonWriteError
from ndjson.exceptions import NdjsonError


def test_ndjsonwriteerror_is_raisable():
    with pytest.raises(NdjsonWriteError):
        raise NdjsonWriteError("test error message")


def test_ndjsonwriteerror_inherits_base():
    assert issubclass(NdjsonWriteError, NdjsonError)


def test_ndjsonwriteerror_message():
    exc = NdjsonWriteError("specific error")
    assert "specific error" in str(exc)
