"""
format-factory-ods — ODS (OpenDocument Spreadsheet) parser prototype.

Gate 4 prototype. FOSS track. No third-party dependencies.
Acquisition gates 1-4 passed. Implementation authorized: R27.
commercial_product_ready: false
"""

from .ods_parser import (
    parse_ods,
    parse_ods_strict,
    probe_ods,
    get_capabilities,
    get_cell_value,
    get_sheet_names,
    get_row_count,
    get_column_count,
    get_row_values,
    count_sheets,
    get_all_values,
    get_column_values,
    sum_column,
    filter_rows_by_value,
    average_column,
    max_column_value,
    min_column_value,
    get_cell_count,
    ods_to_csv,
    ods_to_html,
    count_nonempty_cells,
    get_sheet_as_dict_list,
    sum_row,
    count_distinct_values,
    ods_max_row_length,
    ods_numeric_cell_count,
    ods_empty_cell_count,
    ods_row_count,
    ods_string_cell_count,
    ods_column_count,
    OdsError,
    OdsInvalidContainerError,
    OdsSizeError,
    OdsCell,
    OdsRow,
    OdsSheet,
    OdsDocument,
)
from .ods_writer import (
    write_ods,
    document_to_ods_bytes,
    set_cell_value,
    add_sheet,
    remove_sheet,
    rename_sheet,
    add_row,
    delete_row,
)
from .ods_stats import (
    spreadsheet_stats,
    ods_sheet_name_list,
    ods_cell_type_distribution,
    ods_formula_cell_count,
    ods_data_validation_count,
    sheet_name_order,
)

__version__ = "0.1.0.dev0"
__track__ = "python-foss"
__commercial_ready__ = False
__capability_level__ = "alpha-foss-preview"

__all__ = [
    "parse_ods",
    "parse_ods_strict",
    "probe_ods",
    "get_capabilities",
    "OdsError",
    "OdsInvalidContainerError",
    "OdsSizeError",
    "get_cell_value",
    "get_sheet_names",
    "get_row_count",
    "get_column_count",
    "get_row_values",
    "count_sheets",
    "get_all_values",
    "get_column_values",
    "sum_column",
    "filter_rows_by_value",
    "average_column",
    "max_column_value",
    "min_column_value",
    "get_cell_count",
    "ods_to_csv",
    "ods_to_html",
    "count_nonempty_cells",
    "get_sheet_as_dict_list",
    "sum_row",
    "count_distinct_values",
    "OdsCell",
    "OdsRow",
    "OdsSheet",
    "OdsDocument",
    "spreadsheet_stats",
    "ods_sheet_name_list",
    "ods_cell_type_distribution",
    "ods_formula_cell_count",
    "ods_data_validation_count",
    "sheet_name_order",
    "write_ods",
    "document_to_ods_bytes",
    "set_cell_value",
    "add_sheet",
    "remove_sheet",
    "rename_sheet",
    "add_row",
    "delete_row",
    "ods_max_row_length",
    "ods_numeric_cell_count",
    "ods_empty_cell_count",
    "ods_row_count",
    "ods_string_cell_count",
    "ods_column_count",
]
