"""
format-factory: FODP (Flat OpenDocument Presentation) FOSS Python track.

Minimal FOSS implementation for .fodp format support.
ODF 1.3 Part 3 specification — OASIS Royalty-Free Category 1.
Acquisition Gates 1-3 PASSED. Gates 4-7 delegated PASS (R20).

FOSS track only — no commercial readiness implied.
See: acquisition-packs/fodp/ for gate evidence.
"""

from .fodp_codec import (
    FodpError,
    FodpParseError,
    load,
    get_page_count,
    extract_text,
    get_page_metadata,
    fodp_total_text_length,
    fodp_slide_count,
    fodp_slide_shape_counts,
    fodp_total_shape_count,
    fodp_notes_text,
    fodp_has_notes,
    fodp_slide_titles,
    fodp_image_count,
    fodp_empty_slide_count,
    fodp_master_page_count,
    fodp_text_per_slide,
    fodp_average_shapes_per_slide,
    fodp_max_text_per_slide,
    fodp_has_images,
    fodp_min_text_per_slide,
    fodp_total_notes_length,
    fodp_slide_text_density,
    fodp_nonempty_slide_count,
    fodp_text_to_slide_ratio,
    fodp_all_slides_have_text,
    fodp_max_title_length,
    fodp_average_text_per_slide,
    fodp_shape_to_slide_ratio,
    fodp_notes_to_slide_ratio,
    fodp_image_to_slide_ratio,
    fodp_has_empty_slides,
    fodp_title_coverage,
    fodp_is_single_slide,
    fodp_notes_density,
    fodp_has_titles,
    fodp_min_shapes_per_slide,
    fodp_has_multi_slide,
    fodp_max_shapes_per_slide,
    fodp_avg_notes_length,
    fodp_shape_variance,
    fodp_total_shape_count,
    fodp_avg_shapes_per_slide,
    fodp_empty_slide_count,
    fodp_max_text_length,
    fodp_text_length_variance,
    fodp_slide_text_lengths,
    fodp_avg_title_length,
    fodp_is_text_heavy,
    fodp_max_notes_length,
    fodp_slide_count_is_one,
    fodp_is_shape_heavy,
    fodp_has_zero_shapes,
)

__all__ = [
    "FodpError",
    "FodpParseError",
    "load",
    "get_page_count",
    "extract_text",
    "get_page_metadata",
    "fodp_total_text_length",
    "fodp_slide_count",
    "fodp_slide_shape_counts",
    "fodp_total_shape_count",
    "fodp_notes_text",
    "fodp_has_notes",
    "fodp_slide_titles",
    "fodp_image_count",
    "fodp_empty_slide_count",
    "fodp_master_page_count",
    "fodp_text_per_slide",
    "fodp_average_shapes_per_slide",
    "fodp_max_text_per_slide",
    "fodp_has_images",
    "fodp_min_text_per_slide",
    "fodp_total_notes_length",
    "fodp_slide_text_density",
    "fodp_nonempty_slide_count",
    "fodp_text_to_slide_ratio",
    "fodp_all_slides_have_text",
    "fodp_max_title_length",
    "fodp_average_text_per_slide",
    "fodp_shape_to_slide_ratio",
    "fodp_notes_to_slide_ratio",
    "fodp_image_to_slide_ratio",
    "fodp_has_empty_slides",
    "fodp_title_coverage",
    "fodp_is_single_slide",
    "fodp_notes_density",
    "fodp_has_titles",
    "fodp_min_shapes_per_slide",
    "fodp_has_multi_slide",
    "fodp_max_shapes_per_slide",
    "fodp_avg_notes_length",
    "fodp_shape_variance",
    "fodp_total_shape_count",
    "fodp_avg_shapes_per_slide",
    "fodp_empty_slide_count",
    "fodp_max_text_length",
    "fodp_text_length_variance",
    "fodp_slide_text_lengths",
    "fodp_avg_title_length",
    "fodp_is_text_heavy",
    "fodp_max_notes_length",
    "fodp_slide_count_is_one",
    "fodp_is_shape_heavy",
    "fodp_has_zero_shapes",
]

__version__ = "0.1.0.dev0"
__track__ = "python-foss"
__commercial_ready__ = False
__capability_level__ = "alpha-foss-preview"
