"""format-factory: FODP (Flat OpenDocument Presentation) FOSS Python track.

ODF 1.3 Part 3 spec. Acquisition Gates 1-3 PASSED; 4-7 delegated PASS (R20).
FOSS track — no commercial readiness implied. See: acquisition-packs/fodp/
"""
# ruff: noqa: F405  # __all__ references names from intentional star imports

from .fodp_codec import (
    FodpError,
    FodpParseError,
    load,
    get_page_count,
    extract_text,
    get_page_metadata,
    get_document_metadata,
    export_to_txt,
    export_to_csv,
    export_to_json,
    write_fodp,
)
from .presentation_document import *  # noqa: F401, F403
from .models import FodpDocument  # noqa: F401

__all__ = [
    "FodpError",
    "FodpParseError",
    "load",
    "get_page_count",
    "extract_text",
    "get_page_metadata",
    "get_document_metadata",
    "export_to_txt",
    "export_to_csv",
    "export_to_json",
    "write_fodp",
    "fodp_all_slides_have_text",
    "fodp_average_shapes_per_slide",
    "fodp_average_text_per_slide",
    "fodp_avg_notes_length",
    "fodp_avg_sentence_length",
    "fodp_avg_shapes_per_slide",
    "fodp_avg_text_length",
    "fodp_avg_title_length",
    "fodp_avg_title_words",
    "fodp_empty_slide_count",
    "fodp_has_empty_slides",
    "fodp_has_images",
    "fodp_has_multi_slide",
    "fodp_has_notes",
    "fodp_has_numeric_content",
    "fodp_has_titles",
    "fodp_has_zero_shapes",
    "fodp_image_count",
    "fodp_image_density",
    "fodp_image_to_slide_ratio",
    "fodp_is_shape_heavy",
    "fodp_is_single_slide",
    "fodp_is_text_heavy",
    "fodp_longest_slide_index",
    "fodp_master_page_count",
    "fodp_max_notes_length",
    "fodp_max_shapes_per_slide",
    "fodp_max_text_length",
    "fodp_max_text_per_slide",
    "fodp_max_title_length",
    "fodp_min_shapes_per_slide",
    "fodp_min_text_per_slide",
    "fodp_min_title_length",
    "fodp_nonempty_slide_count",
    "fodp_nonempty_slide_ratio",
    "fodp_notes_density",
    "fodp_notes_text",
    "fodp_notes_to_slide_ratio",
    "fodp_shape_count_variance",
    "fodp_shape_to_slide_ratio",
    "fodp_shape_variance",
    "fodp_shortest_slide_index",
    "fodp_slide_count",
    "fodp_slide_count_is_one",
    "fodp_slide_shape_counts",
    "fodp_slide_text_density",
    "fodp_slide_text_lengths",
    "fodp_slide_text_variance",
    "fodp_slide_titles",
    "fodp_text_length_variance",
    "fodp_text_per_slide",
    "fodp_text_to_slide_ratio",
    "fodp_title_coverage",
    "fodp_total_images",
    "fodp_total_notes_length",
    "fodp_total_shape_count",
    "fodp_total_text_chars",
    "fodp_total_text_length",
    "FodpDocument",
]

__version__ = "0.1.0.dev0"
__track__ = "python-foss"
__commercial_ready__ = False
__capability_level__ = "alpha-foss-preview"
