"""Exception coverage tests for xcf format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from xcf.exceptions import XcfWriteError
from xcf.exceptions import XcfError


def test_xcfwriteerror_is_raisable():
    with pytest.raises(XcfWriteError):
        raise XcfWriteError("test error message")


def test_xcfwriteerror_inherits_base():
    assert issubclass(XcfWriteError, XcfError)


def test_xcfwriteerror_message():
    exc = XcfWriteError("specific error")
    assert "specific error" in str(exc)
