"""Exception coverage tests for dif format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from dif.exceptions import DifParseError, DifWriteError
from dif.exceptions import DifError


def test_difparseerror_is_raisable():
    with pytest.raises(DifParseError):
        raise DifParseError("test error message")


def test_difparseerror_inherits_base():
    assert issubclass(DifParseError, DifError)


def test_difparseerror_message():
    exc = DifParseError("specific error")
    assert "specific error" in str(exc)


def test_difwriteerror_is_raisable():
    with pytest.raises(DifWriteError):
        raise DifWriteError("test error message")


def test_difwriteerror_inherits_base():
    assert issubclass(DifWriteError, DifError)


def test_difwriteerror_message():
    exc = DifWriteError("specific error")
    assert "specific error" in str(exc)
