"""
test_swarm_dif_probe_tc0287a024.py

Product proof test for taskcard TC-0287A024 (GAP-DIF-FOSS-PROBE_DIF-001).
Generated by Train G (limited product proof) in swarm sprint:
  format-factory-supervised-swarm-plan-completion-20260613-915cfd2

Covers all required test types per taskcard:
  - file_based_input
  - string_input (via path string)
  - empty_input
  - return_type_check
  - error_handling

Taskcard: .local/evidences/.../taskcards/TC-0287A024.json
Gap closed: GAP-DIF-FOSS-PROBE_DIF-001
"""
from __future__ import annotations

import sys
from pathlib import Path

_REPO = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(_REPO))

from src.python.dif.dif_parser import probe_dif

_SAMPLES = _REPO / "samples" / "by-format" / "dif"
_VALID = _SAMPLES / "valid"
_INVALID = _SAMPLES / "invalid"


# ---------------------------------------------------------------------------
# file_based_input tests
# ---------------------------------------------------------------------------

class TestProbeDifFileBasedInput:
    """probe_dif accepts file paths and returns structured dict."""

    def test_probe_valid_dif_returns_dict(self):
        result = probe_dif(_VALID / "minimal-2x2.dif")
        assert isinstance(result, dict)

    def test_probe_valid_dif_exists_true(self):
        result = probe_dif(_VALID / "minimal-2x2.dif")
        assert result["exists"] is True

    def test_probe_valid_dif_valid_header_true(self):
        result = probe_dif(_VALID / "minimal-2x2.dif")
        assert result.get("valid_header") is True

    def test_probe_single_cell_file(self):
        result = probe_dif(_VALID / "single-cell.dif")
        assert isinstance(result, dict)
        assert result.get("exists") is True

    def test_probe_numeric_row_file(self):
        result = probe_dif(_VALID / "numeric-row.dif")
        assert isinstance(result, dict)
        assert result.get("valid_header") is True


# ---------------------------------------------------------------------------
# string_input tests (path given as string)
# ---------------------------------------------------------------------------

class TestProbeDifStringInput:
    """probe_dif accepts string paths."""

    def test_probe_accepts_string_path(self):
        result = probe_dif(str(_VALID / "minimal-2x2.dif"))
        assert isinstance(result, dict)

    def test_probe_string_path_valid_header(self):
        result = probe_dif(str(_VALID / "minimal-2x2.dif"))
        assert result.get("valid_header") is True

    def test_probe_string_path_has_path_key(self):
        path_str = str(_VALID / "minimal-2x2.dif")
        result = probe_dif(path_str)
        assert "path" in result


# ---------------------------------------------------------------------------
# empty / missing input tests
# ---------------------------------------------------------------------------

class TestProbeDifEmptyInput:
    """probe_dif handles non-existent / bad paths gracefully."""

    def test_probe_nonexistent_returns_dict(self):
        result = probe_dif("/nonexistent/path/to/nowhere.dif")
        assert isinstance(result, dict)

    def test_probe_nonexistent_exists_false(self):
        result = probe_dif("/nonexistent/path/to/nowhere.dif")
        assert result.get("exists") is False


# ---------------------------------------------------------------------------
# return_type_check tests
# ---------------------------------------------------------------------------

class TestProbeDifReturnType:
    """probe_dif always returns a dict."""

    def test_return_type_is_dict_for_valid_file(self):
        result = probe_dif(_VALID / "minimal-2x2.dif")
        assert type(result) is dict

    def test_return_type_is_dict_for_missing_file(self):
        result = probe_dif("does_not_exist.dif")
        assert type(result) is dict

    def test_return_has_exists_key_always(self):
        result = probe_dif("does_not_exist.dif")
        assert "exists" in result


# ---------------------------------------------------------------------------
# error_handling tests
# ---------------------------------------------------------------------------

class TestProbeDifErrorHandling:
    """probe_dif handles error cases without raising exceptions."""

    def test_invalid_dif_does_not_raise(self):
        inv = _INVALID / "missing-table-header.dif"
        if inv.exists():
            result = probe_dif(inv)
            assert isinstance(result, dict)
        else:
            result = probe_dif("not_a_real_file.dif")
            assert isinstance(result, dict)

    def test_probe_handles_totally_nonexistent_path(self):
        try:
            result = probe_dif("/totally/nonexistent/path.dif")
            assert isinstance(result, dict)
        except Exception:
            assert False, "probe_dif must not raise for non-existent paths"
