"""Production OASIS UBL 2.3 lifecycle API."""

from __future__ import annotations

from pathlib import Path

from format_factory.core import BinarySource

from ._generated import (
    ARCHIVE_MEMBER_NAMES_SHA256,
    AUTHORITY_SHA256,
    ROOT_NAMES,
    ROOT_NAMESPACES,
    ROOT_NAMES_SHA256,
)
from .analytics import element_count, qname_histogram
from .codec import (
    SUPPORTED_PROFILE,
    LossReport,
    PreservationMode,
    canonicalize,
    check_preservation,
    dump,
    dumps,
    load,
    loads,
    probe,
    semantic_sha256,
)
from .document_types import (
    DocumentTypeCoverage,
    create_empty,
    detect_document_type,
    document_type_coverage,
    document_type_coverage_manifest,
    supported_document_types,
)
from .errors import (
    SchemaValidationUnavailable,
    UblError,
    UblParseError,
    UblValidationError,
    UblWriteError,
)
from .components import add_component, remove_component, replace_party, update_component
from .lines import add_line, move_line, remove_line, renumber_lines
from .migration import MigrationReport, migrate_document
from .model import (
    ROOT_CLASSES,
    AllowanceCharge,
    CodeList,
    CodeListRegistry,
    CodeListValidation,
    Contact,
    Country,
    CreditNoteLine,
    DespatchLine,
    DocumentIndex,
    DocumentReference,
    DocumentResponse,
    DuplicateId,
    ExternalReference,
    ExtensionAdapter,
    ExtensionAdapterRegistry,
    ExtensionDecodeResult,
    SignatureBackend,
    SignatureBackendRegistry,
    SignatureSigner,
    SignatureVerificationResult,
    SignatureVerifier,
    FinancialAccount,
    LineItem,
    OrderLine,
    Party,
    PartyIdentification,
    PartyName,
    PartyTaxScheme,
    PaymentMeans,
    PostalAddress,
    Price,
    QueryMatch,
    Response,
    TaxScheme,
    allowance_charge_of,
    business_role,
    contact_of,
    country_of,
    credit_note_line_of,
    despatch_line_of,
    document_reference_of,
    document_response_of,
    external_reference_of,
    financial_account_of,
    load_bundled_code_lists,
    official_code_list_registry,
    parse_genericode,
    line_item_of,
    order_line_of,
    party_identification_of,
    party_name_of,
    party_of,
    party_tax_scheme_of,
    payment_means_of,
    postal_address_of,
    price_of,
    response_of,
    tax_scheme_of,
    validate_code,
    decode_extension,
    sign_document,
    verify_signature,
    date_of,
    date_time_of,
    time_of,

    UblDate,
    UblDateTime,
    UblTime,

    InvoiceLine,
    Item,
    LegalMonetaryTotal,
    TaxSubtotal,
    TaxTotal,
    invoice_line_of,
    item_of,
    legal_monetary_total_of,
    reconcile_invoice,
    tax_subtotal_of,
    tax_total_of,

    amount_of,
    binary_object_of,
    code_of,
    find,
    find_all,
    find_all_qname,
    find_qname,
    identifier_of,
    local_name,
    quantity_of,
    to_node,

    Amount,
    BinaryObject,
    Code,
    Identifier,
    Quantity,
    Rounding,
    UblDocument,
    XmlNode,
    ubl_version_id,
)
from .security import UBL_DEFAULT_LIMITS
from .validation import (
    ProfileValidator,
    ProfileValidatorRegistry,
    bundled_maindoc_schema_paths,
    code_bearing_element_qnames,
    reorder_for_schema_order,
    schema_root_order,
    schema_validate,
    validate,
    validate_all,
    validate_profile,
)

__all__ = [
    "DocumentTypeCoverage",
    "create_empty",
    "detect_document_type",
    "document_type_coverage",
    "document_type_coverage_manifest",
    "supported_document_types",
    "CodeList",
    "CodeListRegistry",
    "CodeListValidation",
    "ExtensionAdapter",
    "ExtensionAdapterRegistry",
    "ExtensionDecodeResult",
    "decode_extension",
    "SignatureBackend",
    "SignatureBackendRegistry",
    "SignatureSigner",
    "SignatureVerificationResult",
    "SignatureVerifier",
    "sign_document",
    "verify_signature",
    "DocumentIndex",
    "DuplicateId",
    "ExternalReference",
    "QueryMatch",
    "business_role",
    "external_reference_of",
    "load_bundled_code_lists",
    "official_code_list_registry",
    "parse_genericode",
    "validate_code",
    "Contact",
    "Country",
    "Party",
    "PartyIdentification",
    "PartyName",
    "PartyTaxScheme",
    "PostalAddress",
    "TaxScheme",
    "contact_of",
    "country_of",
    "party_identification_of",
    "party_name_of",
    "party_of",
    "party_tax_scheme_of",
    "postal_address_of",
    "tax_scheme_of",
    "CreditNoteLine",
    "DespatchLine",
    "DocumentReference",
    "DocumentResponse",
    "LineItem",
    "OrderLine",
    "Response",
    "credit_note_line_of",
    "despatch_line_of",
    "document_reference_of",
    "document_response_of",
    "line_item_of",
    "order_line_of",
    "response_of",
    "time_of",
    "date_time_of",
    "date_of",
    "price_of",
    "payment_means_of",
    "allowance_charge_of",
    "financial_account_of",
    "Price",
    "PaymentMeans",
    "FinancialAccount",
    "AllowanceCharge",
    "UblTime",
    "UblDateTime",
    "UblDate",
    "tax_total_of",
    "tax_subtotal_of",
    "reconcile_invoice",
    "legal_monetary_total_of",
    "item_of",
    "invoice_line_of",
    "TaxTotal",
    "TaxSubtotal",
    "LegalMonetaryTotal",
    "Item",
    "InvoiceLine",
    "to_node",
    "quantity_of",
    "local_name",
    "identifier_of",
    "find_all",
    "find_all_qname",
    "find",
    "find_qname",
    "code_of",
    "binary_object_of",
    "amount_of",
    "Rounding",
    "Quantity",
    "Identifier",
    "Code",
    "BinaryObject",
    "Amount",
    "ARCHIVE_MEMBER_NAMES_SHA256",
    "AUTHORITY_SHA256",
    "LossReport",
    "PreservationMode",
    "ROOT_CLASSES",
    "ROOT_NAMES",
    "ROOT_NAMESPACES",
    "ROOT_NAMES_SHA256",
    "SUPPORTED_PROFILE",
    "SchemaValidationUnavailable",
    "UBL_DEFAULT_LIMITS",
    "UblDocument",
    "UblError",
    "UblParseError",
    "UblValidationError",
    "UblWriteError",
    "XmlNode",
    "bundled_maindoc_schema_paths",
    "canonicalize",
    "check_preservation",
    "code_bearing_element_qnames",
    "dump",
    "dumps",
    "ubl_version_id",
    "element_count",
    "load",
    "loads",
    "probe",
    "qname_histogram",
    "reorder_for_schema_order",
    "roundtrip",
    "schema_root_order",
    "schema_validate",
    "semantic_sha256",
    "ubl_installed_workflow",
    "validate",
    "validate_all",
    "validate_profile",
    "ProfileValidator",
    "ProfileValidatorRegistry",
    "add_line",
    "move_line",
    "remove_line",
    "renumber_lines",
    "replace_party",
    "update_component",
    "add_component",
    "remove_component",
    "migrate_document",
    "MigrationReport",
]

__version__ = "0.2.0.dev0"


def roundtrip(source: BinarySource, destination: str | Path) -> UblDocument:
    document = load(source)
    dump(document, destination)
    return load(destination)


def ubl_installed_workflow(source: BinarySource) -> dict[str, object]:
    document = load(source)
    return {
        "element_count": element_count(document),
        "format": "ubl",
        "loaded": True,
        "profile": SUPPORTED_PROFILE,
        "root": document.root_name,
    }
