"""
format-factory: FODG (Flat OpenDocument Graphics) FOSS Python track.

Minimal FOSS implementation for .fodg format support.
ODF 1.3 Part 3 specification — OASIS Royalty-Free Category 1.
Acquisition Gates 1-3 PASSED. Gates 4-7 delegated PASS (R20).

FOSS track only — no commercial readiness implied.
"""

from .fodg_codec import (
    FodgError,
    FodgParseError,
    load,
    get_page_count,
    get_shape_count,
    extract_text,
    get_page_metadata,
    create_fodg,
    write_fodg,
    get_shapes,
    get_page_by_name,
    add_page,
    get_text_shapes,
    remove_page,
    rename_page,
    get_all_text,
    count_shapes,
    export_to_json,
    duplicate_page,
    get_page_index,
    clear_page,
    swap_pages,
    page_names,
    has_page,
    probe_fodg,
    export_to_txt,
    export_to_csv,
    roundtrip,
    find_text,
    get_page_text,
    total_text_length,
    find_shapes_by_text_pattern,
    export_page_to_json,
    fodg_page_shape_count,
    fodg_avg_shapes_per_page,
    fodg_has_empty_pages,
    fodg_page_count,
    fodg_all_pages_have_shapes,
    fodg_total_shape_count,
    fodg_text_shape_count,
    fodg_text_to_shape_ratio,
    fodg_max_shapes_per_page,
    fodg_min_shapes_per_page,
    fodg_shape_density,
    fodg_empty_page_count,
    fodg_is_single_page,
    fodg_total_text_length,
    fodg_has_text,
    fodg_is_empty_document,
    fodg_non_text_shape_count,
    fodg_avg_text_per_page,
    fodg_has_multiple_pages,
    fodg_shape_to_page_variance,
    fodg_max_text_per_page,
    fodg_text_per_shape,
    fodg_nonempty_page_count,
    fodg_text_density,
    fodg_is_multi_page,
    fodg_shape_count_variance,
    fodg_is_text_only,
    fodg_avg_shapes_per_nonempty_page,
    fodg_has_single_shape,
    fodg_page_text_variance,
    fodg_total_text_chars,
    fodg_avg_text_per_shape,
    fodg_min_text_per_page,
)

__all__ = [
    "FodgError",
    "FodgParseError",
    "load",
    "get_page_count",
    "get_shape_count",
    "extract_text",
    "get_page_metadata",
    "create_fodg",
    "write_fodg",
    "get_shapes",
    "get_page_by_name",
    "add_page",
    "get_text_shapes",
    "remove_page",
    "rename_page",
    "get_all_text",
    "count_shapes",
    "export_to_json",
    "duplicate_page",
    "get_page_index",
    "clear_page",
    "swap_pages",
    "page_names",
    "has_page",
    "probe_fodg",
    "export_to_txt",
    "export_to_csv",
    "roundtrip",
    "find_text",
    "get_page_text",
    "total_text_length",
    "find_shapes_by_text_pattern",
    "export_page_to_json",
    "fodg_page_shape_count",
    "fodg_avg_shapes_per_page",
    "fodg_has_empty_pages",
    "fodg_total_shape_count",
    "fodg_text_shape_count",
    "fodg_page_count",
    "fodg_all_pages_have_shapes",
    "fodg_text_to_shape_ratio",
    "fodg_max_shapes_per_page",
    "fodg_min_shapes_per_page",
    "fodg_shape_density",
    "fodg_empty_page_count",
    "fodg_is_single_page",
    "fodg_total_text_length",
    "fodg_has_text",
    "fodg_is_empty_document",
    "fodg_non_text_shape_count",
    "fodg_avg_text_per_page",
    "fodg_has_multiple_pages",
    "fodg_shape_to_page_variance",
    "fodg_max_text_per_page",
    "fodg_text_per_shape",
    "fodg_nonempty_page_count",
    "fodg_text_density",
    "fodg_is_multi_page",
    "fodg_shape_count_variance",
    "fodg_is_text_only",
    "fodg_avg_shapes_per_nonempty_page",
    "fodg_has_single_shape",
    "fodg_page_text_variance",
    "fodg_total_text_chars",
    "fodg_avg_text_per_shape",
    "fodg_min_text_per_page",
]

__version__ = "0.1.0.dev0"
__track__ = "python-foss"
__commercial_ready__ = False
__capability_level__ = "alpha-foss-preview"
