"""Exception coverage tests for ppm format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from ppm.exceptions import PpmParseError, PpmWriteError
from ppm.exceptions import PpmError


def test_ppmparseerror_is_raisable():
    with pytest.raises(PpmParseError):
        raise PpmParseError("test error message")


def test_ppmparseerror_inherits_base():
    assert issubclass(PpmParseError, PpmError)


def test_ppmparseerror_message():
    exc = PpmParseError("specific error")
    assert "specific error" in str(exc)


def test_ppmwriteerror_is_raisable():
    with pytest.raises(PpmWriteError):
        raise PpmWriteError("test error message")


def test_ppmwriteerror_inherits_base():
    assert issubclass(PpmWriteError, PpmError)


def test_ppmwriteerror_message():
    exc = PpmWriteError("specific error")
    assert "specific error" in str(exc)
