"""
format-factory-qoi — QOI (Quite OK Image) parser prototype.

Gate 4 prototype. FOSS track. No third-party dependencies.
Acquisition gates 1-4 passed. Implementation authorized: R27.
commercial_product_ready: false
"""

from .qoi_parser import (
    parse_qoi,
    parse_qoi_strict,
    probe_qoi,
    get_capabilities,
    qoi_dimensions,
    qoi_pixel_count,
    qoi_unique_color_count,
    qoi_channel_count,
    qoi_is_opaque,
    qoi_has_alpha,
    qoi_average_brightness,
    qoi_red_channel_average,
    qoi_dominant_channel,
    qoi_min_max_brightness,
    qoi_green_channel_average,
    qoi_blue_channel_average,
    qoi_is_grayscale,
    qoi_brightness_variance,
    qoi_total_brightness,
    qoi_avg_rgb_value,
    qoi_red_dominance_ratio,
    qoi_aspect_ratio,
    qoi_color_concentration,
    qoi_avg_rgb,
    qoi_red_dominant,
    qoi_blue_dominant,
    qoi_green_dominant,
    qoi_row_count,
    qoi_is_square,
    qoi_perimeter,
    qoi_color_variance,
    qoi_dimension_ratio,
    qoi_is_landscape,
    qoi_is_portrait,
    qoi_max_dimension,
    qoi_has_any_black,
    qoi_max_channel_average,
    qoi_min_channel_average,
    qoi_has_any_white,
    qoi_channel_range,
    qoi_diagonal,
    qoi_min_dimension,
    qoi_area,
    qoi_brightness_range,
    qoi_is_small,
    qoi_megapixels,
    qoi_channel_balance,
    qoi_is_tall,
    qoi_channel_entropy,
    qoi_is_monochrome,
    qoi_red_ratio,
    qoi_green_ratio,
    qoi_blue_ratio,
    qoi_pixel_density,
    qoi_is_dark,
    QoiImage,
)
from .qoi_encoder import (
    encode_qoi,
    encode_qoi_to_file,
    get_encoder_capabilities,
)

__version__ = "0.1.0.dev0"
__track__ = "python-foss"
__commercial_ready__ = False
__capability_level__ = "alpha-foss-preview"

__all__ = [
    "parse_qoi",
    "parse_qoi_strict",
    "probe_qoi",
    "get_capabilities",
    "qoi_dimensions",
    "qoi_pixel_count",
    "qoi_unique_color_count",
    "qoi_channel_count",
    "qoi_is_opaque",
    "qoi_has_alpha",
    "qoi_average_brightness",
    "qoi_red_channel_average",
    "qoi_dominant_channel",
    "qoi_min_max_brightness",
    "qoi_green_channel_average",
    "qoi_blue_channel_average",
    "qoi_is_grayscale",
    "qoi_brightness_variance",
    "qoi_total_brightness",
    "qoi_avg_rgb_value",
    "qoi_red_dominance_ratio",
    "qoi_aspect_ratio",
    "qoi_color_concentration",
    "qoi_avg_rgb",
    "qoi_red_dominant",
    "qoi_blue_dominant",
    "qoi_green_dominant",
    "qoi_row_count",
    "qoi_is_square",
    "qoi_perimeter",
    "qoi_color_variance",
    "qoi_dimension_ratio",
    "qoi_is_landscape",
    "qoi_is_portrait",
    "qoi_max_dimension",
    "qoi_has_any_black",
    "qoi_max_channel_average",
    "qoi_min_channel_average",
    "qoi_has_any_white",
    "qoi_channel_range",
    "qoi_diagonal",
    "qoi_min_dimension",
    "qoi_area",
    "qoi_brightness_range",
    "qoi_is_small",
    "qoi_megapixels",
    "qoi_channel_balance",
    "qoi_is_tall",
    "qoi_channel_entropy",
    "qoi_is_monochrome",
    "qoi_red_ratio",
    "qoi_green_ratio",
    "qoi_blue_ratio",
    "qoi_pixel_density",
    "qoi_is_dark",
    "QoiImage",
    "encode_qoi",
    "encode_qoi_to_file",
    "get_encoder_capabilities",
]
