"""Exception coverage tests for sylk format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from sylk.exceptions import SylkWriteError
from sylk.exceptions import SylkError


def test_sylkwriteerror_is_raisable():
    with pytest.raises(SylkWriteError):
        raise SylkWriteError("test error message")


def test_sylkwriteerror_inherits_base():
    assert issubclass(SylkWriteError, SylkError)


def test_sylkwriteerror_message():
    exc = SylkWriteError("specific error")
    assert "specific error" in str(exc)
