"""TC-C3-003: Tests verifying advisory_only=False for machine_executable capability actions.

Gate C5: action queue executability — confirms the capability_map_generator correctly sets
advisory_only=False for ACT-UPDATE-POC-TARGETS and top-level queue when machine_executable items exist.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
ACTION_QUEUE = REPO_ROOT / "reports" / "capability-layer" / "action-queue.json"
GENERATOR = REPO_ROOT / "tools" / "capability_layer" / "capability_map_generator.py"


@pytest.fixture(scope="module")
def action_queue() -> dict:
    """Load the current action-queue.json (regenerated by capability_map_generator)."""
    assert ACTION_QUEUE.exists(), f"action-queue.json not found at {ACTION_QUEUE}"
    return json.loads(ACTION_QUEUE.read_text(encoding="utf-8"))


class TestActionQueueAdvisoryOnly:
    """TC-C3-003: advisory_only flag is correctly set per machine_executable."""

    def test_action_queue_file_exists(self):
        """action-queue.json must exist at expected path."""
        assert ACTION_QUEUE.exists()

    def test_top_level_advisory_only_is_false(self, action_queue):
        """Top-level advisory_only must be False when any machine_executable action exists."""
        assert action_queue.get("advisory_only") is False, (
            f"Expected top-level advisory_only=False, got {action_queue.get('advisory_only')}"
        )

    def test_acts_update_poc_targets_exists(self, action_queue):
        """ACT-UPDATE-POC-TARGETS must be present in actions list."""
        ids = [a.get("action_id") for a in action_queue.get("actions", [])]
        assert "ACT-UPDATE-POC-TARGETS" in ids

    def test_acts_update_poc_targets_advisory_only_false(self, action_queue):
        """ACT-UPDATE-POC-TARGETS must have advisory_only=False (TC-C3-001 fix)."""
        for action in action_queue.get("actions", []):
            if action.get("action_id") == "ACT-UPDATE-POC-TARGETS":
                assert action.get("advisory_only") is False, (
                    f"Expected advisory_only=False for ACT-UPDATE-POC-TARGETS, "
                    f"got {action.get('advisory_only')}"
                )
                return
        pytest.fail("ACT-UPDATE-POC-TARGETS not found in actions")

    def test_acts_update_poc_targets_machine_executable_true(self, action_queue):
        """ACT-UPDATE-POC-TARGETS must be machine_executable."""
        for action in action_queue.get("actions", []):
            if action.get("action_id") == "ACT-UPDATE-POC-TARGETS":
                assert action.get("machine_executable") is True
                return
        pytest.fail("ACT-UPDATE-POC-TARGETS not found in actions")

    def test_acts_update_poc_targets_safe_for_autonomous(self, action_queue):
        """ACT-UPDATE-POC-TARGETS must be safe_for_autonomous."""
        for action in action_queue.get("actions", []):
            if action.get("action_id") == "ACT-UPDATE-POC-TARGETS":
                assert action.get("safe_for_autonomous") is True
                return
        pytest.fail("ACT-UPDATE-POC-TARGETS not found in actions")

    def test_machine_executable_items_are_not_advisory(self, action_queue):
        """All machine_executable=True actions must have advisory_only=False."""
        for action in action_queue.get("actions", []):
            if action.get("machine_executable") is True:
                assert action.get("advisory_only") is False, (
                    f"Action {action.get('action_id')} is machine_executable=True "
                    f"but advisory_only={action.get('advisory_only')}"
                )

    def test_action_queue_has_required_schema_fields(self, action_queue):
        """action-queue.json must have required schema fields."""
        required = ["schema_version", "advisory_only", "total_actions", "actions"]
        for field in required:
            assert field in action_queue, f"Missing field: {field}"

    def test_total_actions_matches_actions_list(self, action_queue):
        """total_actions must match len(actions)."""
        assert action_queue.get("total_actions") == len(action_queue.get("actions", []))

    def test_generator_produces_correct_advisory_only(self):
        """Running the generator must produce advisory_only=False in action-queue.json.

        Skip if generator times out (it processes 14,432 SAL facts and can be slow).
        The advisory_only value in action-queue.json is verified by the other tests.
        """
        try:
            result = subprocess.run(
                [sys.executable, str(GENERATOR)],
                capture_output=True, text=True, timeout=180,
                cwd=str(REPO_ROOT),
            )
        except subprocess.TimeoutExpired:
            pytest.skip("Generator timed out after 180s — advisory_only verified by file tests")
        assert result.returncode == 0, f"Generator failed: {result.stderr[:500]}"
        queue = json.loads(ACTION_QUEUE.read_text(encoding="utf-8"))
        assert queue.get("advisory_only") is False, (
            "Generator produced advisory_only=True at top level; TC-C3-001 fix may not persist"
        )
