"""Exception coverage tests for abw format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from abw.exceptions import AbwWriteError
from abw.exceptions import AbwError


def test_abwwriteerror_is_raisable():
    with pytest.raises(AbwWriteError):
        raise AbwWriteError("test error message")


def test_abwwriteerror_inherits_base():
    assert issubclass(AbwWriteError, AbwError)


def test_abwwriteerror_message():
    exc = AbwWriteError("specific error")
    assert "specific error" in str(exc)
