"""
format-factory-tsv — Minimal FOSS TSV parser (Gate 4 prototype).

Tab-separated values parser using Python stdlib csv module with tab delimiter.

publication_authorized: false
commercial_product_ready: false
capability_level: alpha-foss-preview
track: python-foss

Sprint: FORMAT-FACTORY-R55-MULTI-MEGA-TRAIN-PRODUCT-RC-PHASE6-ACQUISITION-AI-VALIDATOR-001
"""

from .tsv_parser import (
    parse_tsv,
    parse_tsv_strict,
    probe_tsv,
    get_capabilities,
    write_tsv,
    load_tsv,
    get_headers,
    get_column,
    write_tsv_strict,
    get_row,
    validate_headers,
    count_rows,
    to_csv,
    deduplicate_rows,
    get_row_by_key,
    merge_tsv,
    min_column_tsv,
    sample_rows,
    sum_column_tsv,
    sort_rows,
    drop_column,
    add_column,
    rename_column,
    get_column_values,
    max_column_tsv,
    column_count,
    filter_rows,
    append_row,
    roundtrip,
    average_column_tsv,
    median_column_tsv,
    std_column_tsv,
    TsvError,
    TsvInputError,
    TsvSizeError,
    TsvParseError,
    append_rows,
    find_rows_containing,
    unique_column_values,
    tsv_nonempty_cell_count,
    tsv_numeric_cell_count,
    tsv_empty_row_count,
    tsv_max_cell_length,
    tsv_row_count,
    tsv_column_count,
    count_distinct_values,
    tsv_has_header,
    tsv_max_field_length,
    tsv_duplicate_row_count,
    tsv_total_cell_count,
    tsv_average_cell_length,
    tsv_numeric_density,
    tsv_unique_row_count,
    tsv_header_count,
)

__version__ = "0.1.0"
__track__ = "python-foss"
__commercial_ready__ = False
__capability_level__ = "alpha-foss-preview"

__all__ = [
    "parse_tsv",
    "parse_tsv_strict",
    "probe_tsv",
    "get_capabilities",
    "write_tsv",
    "load_tsv",
    "get_headers",
    "get_column",
    "write_tsv_strict",
    "get_row",
    "validate_headers",
    "count_rows",
    "to_csv",
    "deduplicate_rows",
    "get_row_by_key",
    "merge_tsv",
    "min_column_tsv",
    "sample_rows",
    "sum_column_tsv",
    "sort_rows",
    "drop_column",
    "add_column",
    "rename_column",
    "get_column_values",
    "max_column_tsv",
    "column_count",
    "filter_rows",
    "append_row",
    "roundtrip",
    "average_column_tsv",
    "median_column_tsv",
    "std_column_tsv",
    "TsvError",
    "TsvInputError",
    "TsvSizeError",
    "TsvParseError",
    "append_rows",
    "find_rows_containing",
    "unique_column_values",
    "tsv_nonempty_cell_count",
    "tsv_numeric_cell_count",
    "tsv_empty_row_count",
    "tsv_max_cell_length",
    "tsv_row_count",
    "tsv_column_count",
    "count_distinct_values",
    "tsv_has_header",
    "tsv_max_field_length",
    "tsv_duplicate_row_count",
    "tsv_total_cell_count",
    "tsv_average_cell_length",
    "tsv_numeric_density",
    "tsv_unique_row_count",
    "tsv_header_count",
]
