[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "format-factory-tsv"
version = "0.1.0.dev0"
description = "Format Factory TSV (Tab-Separated Values) FOSS Python parser and writer"
license = {text = "Apache-2.0"}
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = [".."]
include = ["tsv*"]
