"""
format-factory-xcf — XCF (GIMP Native Image Format) parser prototype.

Gate 4 prototype. FOSS track. No third-party dependencies.
Acquisition gates 1-3 passed. Implementation authorized: R28.
commercial_product_ready: false
"""

from .xcf_parser import (
    parse_xcf,
    parse_xcf_strict,
    probe_xcf,
    get_capabilities,
    xcf_layer_count,
    xcf_image_dimensions,
    xcf_version,
    xcf_image_type_name,
    xcf_pixel_count,
    xcf_file_size,
    xcf_is_rgb,
    xcf_is_grayscale,
    xcf_is_indexed,
    xcf_aspect_ratio,
    xcf_is_square,
    xcf_width,
    xcf_megapixels,
    xcf_has_alpha,
    xcf_canvas_size_bytes,
    xcf_height,
    xcf_layer_to_canvas_ratio,
    xcf_total_layers_area,
    xcf_average_layer_size,
    xcf_is_landscape,
    xcf_is_portrait,
    xcf_layer_count_per_megapixel,
    xcf_compression_ratio,
    xcf_layers_per_dimension,
    xcf_perimeter,
    xcf_diagonal,
    xcf_dimension_ratio,
    xcf_layer_density,
    xcf_total_layer_pixels,
    xcf_is_single_layer,
    xcf_canvas_area,
    xcf_max_layer_dimension,
    xcf_min_layer_dimension,
    xcf_has_multiple_layers,
    xcf_max_dimension,
    xcf_min_dimension,
    xcf_layer_to_pixel_ratio,
    xcf_is_tall,
    xcf_column_count,
    xcf_is_wide,
    xcf_pixel_density,
    xcf_layer_area_variance,
    xcf_row_count,
    xcf_pixel_count_per_layer,
    xcf_is_multi_pixel,
    xcf_file_bytes_per_layer,
    xcf_average_dimension,
    XcfError,
    XcfInvalidMagicError,
    XcfInvalidHeaderError,
    XcfSizeError,
    XcfParseError,
    XcfImage,
)

__version__ = "0.1.0.dev0"
__track__ = "python-foss"
__commercial_ready__ = False
__capability_level__ = "alpha-foss-preview"

__all__ = [
    "parse_xcf",
    "parse_xcf_strict",
    "probe_xcf",
    "get_capabilities",
    "xcf_layer_count",
    "xcf_image_dimensions",
    "xcf_version",
    "xcf_image_type_name",
    "xcf_pixel_count",
    "xcf_file_size",
    "xcf_is_rgb",
    "xcf_is_grayscale",
    "xcf_is_indexed",
    "xcf_aspect_ratio",
    "xcf_is_square",
    "xcf_width",
    "xcf_megapixels",
    "xcf_has_alpha",
    "xcf_canvas_size_bytes",
    "xcf_height",
    "xcf_layer_to_canvas_ratio",
    "xcf_total_layers_area",
    "xcf_average_layer_size",
    "xcf_is_landscape",
    "xcf_is_portrait",
    "xcf_layer_count_per_megapixel",
    "xcf_compression_ratio",
    "xcf_layers_per_dimension",
    "xcf_perimeter",
    "xcf_diagonal",
    "xcf_dimension_ratio",
    "xcf_layer_density",
    "xcf_total_layer_pixels",
    "xcf_is_single_layer",
    "xcf_canvas_area",
    "xcf_max_layer_dimension",
    "xcf_min_layer_dimension",
    "xcf_has_multiple_layers",
    "xcf_max_dimension",
    "xcf_min_dimension",
    "xcf_layer_to_pixel_ratio",
    "xcf_is_tall",
    "xcf_column_count",
    "xcf_is_wide",
    "xcf_pixel_density",
    "xcf_layer_area_variance",
    "xcf_row_count",
    "xcf_pixel_count_per_layer",
    "xcf_is_multi_pixel",
    "xcf_file_bytes_per_layer",
    "xcf_average_dimension",
    "XcfError",
    "XcfInvalidMagicError",
    "XcfInvalidHeaderError",
    "XcfSizeError",
    "XcfParseError",
    "XcfImage",
]
