"""Exception coverage tests for ods format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from ods.exceptions import OdsParseError, OdsWriteError
from ods.exceptions import OdsError


def test_odsparseerror_is_raisable():
    with pytest.raises(OdsParseError):
        raise OdsParseError("test error message")


def test_odsparseerror_inherits_base():
    assert issubclass(OdsParseError, OdsError)


def test_odsparseerror_message():
    exc = OdsParseError("specific error")
    assert "specific error" in str(exc)


def test_odswriteerror_is_raisable():
    with pytest.raises(OdsWriteError):
        raise OdsWriteError("test error message")


def test_odswriteerror_inherits_base():
    assert issubclass(OdsWriteError, OdsError)


def test_odswriteerror_message():
    exc = OdsWriteError("specific error")
    assert "specific error" in str(exc)
