"""
format-factory: ABW (AbiWord) FOSS Python track.

Minimal FOSS implementation for .abw format support.
AWML 1.0 plain XML format.
Acquisition Gates 1-7 PASSED.

FOSS track only — no commercial readiness implied.
"""

from .abw_codec import (
    AbwError,
    AbwParseError,
    load,
    get_section_count,
    get_paragraph_count,
    extract_text,
    create_abw,
    write_abw,
    probe_abw,
    export_to_txt,
    export_to_html,
    get_metadata,
    export_to_json,
    edit_paragraph,
    export_to_csv,
    get_paragraph,
    search_paragraph,
    get_word_count,
    search_replace_paragraph,
    merge_abw,
    word_frequency,
    truncate_paragraphs,
    get_unique_words,
    append_paragraph,
    split_paragraphs,
    get_char_count,
    join_paragraphs,
    replace_in_paragraphs,
    export_to_markdown,
    get_paragraph_at,
    paragraph_lengths,
    reverse_paragraphs,
    word_wrap,
    has_paragraph,
    first_paragraph,
    last_paragraph,
    count_words,
    paragraph_at,
    text_stats,
    export_to_plain_text,
    search_text,
    get_words,
    longest_paragraph,
    is_empty,
    average_paragraph_length,
    shortest_paragraph,
    contains_text,
    count_paragraphs_matching,
    abw_sentence_count,
    abw_longest_word,
    abw_total_char_count,
    abw_empty_paragraph_count,
    abw_nonempty_paragraph_count,
)

__all__ = [
    "AbwError",
    "AbwParseError",
    "load",
    "get_section_count",
    "get_paragraph_count",
    "extract_text",
    "create_abw",
    "write_abw",
    "probe_abw",
    "export_to_txt",
    "export_to_html",
    "get_metadata",
    "export_to_json",
    "edit_paragraph",
    "export_to_csv",
    "get_paragraph",
    "search_paragraph",
    "get_word_count",
    "search_replace_paragraph",
    "merge_abw",
    "word_frequency",
    "truncate_paragraphs",
    "get_unique_words",
    "append_paragraph",
    "split_paragraphs",
    "get_char_count",
    "join_paragraphs",
    "replace_in_paragraphs",
    "export_to_markdown",
    "get_paragraph_at",
    "paragraph_lengths",
    "reverse_paragraphs",
    "word_wrap",
    "has_paragraph",
    "first_paragraph",
    "last_paragraph",
    "count_words",
    "paragraph_at",
    "text_stats",
    "export_to_plain_text",
    "search_text",
    "get_words",
    "longest_paragraph",
    "is_empty",
    "average_paragraph_length",
    "shortest_paragraph",
    "contains_text",
    "count_paragraphs_matching",
    "abw_sentence_count",
    "abw_longest_word",
    "abw_total_char_count",
    "abw_empty_paragraph_count",
    "abw_nonempty_paragraph_count",
]

__version__ = "0.1.0.dev0"
__track__ = "python-foss"
__commercial_ready__ = False
__capability_level__ = "alpha-foss-preview"
