"""
format-factory-odt — ODT (OpenDocument Text) parser prototype.

Gate 4 prototype. FOSS track. No third-party dependencies.
Acquisition gates 1-4 passed. Implementation authorized: R27.
commercial_product_ready: false
"""

from .odt_parser import (
    parse_odt,
    parse_odt_strict,
    probe_odt,
    get_capabilities,
    odt_word_count,
    odt_heading_count,
    odt_paragraph_count,
    odt_char_count,
    odt_list_count,
    odt_table_count,
    odt_sentence_count,
    odt_average_word_length,
    odt_unique_word_count,
    odt_longest_paragraph,
    odt_has_tables,
    odt_avg_paragraph_length,
    odt_words_per_sentence,
    odt_vocabulary_richness,
    odt_chars_per_word,
    odt_has_headings,
    odt_max_paragraph_length,
    odt_min_paragraph_length,
    odt_heading_to_paragraph_ratio,
    odt_total_elements,
    odt_is_empty,
    odt_shortest_word,
    odt_paragraph_density,
    odt_heading_density,
    odt_longest_word,
    odt_list_to_paragraph_ratio,
    odt_has_lists,
    odt_has_unicode,
    odt_max_words_per_paragraph,
    odt_min_words_per_paragraph,
    odt_word_density,
    odt_sentence_density,
    odt_table_density,
    odt_nonempty_paragraph_count,
    odt_char_density,
    odt_empty_paragraph_count,
    odt_words_per_heading,
    odt_avg_words_per_sentence,
    odt_shortest_paragraph_length,
    odt_max_paragraph_length,
    odt_avg_chars_per_paragraph,
    odt_paragraph_variance,
    odt_is_single_paragraph,
    odt_list_density,
    odt_heading_per_paragraph,
    odt_is_multi_paragraph,
    odt_whitespace_ratio,
    odt_avg_chars_per_word,
    odt_is_content_rich,
    OdtError,
    OdtInvalidContainerError,
    OdtSizeError,
    OdtParagraph,
    OdtHeading,
    OdtListItem,
    OdtDocument,
)

__version__ = "0.1.0.dev0"
__track__ = "python-foss"
__commercial_ready__ = False
__capability_level__ = "alpha-foss-preview"

__all__ = [
    "parse_odt",
    "parse_odt_strict",
    "probe_odt",
    "get_capabilities",
    "odt_word_count",
    "odt_heading_count",
    "odt_paragraph_count",
    "odt_char_count",
    "odt_list_count",
    "odt_table_count",
    "odt_sentence_count",
    "odt_average_word_length",
    "odt_unique_word_count",
    "odt_longest_paragraph",
    "odt_has_tables",
    "odt_avg_paragraph_length",
    "odt_words_per_sentence",
    "odt_vocabulary_richness",
    "odt_chars_per_word",
    "odt_has_headings",
    "odt_max_paragraph_length",
    "odt_min_paragraph_length",
    "odt_heading_to_paragraph_ratio",
    "odt_total_elements",
    "odt_is_empty",
    "odt_shortest_word",
    "odt_paragraph_density",
    "odt_heading_density",
    "odt_longest_word",
    "odt_list_to_paragraph_ratio",
    "odt_has_lists",
    "odt_has_unicode",
    "odt_max_words_per_paragraph",
    "odt_min_words_per_paragraph",
    "odt_word_density",
    "odt_sentence_density",
    "odt_table_density",
    "odt_nonempty_paragraph_count",
    "odt_char_density",
    "odt_empty_paragraph_count",
    "odt_words_per_heading",
    "odt_avg_words_per_sentence",
    "odt_shortest_paragraph_length",
    "odt_max_paragraph_length",
    "odt_avg_chars_per_paragraph",
    "odt_paragraph_variance",
    "odt_is_single_paragraph",
    "odt_list_density",
    "odt_heading_per_paragraph",
    "odt_is_multi_paragraph",
    "odt_whitespace_ratio",
    "odt_avg_chars_per_word",
    "odt_is_content_rich",
    "OdtError",
    "OdtInvalidContainerError",
    "OdtSizeError",
    "OdtParagraph",
    "OdtHeading",
    "OdtListItem",
    "OdtDocument",
]
