"""Exception coverage tests for pbm format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from pbm.exceptions import PbmParseError, PbmWriteError
from pbm.exceptions import PbmError


def test_pbmparseerror_is_raisable():
    with pytest.raises(PbmParseError):
        raise PbmParseError("test error message")


def test_pbmparseerror_inherits_base():
    assert issubclass(PbmParseError, PbmError)


def test_pbmparseerror_message():
    exc = PbmParseError("specific error")
    assert "specific error" in str(exc)


def test_pbmwriteerror_is_raisable():
    with pytest.raises(PbmWriteError):
        raise PbmWriteError("test error message")


def test_pbmwriteerror_inherits_base():
    assert issubclass(PbmWriteError, PbmError)


def test_pbmwriteerror_message():
    exc = PbmWriteError("specific error")
    assert "specific error" in str(exc)
