"""Public UBL model types."""

from .document import UblDocument, XmlNode, ubl_version_id
from .root_types import ROOT_CLASSES
from .aggregates import (
    InvoiceLine,
    Item,
    LegalMonetaryTotal,
    TaxSubtotal,
    TaxTotal,
    invoice_line_of,
    item_of,
    legal_monetary_total_of,
    reconcile_invoice,
    tax_subtotal_of,
    tax_total_of,
)
from .charges import (
    AllowanceCharge,
    FinancialAccount,
    PaymentMeans,
    Price,
    allowance_charge_of,
    financial_account_of,
    payment_means_of,
    price_of,
)
from .codelist import CodeList, CodeListRegistry, CodeListValidation, validate_code
from .lines import (
    CreditNoteLine,
    DespatchLine,
    DocumentReference,
    DocumentResponse,
    LineItem,
    OrderLine,
    Response,
    credit_note_line_of,
    despatch_line_of,
    document_reference_of,
    document_response_of,
    line_item_of,
    order_line_of,
    response_of,
)
from .party import (
    Contact,
    Country,
    Party,
    PartyIdentification,
    PartyName,
    PartyTaxScheme,
    PostalAddress,
    TaxScheme,
    contact_of,
    country_of,
    party_identification_of,
    party_name_of,
    party_of,
    party_tax_scheme_of,
    postal_address_of,
    tax_scheme_of,
)
from .query import DocumentIndex, DuplicateId, Path, QueryMatch, business_role
from .reference import ExternalReference, external_reference_of
from .temporal import UblDate, UblDateTime, UblTime
from .typed import (
    date_of,
    date_time_of,
    time_of,
    amount_of,
    binary_object_of,
    code_of,
    find,
    find_all,
    identifier_of,
    local_name,
    quantity_of,
    to_node,
)
from .values import (
    Amount,
    BinaryObject,
    Code,
    Identifier,
    Quantity,
    Rounding,
)


def document_from_root(
    root: XmlNode,
    *,
    source_sha256: str | None = None,
    signed_content_sha256: str | None = None,
) -> UblDocument:
    root_name = root.qname.rsplit("}", 1)[-1]
    document_type = ROOT_CLASSES.get(root_name)
    if document_type is None:
        raise ValueError(f"unsupported UBL document root: {root_name}")
    return document_type(
        root,
        source_sha256=source_sha256,
        signed_content_sha256=signed_content_sha256,
        detected_version=ubl_version_id(root),
    )

__all__ = [
    "CodeList",
    "CodeListRegistry",
    "CodeListValidation",
    "DocumentIndex",
    "DuplicateId",
    "ExternalReference",
    "Path",
    "QueryMatch",
    "business_role",
    "external_reference_of",
    "validate_code",
    "Contact",
    "Country",
    "Party",
    "PartyIdentification",
    "PartyName",
    "PartyTaxScheme",
    "PostalAddress",
    "TaxScheme",
    "contact_of",
    "country_of",
    "party_identification_of",
    "party_name_of",
    "party_of",
    "party_tax_scheme_of",
    "postal_address_of",
    "tax_scheme_of",
    "CreditNoteLine",
    "DespatchLine",
    "DocumentReference",
    "DocumentResponse",
    "LineItem",
    "OrderLine",
    "Response",
    "credit_note_line_of",
    "despatch_line_of",
    "document_reference_of",
    "document_response_of",
    "line_item_of",
    "order_line_of",
    "response_of",
    "time_of",
    "date_time_of",
    "date_of",
    "price_of",
    "payment_means_of",
    "allowance_charge_of",
    "financial_account_of",
    "Price",
    "PaymentMeans",
    "FinancialAccount",
    "AllowanceCharge",
    "UblTime",
    "UblDateTime",
    "UblDate",
    "tax_total_of",
    "tax_subtotal_of",
    "reconcile_invoice",
    "legal_monetary_total_of",
    "item_of",
    "invoice_line_of",
    "TaxTotal",
    "TaxSubtotal",
    "LegalMonetaryTotal",
    "Item",
    "InvoiceLine",
    "to_node",
    "quantity_of",
    "local_name",
    "identifier_of",
    "find_all",
    "find",
    "code_of",
    "binary_object_of",
    "amount_of",
    "Rounding",
    "Quantity",
    "Identifier",
    "Code",
    "BinaryObject",
    "Amount","ROOT_CLASSES", "UblDocument", "XmlNode", "document_from_root",
    "ubl_version_id"]
