"""
test_r75_final_artifact_authority_model.py

R75 Train B: Tests for the two-authority model and final-artifact-authority.json.

Validates:
1. build_delivery_package generates a standalone .sha256.txt file
2. build_delivery_package generates a final-artifact-authority.json
3. The authority JSON has the correct schema and cross-layer SHA consistency
4. The standalone SHA file contains a valid sha256sum line

Sprint: FORMAT-FACTORY-R75-FINAL-ARTIFACT-AUTHORITY-REPAIR-RC-SEAL-PRODUCT-ADVANCEMENT-MEGA-TRAIN-001
"""
from __future__ import annotations

import hashlib
import json
import sys
import tempfile
import zipfile
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from tools.evidence.build_delivery_package import build_delivery_package


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _make_fake_evidence_zip(tmp_dir: Path, name: str) -> Path:
    """Create a minimal fake evidence ZIP with required metadata structure."""
    path = tmp_dir / name
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("bundle-metadata/sprint-id.txt", "FORMAT-FACTORY-R75-TEST-001\n")
        zf.writestr(
            "bundle-metadata/final-bundle-validation-proof.txt",
            f"Bundle: {name}\nSHA-256: placeholder\nBUNDLE_VALIDATION: PASS\n",
        )
        zf.writestr("bundle-metadata/git-status-final.txt", "nothing to commit\n")
    return path


def _make_fake_sidecar(tmp_dir: Path, evidence_zip: Path, sidecar_name: str) -> Path:
    """Create a fake sidecar proof JSON for an evidence ZIP."""
    h = hashlib.sha256()
    with open(evidence_zip, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    sha = h.hexdigest()

    sidecar_data = {
        "sha256": sha,
        "filename": evidence_zip.name,
        "size_bytes": evidence_zip.stat().st_size,
        "validation_result": "PASS",
        "git_head": "abc123def456abc123def456abc123def456abc123",
        "timestamp_utc": "2026-05-29T00:00:00+00:00",
    }
    path = tmp_dir / sidecar_name
    with open(path, "w", encoding="utf-8") as f:
        json.dump(sidecar_data, f, indent=2)
    return path


class TestFinalArtifactAuthorityModel:
    """R75 Train B: Two-authority model artifacts generated by build_delivery_package."""

    def setup_method(self):
        self.tmp = tempfile.mkdtemp()
        self.tmp_dir = Path(self.tmp)

    def test_standalone_sha_file_generated(self):
        """build_delivery_package must generate a .sha256.txt standalone SHA file."""
        evidence_zip = _make_fake_evidence_zip(self.tmp_dir, "r75-pass2-final.zip")
        sidecar = _make_fake_sidecar(
            self.tmp_dir, evidence_zip, "r75-pass2-final.sha256-proof.json"
        )
        output = self.tmp_dir / "r75-delivery-package.zip"
        contract = "tools/evidence/contracts/r75-fake-contract.yaml"

        manifest = build_delivery_package(
            evidence_zip=evidence_zip,
            sidecar=sidecar,
            contract_path=contract,
            output=output,
        )

        sha_txt = self.tmp_dir / "r75-delivery-package.sha256.txt"
        assert sha_txt.exists(), "Standalone .sha256.txt must be generated"
        assert "standalone_sha_file_path" in manifest
        content = sha_txt.read_text(encoding="utf-8").strip()
        assert len(content) > 0, "Standalone SHA file must not be empty"
        # Format: "<sha256>  <filename>"
        parts = content.split("  ", 1)
        assert len(parts) == 2, f"SHA file must have '  ' separator, got: {content!r}"
        sha_value, filename = parts
        assert len(sha_value) == 64, f"SHA must be 64 hex chars, got: {sha_value!r}"
        assert filename == "r75-delivery-package.zip", f"Filename must match, got: {filename!r}"
        # Verify SHA is correct
        actual_sha = hashlib.sha256(output.read_bytes()).hexdigest()
        assert sha_value == actual_sha, "Standalone SHA file must contain correct SHA"

    def test_artifact_authority_json_generated(self):
        """build_delivery_package must generate final-artifact-authority.json."""
        evidence_zip = _make_fake_evidence_zip(self.tmp_dir, "r75-pass2-final.zip")
        sidecar = _make_fake_sidecar(
            self.tmp_dir, evidence_zip, "r75-pass2-final.sha256-proof.json"
        )
        output = self.tmp_dir / "r75-delivery-package.zip"
        contract = "tools/evidence/contracts/r75-fake-contract.yaml"

        manifest = build_delivery_package(
            evidence_zip=evidence_zip,
            sidecar=sidecar,
            contract_path=contract,
            output=output,
        )

        authority_path = self.tmp_dir / "r75-final-artifact-authority.json"
        assert authority_path.exists(), "final-artifact-authority.json must be generated"
        assert "artifact_authority_path" in manifest

        with open(authority_path, encoding="utf-8") as f:
            authority = json.load(f)

        assert authority["schema_version"] == "1.0"
        assert authority["authority_model"] == "two_layer"
        assert "source_evidence_authority" in authority
        assert "final_artifact_authority" in authority
        assert "cross_layer_validation" in authority

    def test_authority_json_cross_layer_sha_consistency(self):
        """final-artifact-authority.json must record consistent cross-layer SHAs."""
        evidence_zip = _make_fake_evidence_zip(self.tmp_dir, "r75-pass2-final.zip")
        sidecar = _make_fake_sidecar(
            self.tmp_dir, evidence_zip, "r75-pass2-final.sha256-proof.json"
        )
        output = self.tmp_dir / "r75-delivery-package.zip"

        build_delivery_package(
            evidence_zip=evidence_zip,
            sidecar=sidecar,
            contract_path="tools/evidence/contracts/r75-fake.yaml",
            output=output,
        )

        authority_path = self.tmp_dir / "r75-final-artifact-authority.json"
        with open(authority_path, encoding="utf-8") as f:
            authority = json.load(f)

        sea = authority["source_evidence_authority"]
        faa = authority["final_artifact_authority"]
        xlv = authority["cross_layer_validation"]

        # Sidecar validates inner ZIP
        assert sea["sidecar_validates_inner_zip"] is True
        assert xlv["sidecar_proves_inner_zip"] is True

        # Delivery package SHA is correct
        actual_pkg_sha = hashlib.sha256(output.read_bytes()).hexdigest()
        assert faa["delivery_package_sha256"] == actual_pkg_sha

        # Inner ZIP SHA is correct
        actual_inner_sha = hashlib.sha256(evidence_zip.read_bytes()).hexdigest()
        assert sea["inner_zip_sha256"] == actual_inner_sha

        # Sidecar SHA is correct
        actual_sidecar_sha = hashlib.sha256(sidecar.read_bytes()).hexdigest()
        assert sea["sidecar_sha256"] == actual_sidecar_sha

    def test_authority_json_standalone_sha_field_present(self):
        """final-artifact-authority.json must reference the standalone SHA file."""
        evidence_zip = _make_fake_evidence_zip(self.tmp_dir, "r75-pass2-final.zip")
        sidecar = _make_fake_sidecar(
            self.tmp_dir, evidence_zip, "r75-pass2-final.sha256-proof.json"
        )
        output = self.tmp_dir / "r75-delivery-package.zip"

        build_delivery_package(
            evidence_zip=evidence_zip,
            sidecar=sidecar,
            contract_path="tools/evidence/contracts/r75-fake.yaml",
            output=output,
        )

        authority_path = self.tmp_dir / "r75-final-artifact-authority.json"
        with open(authority_path, encoding="utf-8") as f:
            authority = json.load(f)

        faa = authority["final_artifact_authority"]
        assert "standalone_sha_file" in faa
        assert faa["standalone_sha_file"] == "r75-delivery-package.sha256.txt"
