"""
create_golden_case.py — Capture current replay engine output as a golden test fixture.

Sprint: S-F2F-04 (Golden Dry-Run Tests)
Status: ACTIVE — write golden fixtures to tests/playbook/golden/ only.

AUTHORITY BOUNDARY:
  Golden fixtures are test artifacts only. They do NOT approve any gate,
  replace DEC-034, or replace human approval.

MODES:
  dry-run   — capture dry-run report as golden fixture (YAML)
  explain   — capture explain output as golden fixture (text)
  review-queue — capture review queue as golden fixture (YAML)

CLI:
  python tools/playbook/create_golden_case.py
    --mode {dry-run,explain,review-queue}
    --format-id FORMAT_ID
    --playbook PLAYBOOK_YAML
    --output-name FIXTURE_NAME   # written to tests/playbook/golden/
    [--schema SCHEMA_FILE]
    [--overwrite]                # required if fixture already exists

NORMALIZATION:
  Timestamps (generated_at, diff_generated_at, provenance.created_at),
  queue_id, and run_id are replaced with NORMALIZED_TIMESTAMP / *-NORMALIZED
  before writing the golden fixture.
"""

import argparse
import io
import os
import sys

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GOLDEN_DIR = os.path.join(REPO_ROOT, "tests", "playbook", "golden")
DEFAULT_SCHEMA = os.path.join(REPO_ROOT, "schemas", "playbook", "acquisition-playbook.schema.json")

_SENTINEL_TS = "NORMALIZED_TIMESTAMP"


def _normalize_report(report: dict) -> dict:
    """Replace unstable fields in a dry-run report."""
    import copy
    r = copy.deepcopy(report)
    if "generated_at" in r:
        r["generated_at"] = _SENTINEL_TS
    return r


def _normalize_queue(queue: dict) -> dict:
    """Replace unstable fields in a review queue."""
    import copy
    q = copy.deepcopy(queue)
    q["generated_at"] = _SENTINEL_TS
    q["queue_id"] = "rq-NORMALIZED"
    q["run_id"] = "s-f2f-03-export-NORMALIZED"
    for item in q.get("items", []):
        if "provenance" in item and "created_at" in item["provenance"]:
            item["provenance"]["created_at"] = _SENTINEL_TS
    return q


def _write_golden(output_name: str, content: str, overwrite: bool) -> str:
    """Write content to tests/playbook/golden/<output_name>. Returns absolute path."""
    os.makedirs(GOLDEN_DIR, exist_ok=True)
    out_path = os.path.join(GOLDEN_DIR, output_name)
    if os.path.exists(out_path) and not overwrite:
        print(
            f"CREATE_GOLDEN_ERROR: '{out_path}' already exists. Use --overwrite to replace.",
            file=sys.stderr,
        )
        sys.exit(2)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    return out_path


def mode_capture_dry_run(playbook_path: str, schema_path: str, format_id: str,
                          output_name: str, overwrite: bool) -> int:
    """Run dry-run and write normalized report as golden fixture."""
    sys.path.insert(0, os.path.join(REPO_ROOT, "tools", "playbook"))
    from replay_acquisition_playbook import mode_dry_run

    rc, report = mode_dry_run(playbook_path, schema_path, format_id)

    if report.get("skipped"):
        print(
            "CREATE_GOLDEN_SKIP: playbook is not_for_execution — no golden created.",
            file=sys.stderr,
        )
        return 0

    normalized = _normalize_report(report)
    header = (
        f"# Golden fixture: dry-run report for {os.path.basename(playbook_path)}\n"
        f"# format_id: {format_id}\n"
        f"# Timestamps replaced with NORMALIZED_TIMESTAMP\n"
        f"# Generated by create_golden_case.py (S-F2F-04)\n"
    )
    content = header + yaml.dump(
        normalized, default_flow_style=False, allow_unicode=True, sort_keys=False
    )
    out_path = _write_golden(output_name, content, overwrite)
    print(f"CREATE_GOLDEN: PASS — written to {out_path}")
    print(f"GOLDEN_EXIT_CODE: {rc} ({'PASS' if rc == 0 else 'CONFLICTS'})")
    return 0


def mode_capture_explain(playbook_path: str, format_id: str,
                          output_name: str, overwrite: bool) -> int:
    """Run explain and write stdout as golden text fixture."""
    sys.path.insert(0, os.path.join(REPO_ROOT, "tools", "playbook"))
    from replay_acquisition_playbook import mode_explain

    old_stdout = sys.stdout
    sys.stdout = io.StringIO()
    try:
        rc = mode_explain(playbook_path, format_id)
        content = sys.stdout.getvalue()
    finally:
        sys.stdout = old_stdout

    header = (
        f"# Golden fixture: explain output for {os.path.basename(playbook_path)}\n"
        f"# format_id: {format_id}\n"
        f"# Generated by create_golden_case.py (S-F2F-04)\n"
    )
    out_path = _write_golden(output_name, content, overwrite)
    print(f"CREATE_GOLDEN: PASS — written to {out_path}")
    return 0


def mode_capture_review_queue(playbook_path: str, schema_path: str, format_id: str,
                               output_name: str, overwrite: bool) -> int:
    """Run dry-run + build review queue and write normalized queue as golden fixture."""
    sys.path.insert(0, os.path.join(REPO_ROOT, "tools", "playbook"))
    from replay_acquisition_playbook import mode_dry_run
    from export_review_queue import build_review_queue

    _, report = mode_dry_run(playbook_path, schema_path, format_id)

    if report.get("skipped"):
        print("CREATE_GOLDEN_SKIP: playbook is not_for_execution.", file=sys.stderr)
        return 0

    queue = build_review_queue(format_id, report)
    normalized = _normalize_queue(queue)
    header = (
        f"# Golden fixture: review queue for {os.path.basename(playbook_path)}\n"
        f"# format_id: {format_id}\n"
        f"# Timestamps, queue_id, and run_id normalized\n"
        f"# Generated by create_golden_case.py (S-F2F-04)\n"
    )
    content = header + yaml.dump(
        normalized, default_flow_style=False, allow_unicode=True, sort_keys=False
    )
    out_path = _write_golden(output_name, content, overwrite)
    total = queue["summary"]["total_items"]
    print(f"CREATE_GOLDEN: PASS — written to {out_path} ({total} items)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Capture replay engine output as a golden test fixture (S-F2F-04).",
    )
    parser.add_argument(
        "--mode",
        required=True,
        choices=["dry-run", "explain", "review-queue"],
        help="What to capture as the golden fixture.",
    )
    parser.add_argument(
        "--format-id",
        required=True,
        help="Format identifier (e.g. 'fods' or 'fodt').",
    )
    parser.add_argument(
        "--playbook",
        required=True,
        help="Path to the playbook YAML fixture.",
    )
    parser.add_argument(
        "--output-name",
        required=True,
        help="Filename for the golden fixture (written to tests/playbook/golden/).",
    )
    parser.add_argument(
        "--schema",
        default=DEFAULT_SCHEMA,
        help=f"Path to acquisition-playbook schema JSON. Default: {DEFAULT_SCHEMA}",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        default=False,
        help="Overwrite an existing golden fixture. Required if the file already exists.",
    )

    args = parser.parse_args()

    if args.mode == "dry-run":
        return mode_capture_dry_run(
            args.playbook, args.schema, args.format_id, args.output_name, args.overwrite
        )
    elif args.mode == "explain":
        return mode_capture_explain(
            args.playbook, args.format_id, args.output_name, args.overwrite
        )
    elif args.mode == "review-queue":
        return mode_capture_review_queue(
            args.playbook, args.schema, args.format_id, args.output_name, args.overwrite
        )
    else:
        print(f"CREATE_GOLDEN_ERROR: Unknown mode '{args.mode}'.", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
