"""Exception coverage tests for qoi format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from qoi.exceptions import QoiParseError, QoiWriteError
from qoi.exceptions import QoiError


def test_qoiparseerror_is_raisable():
    with pytest.raises(QoiParseError):
        raise QoiParseError("test error message")


def test_qoiparseerror_inherits_base():
    assert issubclass(QoiParseError, QoiError)


def test_qoiparseerror_message():
    exc = QoiParseError("specific error")
    assert "specific error" in str(exc)


def test_qoiwriteerror_is_raisable():
    with pytest.raises(QoiWriteError):
        raise QoiWriteError("test error message")


def test_qoiwriteerror_inherits_base():
    assert issubclass(QoiWriteError, QoiError)


def test_qoiwriteerror_message():
    exc = QoiWriteError("specific error")
    assert "specific error" in str(exc)
