"""Exception coverage tests for fodg format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from fodg.exceptions import FodgWriteError
from fodg.exceptions import FodgError


def test_fodgwriteerror_is_raisable():
    with pytest.raises(FodgWriteError):
        raise FodgWriteError("test error message")


def test_fodgwriteerror_inherits_base():
    assert issubclass(FodgWriteError, FodgError)


def test_fodgwriteerror_message():
    exc = FodgWriteError("specific error")
    assert "specific error" in str(exc)
