"""
format-factory: NDJSON (Newline-Delimited JSON) FOSS Python track.

Minimal FOSS implementation for .ndjson / .jsonl format support.
Spec: https://ndjson.org/ — royalty-free, public domain format.
Uses stdlib json only — no external dependencies.
Acquisition Gates 1-4 initiated.

FOSS track only — no commercial readiness implied.
"""

from .ndjson_codec import (
    NdjsonError,
    NdjsonParseError,
    probe_ndjson,
    load_ndjson,
    write_ndjson,
    append_record,
    filter_records,
    get_field_names,
    export_to_csv,
    get_record_count,
    validate_schema,
    roundtrip,
    sort_records,
    write_csv,
    field_stats,
    merge_ndjson,
    group_by,
    sum_field,
    rename_field,
    tail,
    pick,
    average_value,
    count_by,
    distinct_values,
    to_jsonl_str,
    pluck,
    min_value,
    max_value,
    deduplicate,
    count_records,
    zip_records,
    sort_by,
    aggregate,
    head,
    flatten_records,
    to_markdown_table,
    count_unique_values,
    zip_with_index,
    omit,
    batch_update,
    ndjson_max_field_count,
    ndjson_average_field_count,
    ndjson_null_field_count,
    ndjson_min_field_count,
    ndjson_record_count,
    ndjson_field_exists,
    ndjson_max_record_size,
    ndjson_total_field_count,
    ndjson_unique_field_names,
    ndjson_nested_field_count,
    ndjson_boolean_field_count,
    ndjson_has_nested_objects,
    ndjson_empty_record_count,
    ndjson_numeric_field_count,
    ndjson_average_record_size,
    ndjson_string_field_count,
)

__all__ = [
    "NdjsonError",
    "NdjsonParseError",
    "probe_ndjson",
    "load_ndjson",
    "write_ndjson",
    "append_record",
    "filter_records",
    "get_field_names",
    "export_to_csv",
    "get_record_count",
    "validate_schema",
    "roundtrip",
    "sort_records",
    "write_csv",
    "field_stats",
    "merge_ndjson",
    "group_by",
    "sum_field",
    "rename_field",
    "tail",
    "pick",
    "average_value",
    "count_by",
    "distinct_values",
    "to_jsonl_str",
    "pluck",
    "min_value",
    "max_value",
    "deduplicate",
    "count_records",
    "zip_records",
    "sort_by",
    "aggregate",
    "head",
    "flatten_records",
    "to_markdown_table",
    "count_unique_values",
    "zip_with_index",
    "omit",
    "batch_update",
    "ndjson_max_field_count",
    "ndjson_average_field_count",
    "ndjson_null_field_count",
    "ndjson_min_field_count",
    "ndjson_record_count",
    "ndjson_field_exists",
    "ndjson_max_record_size",
    "ndjson_total_field_count",
    "ndjson_unique_field_names",
    "ndjson_nested_field_count",
    "ndjson_boolean_field_count",
    "ndjson_has_nested_objects",
    "ndjson_empty_record_count",
    "ndjson_numeric_field_count",
    "ndjson_average_record_size",
    "ndjson_string_field_count",
]

__version__ = "0.1.0.dev0"
__track__ = "python-foss"
__commercial_ready__ = False
__capability_level__ = "alpha-foss-preview"
