"""Generate exception coverage test files for all formats with uncovered exceptions.

TC-CERT-H-EXC certification hardening.
"""
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# Map: format -> {module_name: [exception_class_names]}
EXCEPTIONS = {
    "zst": {
        "zst_codec": ["ZstDecompressError", "ZstFileNotFoundError", "ZstReadError"],
        "exceptions": ["ZstParseError", "ZstWriteError"],
    },
    "dif": {"exceptions": ["DifParseError", "DifWriteError"]},
    "ods": {"exceptions": ["OdsParseError", "OdsWriteError"]},
    "odt": {"exceptions": ["OdtParseError", "OdtWriteError"]},
    "pbm": {"exceptions": ["PbmParseError", "PbmWriteError"]},
    "pgm": {"exceptions": ["PgmParseError", "PgmWriteError"]},
    "ppm": {"exceptions": ["PpmParseError", "PpmWriteError"]},
    "qoi": {"exceptions": ["QoiParseError", "QoiWriteError"]},
    "abw": {"exceptions": ["AbwWriteError"]},
    "fodg": {"exceptions": ["FodgWriteError"]},
    "fodp": {"exceptions": ["FodpWriteError"]},
    "gnumeric": {"exceptions": ["GnumericWriteError"]},
    "ndjson": {"exceptions": ["NdjsonWriteError"]},
    "sylk": {"exceptions": ["SylkWriteError"]},
    "tsv": {"exceptions": ["TsvWriteError"]},
    "xcf": {"exceptions": ["XcfWriteError"]},
}

BASE_ERRORS = {
    "zst": ("zst_codec", "ZstError"),
    "dif": ("exceptions", "DifError"),
    "ods": ("exceptions", "OdsError"),
    "odt": ("exceptions", "OdtError"),
    "pbm": ("exceptions", "PbmError"),
    "pgm": ("exceptions", "PgmError"),
    "ppm": ("exceptions", "PpmError"),
    "qoi": ("exceptions", "QoiError"),
    "abw": ("exceptions", "AbwError"),
    "fodg": ("exceptions", "FodgError"),
    "fodp": ("exceptions", "FodpError"),
    "gnumeric": ("exceptions", "GnumericError"),
    "ndjson": ("exceptions", "NdjsonError"),
    "sylk": ("exceptions", "SylkError"),
    "tsv": ("exceptions", "TsvError"),
    "xcf": ("exceptions", "XcfError"),
}


def generate_test_file(fmt: str, modules: dict) -> Path:
    base_mod, base_cls = BASE_ERRORS[fmt]
    all_exc_names = []
    imports = []

    for mod_name, exc_names in modules.items():
        all_exc_names.extend(exc_names)
        names_str = ", ".join(exc_names)
        imports.append(f"from {fmt}.{mod_name} import {names_str}")

    # Import base error if not already imported
    if base_cls not in all_exc_names:
        imports.append(f"from {fmt}.{base_mod} import {base_cls}")

    lines = [
        f'"""Exception coverage tests for {fmt} format.',
        "",
        "Ensures all exception classes are importable, raisable, and properly subclassed.",
        "Generated by TC-CERT-H-EXC certification hardening.",
        '"""',
        "import pytest",
        "",
    ]
    lines.extend(imports)
    lines.append("")
    lines.append("")

    for exc_name in all_exc_names:
        test_name = exc_name.lower()
        lines.extend([
            f"def test_{test_name}_is_raisable():",
            f'    with pytest.raises({exc_name}):',
            f'        raise {exc_name}("test error message")',
            "",
            "",
            f"def test_{test_name}_inherits_base():",
            f"    assert issubclass({exc_name}, {base_cls})",
            "",
            "",
            f"def test_{test_name}_message():",
            f'    exc = {exc_name}("specific error")',
            '    assert "specific error" in str(exc)',
            "",
            "",
        ])

    test_path = REPO_ROOT / "tests" / "python" / fmt / "test_exception_coverage.py"
    test_path.parent.mkdir(parents=True, exist_ok=True)
    test_path.write_text("\n".join(lines), encoding="utf-8")
    return test_path


def main():
    for fmt, modules in EXCEPTIONS.items():
        path = generate_test_file(fmt, modules)
        exc_count = sum(len(v) for v in modules.values())
        print(f"Wrote {path.relative_to(REPO_ROOT)} ({exc_count} exceptions, {exc_count * 3} tests)")


if __name__ == "__main__":
    main()
