"""Exception coverage tests for odt format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from odt.exceptions import OdtParseError, OdtWriteError
from odt.exceptions import OdtError


def test_odtparseerror_is_raisable():
    with pytest.raises(OdtParseError):
        raise OdtParseError("test error message")


def test_odtparseerror_inherits_base():
    assert issubclass(OdtParseError, OdtError)


def test_odtparseerror_message():
    exc = OdtParseError("specific error")
    assert "specific error" in str(exc)


def test_odtwriteerror_is_raisable():
    with pytest.raises(OdtWriteError):
        raise OdtWriteError("test error message")


def test_odtwriteerror_inherits_base():
    assert issubclass(OdtWriteError, OdtError)


def test_odtwriteerror_message():
    exc = OdtWriteError("specific error")
    assert "specific error" in str(exc)
