#!/usr/bin/env python3
"""Build a cross-format test index for the Format Factory test suite.

Scans tests/python/deepening/ and tests/python/dogfood/ to map each format name
to the set of test FILES that exercise it. This index is consumed by test_runner.py
to ensure that when a format's source changes, cross-format tests covering it are
also included in the auto-detected test scope.

Outputs:
  registry/cross-format-test-index.yaml

Usage:
  python tools/build_cross_format_index.py
  python tools/build_cross_format_index.py --dry-run
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEEPENING_DIR = REPO_ROOT / "tests" / "python" / "deepening"
DOGFOOD_DIR = REPO_ROOT / "tests" / "python" / "dogfood"
INDEX_OUTPUT = REPO_ROOT / "registry" / "cross-format-test-index.yaml"

KNOWN_FORMATS = {
    "abw", "csv", "dif", "fodg", "fodp", "fods", "fodt",
    "gnumeric", "ndjson", "ods", "odt", "pbm", "pgm", "ppm",
    "qoi", "sylk", "toml", "tsv", "xcf", "zst",
}

# Patterns for extracting format references from source
_IMPORT_PATTERNS = [
    # from src.python.fods import ...
    re.compile(r'from\s+src\.python\.(\w+)\s+import'),
    # from src.python.fods.fods_codec import ...
    re.compile(r'from\s+src\.python\.(\w+)\.\w+\s+import'),
    # import src.python.fods
    re.compile(r'import\s+src\.python\.(\w+)'),
    # sys.path / manual import patterns common in test files
    re.compile(r'from\s+(\w+)\s+import\s+\w+_\w+'),  # from fods import fods_*
]

# Function-call patterns: fods_string_density(...) → format=fods
_CALL_PATTERN = re.compile(r'\b([a-z][a-z0-9]+)_[a-z]')


def _extract_formats_from_filename(filename: str) -> set[str]:
    """Extract format names embedded in filename.

    E.g. test_r273_dif_sylk_abw_fods_deepening → {dif, sylk, abw, fods}
    """
    stem = Path(filename).stem
    parts = stem.split("_")
    return {p for p in parts if p in KNOWN_FORMATS}


def _extract_formats_from_content(content: str) -> set[str]:
    """Extract format names referenced in file content."""
    formats: set[str] = set()

    # Direct import patterns
    for pat in _IMPORT_PATTERNS:
        for m in pat.finditer(content):
            fmt = m.group(1)
            if fmt in KNOWN_FORMATS:
                formats.add(fmt)

    # Function call patterns: detect calls like fods_string_density(...)
    for m in _CALL_PATTERN.finditer(content):
        prefix = m.group(1)
        if prefix in KNOWN_FORMATS:
            formats.add(prefix)

    return formats


def build_index(dry_run: bool = False) -> dict[str, list[str]]:
    """Scan deepening + dogfood dirs and build format→file mapping."""
    index: dict[str, set[str]] = defaultdict(set)

    dirs = [
        (DEEPENING_DIR, "tests/python/deepening"),
        (DOGFOOD_DIR, "tests/python/dogfood"),
    ]

    total_files = 0
    for scan_dir, label in dirs:
        if not scan_dir.is_dir():
            print(f"WARNING: {label} not found, skipping", file=sys.stderr)
            continue
        for fp in sorted(scan_dir.glob("test_*.py")):
            rel_path = str(fp.relative_to(REPO_ROOT)).replace("\\", "/")
            try:
                content = fp.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue

            formats_in_name = _extract_formats_from_filename(fp.name)
            formats_in_content = _extract_formats_from_content(content)
            all_formats = formats_in_name | formats_in_content

            for fmt in all_formats:
                index[fmt].add(rel_path)

            total_files += 1

    # Convert to sorted lists
    result = {fmt: sorted(paths) for fmt, paths in sorted(index.items())}

    # Stats
    print(f"\nCross-Format Index Summary")
    print(f"  Files scanned: {total_files}")
    print(f"  Formats indexed: {len(result)}")
    for fmt, paths in sorted(result.items()):
        print(f"  {fmt:12s}: {len(paths):5d} cross-format test files")

    if not dry_run:
        _write_index(result)

    return result


def _write_index(index: dict[str, list[str]]) -> None:
    """Write the index to registry/cross-format-test-index.yaml."""
    lines = [
        "# Cross-Format Test Index — Format Factory",
        "# Generated by tools/build_cross_format_index.py",
        "# Maps each format to the set of test files (in deepening/ and dogfood/) that cover it.",
        "# Used by tools/test_runner.py --auto to detect cross-format tests when a format changes.",
        "",
        "schema_version: \"1.0\"",
        "generated_date: \"2026-06-18\"",
        "description: >",
        "  When src/python/{format}/ changes, test_runner.py --auto will also include",
        "  all files listed under format_to_tests[format] in addition to tests/python/{format}/.",
        "  This ensures cross-format deepening and dogfood tests are not silently skipped.",
        "",
        "format_to_tests:",
    ]

    for fmt, paths in sorted(index.items()):
        lines.append(f"  {fmt}:")
        for p in paths:
            lines.append(f"    - \"{p}\"")

    INDEX_OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote cross-format index: {INDEX_OUTPUT}")
    print(f"  Total entries: {sum(len(v) for v in index.values())}")


def main():
    parser = argparse.ArgumentParser(description="Build cross-format test index")
    parser.add_argument("--dry-run", action="store_true", help="Print summary, don't write file")
    args = parser.parse_args()

    index = build_index(dry_run=args.dry_run)

    if not args.dry_run:
        print(f"\nIndex written. Use with: python tools/test_runner.py --auto [--format FMT]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
