#!/usr/bin/env python3
"""Format Factory layered test runner.

Selects and runs the appropriate pytest layer for a given change scope.
Outputs structured JSON compatible with evidence-declaration.yaml.

Usage:
    python tools/test_runner.py --layer 0                  # explicit layer
    python tools/test_runner.py --auto                     # auto-detect from git diff
    python tools/test_runner.py --auto --format tsv        # hint: specific format
    python tools/test_runner.py --layer 6 --shard 1/4      # sharded full suite
    python tools/test_runner.py --layer 1 --dry-run        # print command only
    python tools/test_runner.py --layer 3 --json-out r.json
    python tools/test_runner.py --list-layers              # list all layers as JSON
    python tools/test_runner.py --layer 0 --known-failures registry/known-failure-ledger.yaml
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
import time
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from fnmatch import fnmatch
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "registry" / "test-layer-manifest.yaml"

LAYER_NAMES = {
    0: "structural",
    1: "focused",
    2: "family",
    3: "integration",
    4: "golden",
    5: "broad",
    6: "full",
}

SHARD_MAP = {
    1: {"path": "tests/python/", "ignore": []},
    2: {"path": "tests/supervisor/", "ignore": []},
    3: {"path": "tests/evidence/", "ignore": []},
    4: {
        "path": "tests/",
        "ignore": ["tests/python", "tests/supervisor", "tests/evidence"],
    },
}

CROSS_FORMAT_INDEX_PATH = REPO_ROOT / "registry" / "cross-format-test-index.yaml"


def load_manifest(path: Path | None = None) -> dict:
    """Load the test-layer-manifest.yaml."""
    path = path or MANIFEST_PATH
    try:
        import yaml
        with open(path, encoding="utf-8") as f:
            return yaml.safe_load(f)
    except ImportError:
        # Fallback: parse just enough YAML for change_impact rules
        # If PyYAML is missing, use a minimal hardcoded default
        return _fallback_manifest()


def _fallback_manifest() -> dict:
    """Minimal manifest when PyYAML is unavailable."""
    return {
        "layers": {f"layer{i}": {"name": LAYER_NAMES[i]} for i in range(7)},
        "format_families": {
            "netpbm": ["pbm", "pgm", "ppm"],
            "opendocument_spreadsheet": ["fods", "ods"],
            "opendocument_text": ["fodt", "odt", "abw"],
            "opendocument_graphics": ["fodg"],
            "tabular": ["csv", "tsv", "sylk", "dif", "gnumeric"],
            "image": ["pbm", "pgm", "ppm", "qoi", "xcf"],
            "archive": ["zst"],
            "structured": ["ndjson", "toml"],
        },
        "change_impact": [
            {"pattern": "docs/**", "min_layer": 0},
            {"pattern": "reports/**", "min_layer": 0},
            {"pattern": "plans/**", "min_layer": 0},
            {"pattern": "*.md", "min_layer": 0},
            {"pattern": "src/python/**", "min_layer": 1},
            {"pattern": "tests/python/*/test_*.py", "min_layer": 1},
            {"pattern": "tools/supervisor/**", "min_layer": 3},
            {"pattern": "tools/ai/**", "min_layer": 3},
            {"pattern": "tests/supervisor/**", "min_layer": 3},
            {"pattern": "tests/evidence/**", "min_layer": 3},
            {"pattern": "tests/capability_layer/**", "min_layer": 3},
            {"pattern": "registry/**", "min_layer": 3},
            {"pattern": "schemas/**", "min_layer": 3},
            {"pattern": "tools/*", "min_layer": 5},
            {"pattern": "tests/python/conftest.py", "min_layer": 5},
            {"pattern": "src/net/**", "min_layer": 5},
            {"pattern": "pyproject.toml", "min_layer": 6},
            {"pattern": ".github/**", "min_layer": 6},
            {"pattern": "tests/conftest.py", "min_layer": 6},
            {"pattern": "_default", "min_layer": 6},
        ],
    }


def load_cross_format_index(path: Path | None = None) -> dict[str, list[str]]:
    """Load the cross-format test index (format -> list of cross-format test files).

    Returns empty dict if the index does not exist or PyYAML is unavailable.
    The index is generated by tools/build_cross_format_index.py.
    """
    p = path or CROSS_FORMAT_INDEX_PATH
    if not p.exists():
        return {}
    try:
        import yaml
        with open(p) as f:
            data = yaml.safe_load(f) or {}
        return data.get("format_to_tests", {})
    except Exception:
        return {}


def resolve_cross_format_paths(
    formats: set[str],
    index: dict[str, list[str]],
    repo_root: Path = REPO_ROOT,
) -> list[str]:
    """Return absolute paths of cross-format test files for the given formats.

    Only returns paths that are NOT already covered by the standard
    tests/python/{format}/ directory (avoids double-counting).
    """
    standard_dirs = {str(repo_root / "tests" / "python" / fmt) for fmt in formats}
    cross_paths: list[str] = []
    seen: set[str] = set()
    for fmt in formats:
        for rel_path in index.get(fmt, []):
            abs_path = str(repo_root / rel_path)
            # Skip if this file is already under a standard format directory
            if any(abs_path.startswith(d) for d in standard_dirs):
                continue
            if abs_path not in seen:
                seen.add(abs_path)
                cross_paths.append(abs_path)
    return sorted(cross_paths)


def detect_changed_files(base_ref: str = "HEAD") -> list[str]:
    """Detect changed files via git diff."""
    # Try staged + unstaged vs base_ref
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", base_ref],
            capture_output=True,
            text=True,
            cwd=str(REPO_ROOT),
        )
        files = [f.strip() for f in result.stdout.strip().splitlines() if f.strip()]
    except (subprocess.SubprocessError, FileNotFoundError):
        files = []

    # Also include untracked files
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", "--cached"],
            capture_output=True,
            text=True,
            cwd=str(REPO_ROOT),
        )
        staged = [f.strip() for f in result.stdout.strip().splitlines() if f.strip()]
        files = list(set(files + staged))
    except (subprocess.SubprocessError, FileNotFoundError):
        pass

    # Also get unstaged changes
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only"],
            capture_output=True,
            text=True,
            cwd=str(REPO_ROOT),
        )
        unstaged = [f.strip() for f in result.stdout.strip().splitlines() if f.strip()]
        files = list(set(files + unstaged))
    except (subprocess.SubprocessError, FileNotFoundError):
        pass

    return sorted(files)


def resolve_formats_from_paths(changed_files: list[str]) -> set[str]:
    """Extract format names from changed file paths."""
    formats = set()
    for f in changed_files:
        parts = f.replace("\\", "/").split("/")
        # src/python/{format}/... or tests/python/{format}/...
        if len(parts) >= 3 and parts[0] in ("src", "tests") and parts[1] == "python":
            fmt = parts[2]
            if fmt not in ("conftest.py", "__pycache__") and not fmt.startswith("test_"):
                formats.add(fmt)
    return formats


def resolve_family(fmt: str, manifest: dict) -> set[str]:
    """Expand a format to its family members."""
    families = manifest.get("format_families", {})
    result = {fmt}
    for _family_name, members in families.items():
        if fmt in members:
            result.update(members)
    return result


def compute_min_layer(
    changed_files: list[str], manifest: dict
) -> tuple[int, str]:
    """Walk change-impact rules, return (max_min_layer, reason)."""
    rules = manifest.get("change_impact", [])
    max_layer = -1
    reason = "no changed files detected"

    if not changed_files:
        return 0, reason

    for f in changed_files:
        f_norm = f.replace("\\", "/")
        matched = False
        for rule in rules:
            pat = rule["pattern"]
            if pat == "_default":
                if not matched:
                    layer = rule["min_layer"]
                    if layer > max_layer:
                        max_layer = layer
                        reason = f"{f_norm} matched default rule"
                break
            if fnmatch(f_norm, pat):
                layer = rule["min_layer"]
                if layer > max_layer:
                    max_layer = layer
                    reason = f"{f_norm} matched pattern '{pat}'"
                matched = True
                break
        if not matched:
            # No pattern matched — use default (layer 6)
            if 6 > max_layer:
                max_layer = 6
                reason = f"{f_norm} matched no pattern (default: layer 6)"

    return max(0, max_layer), reason


def build_marker_expr(layer: int) -> str:
    """Build cumulative marker expression for the given layer."""
    if layer >= 6:
        return ""  # No filter needed — run everything
    parts = [f"layer{i}" for i in range(layer + 1)]
    return " or ".join(parts)


_LAYER0_FILES = [
    "tests/test_health_check.py",
    "tests/python/test_pige_public_api_smoke.py",
]


def build_pytest_cmd(
    layer: int,
    formats: set[str] | None = None,
    shard: tuple[int, int] | None = None,
    verbose: bool = False,
    junitxml_path: str | None = None,
    cross_format_paths: list[str] | None = None,
    skip_arithmetic: bool = False,
) -> list[str]:
    """Construct the pytest command for the given layer and options.

    Args:
        cross_format_paths: additional test file paths from the cross-format index
            (typically deepening/dogfood files that cover the changed formats).
        skip_arithmetic: if True, pass --skip-arithmetic to pytest (conftest will
            skip tests listed in registry/arithmetic-deepening-tests.txt).
    """
    python_exe = sys.executable
    cmd = [python_exe, "-m", "pytest"]

    # Fast-path: L0 uses explicit file paths (no marker, avoids full-tree collection)
    if layer == 0:
        for f in _LAYER0_FILES:
            cmd.append(str(REPO_ROOT / f))
    # Fast-path: L1/L2 with format hint uses directory paths + L0 files (cumulative)
    elif layer <= 2 and formats:
        # Include L0 files first (cumulativity: layer N includes layers 0..N)
        for f in _LAYER0_FILES:
            cmd.append(str(REPO_ROOT / f))
        for fmt in sorted(formats):
            test_dir = REPO_ROOT / "tests" / "python" / fmt
            if test_dir.is_dir():
                cmd.append(str(test_dir))
        # Add cross-format test paths (deepening/dogfood files for these formats)
        if cross_format_paths:
            for p in cross_format_paths:
                if Path(p).exists() and p not in cmd:
                    cmd.append(p)
    else:
        # Standard path: use cumulative marker expression
        marker_expr = build_marker_expr(layer)
        if marker_expr:
            cmd.extend(["-m", marker_expr])

    # Shard scoping for L6
    if shard:
        shard_num, _shard_total = shard
        shard_info = SHARD_MAP.get(shard_num)
        if shard_info:
            cmd.append(str(REPO_ROOT / shard_info["path"]))
            for ign in shard_info.get("ignore", []):
                cmd.extend(["--ignore", str(REPO_ROOT / ign)])

    # Skip arithmetic deepening tests if requested (conftest reads the manifest)
    if skip_arithmetic:
        cmd.append("--skip-arithmetic")

    # Output
    if junitxml_path:
        cmd.extend(["--junitxml", junitxml_path])

    if verbose:
        cmd.append("-v")

    cmd.append("-q")

    # Always include --continue-on-collection-errors so gap tests (ImportError)
    # don't abort the entire run. Tests that do collect still run normally.
    cmd.append("--continue-on-collection-errors")

    return cmd


def parse_junitxml(path: str) -> dict:
    """Parse junitxml output into test_results dict."""
    try:
        tree = ET.parse(path)
        root = tree.getroot()
        # Handle both <testsuites> and <testsuite> root
        if root.tag == "testsuites":
            suites = root.findall("testsuite")
        else:
            suites = [root]

        total = 0
        failures = 0
        errors = 0
        skipped = 0
        for suite in suites:
            total += int(suite.get("tests", 0))
            failures += int(suite.get("failures", 0))
            errors += int(suite.get("errors", 0))
            skipped += int(suite.get("skipped", 0))

        passed = total - failures - errors - skipped
        return {
            "passed": max(0, passed),
            "failed": failures,
            "skipped": skipped,
            "errors": errors,
        }
    except FileNotFoundError:
        return {"passed": 0, "failed": 0, "skipped": 0, "errors": 0,
                "_parse_error": "junitxml file not found"}
    except (ET.ParseError, ValueError):
        return {"passed": 0, "failed": 0, "skipped": 0, "errors": 0,
                "_parse_error": "junitxml parse failed"}


def run_and_collect(
    cmd: list[str],
    layer: int,
    layer_reason: str,
    formats: set[str] | None = None,
    shard: tuple[int, int] | None = None,
    json_out_path: str | None = None,
) -> dict:
    """Run pytest command and collect structured results."""
    start = time.monotonic()
    start_ts = datetime.now(timezone.utc).isoformat()

    # Create temp junitxml if not already in cmd
    junitxml_in_cmd = any("--junitxml" in c for c in cmd)
    junitxml_path = None
    if not junitxml_in_cmd:
        tmp = tempfile.NamedTemporaryFile(suffix=".xml", delete=False, prefix="ff-test-")
        junitxml_path = tmp.name
        tmp.close()
        cmd.extend(["--junitxml", junitxml_path])
    else:
        for i, c in enumerate(cmd):
            if c == "--junitxml" and i + 1 < len(cmd):
                junitxml_path = cmd[i + 1]
                break

    # Propagate sys.path + user site-packages via PYTHONPATH so pytest is findable
    # even when installed in user site-packages and run from a system Python.
    import site as _site
    _env = dict(os.environ)
    _path_entries = list(sys.path)
    try:
        _user_site = _site.getusersitepackages()
        if _user_site and _user_site not in _path_entries:
            _path_entries.append(_user_site)
    except AttributeError:
        pass
    _extra = os.pathsep.join(p for p in _path_entries if p)
    _existing = _env.get("PYTHONPATH", "")
    _env["PYTHONPATH"] = f"{_extra}{os.pathsep}{_existing}" if _existing else _extra
    proc = subprocess.run(cmd, cwd=str(REPO_ROOT), capture_output=True, text=True, env=_env)
    elapsed = time.monotonic() - start

    test_results = parse_junitxml(junitxml_path) if junitxml_path else {
        "passed": 0, "failed": 0, "skipped": 0, "errors": 0,
    }

    # Extract parse error sentinel (if any) before exposing test_results
    parse_error = test_results.pop("_parse_error", None)

    # Determine result reliability
    total_tests = sum(test_results[k] for k in ("passed", "failed", "skipped", "errors"))
    results_reliable = True
    if parse_error:
        results_reliable = False
    elif proc.returncode != 0 and total_tests == 0:
        results_reliable = False

    if not results_reliable:
        print(
            f"WARNING: pytest exited {proc.returncode} but test results are "
            f"unreliable (0 tests recorded). Check pytest output for errors.",
            file=sys.stderr,
        )

    # Clean up temp file
    if junitxml_path and not junitxml_in_cmd:
        try:
            os.unlink(junitxml_path)
        except OSError:
            pass

    marker_expr = build_marker_expr(layer)
    result = {
        "layer": layer,
        "layer_name": LAYER_NAMES.get(layer, f"layer{layer}"),
        "layer_reason": layer_reason,
        "formats_detected": sorted(formats) if formats else [],
        "marker_expr": marker_expr or "(no filter - full suite)",
        "command": " ".join(cmd),
        "test_results": test_results,
        "test_results_reliable": results_reliable,
        "duration_seconds": round(elapsed, 2),
        "shard": f"{shard[0]}/{shard[1]}" if shard else None,
        "timestamp": start_ts,
        "pytest_exit_code": proc.returncode,
    }

    if json_out_path:
        out_path = Path(json_out_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w") as f:
            json.dump(result, f, indent=2)

    return result


def _handle_list_layers() -> None:
    """Handle --list-layers flag via sys.argv pre-processing (before argparse)."""
    manifest = load_manifest()
    layers_data = manifest.get("layers", {})
    result = []
    for i in range(7):
        key = f"layer{i}"
        layer_info = layers_data.get(key, {})
        result.append({
            "layer": i,
            "name": layer_info.get("name", LAYER_NAMES.get(i, f"layer{i}")),
            "description": layer_info.get("description", ""),
            "max_time_seconds": layer_info.get("max_time_seconds", None),
        })
    print(json.dumps(result, indent=2))


def _compare_known_failures(
    test_results: dict,
    known_failures_path: str,
    xml_path: str | None = None,
) -> tuple[list[dict], list[dict]]:
    """Compare current failures against known-failure ledger.

    Returns (pre_existing, new_failures) as lists of failure dicts.
    """
    # Load known failures
    known: list[dict] = []
    kf_path = Path(known_failures_path)
    if kf_path.exists():
        try:
            import yaml
            with open(kf_path) as f:
                data = yaml.safe_load(f) or {}
            known = data.get("known_failures", [])
        except Exception:
            try:
                with open(kf_path) as f:
                    data = json.load(f) or {}
                known = data.get("known_failures", [])
            except Exception:
                known = []

    known_ids = {k.get("test_id", "") for k in known}

    # Extract current failing test IDs from junitxml if available
    current_failures: list[str] = []
    if xml_path:
        try:
            tree = ET.parse(xml_path)
            root = tree.getroot()
            suites = root.findall("testsuite") if root.tag == "testsuites" else [root]
            for suite in suites:
                for tc in suite.findall("testcase"):
                    if tc.find("failure") is not None or tc.find("error") is not None:
                        classname = tc.get("classname", "")
                        name = tc.get("name", "")
                        test_id = f"{classname}::{name}" if classname else name
                        current_failures.append(test_id)
        except Exception:
            pass

    pre_existing = [f for f in current_failures if f in known_ids]
    new_failures = [f for f in current_failures if f not in known_ids]

    return (
        [{"test_id": tid} for tid in pre_existing],
        [{"test_id": tid} for tid in new_failures],
    )


SHARD_LEDGER_PATH = REPO_ROOT / "registry" / "full-suite-shard-ledger.yaml"


def _update_shard_ledger(shard_num: int, total_shards: int, result: dict) -> None:
    """Write shard completion status to the shard ledger (best-effort)."""
    try:
        import yaml
    except ImportError:
        print("WARNING: pyyaml not available, skipping shard ledger update", file=sys.stderr)
        return
    try:
        ledger = yaml.safe_load(SHARD_LEDGER_PATH.read_text(encoding="utf-8")) or {}
        tr = result.get("test_results", {})
        entry = {
            "run_id": f"run-{datetime.now().strftime('%Y-%m-%d-%H%M%S')}",
            "date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            "shard_id": shard_num,
            "tests_run": sum(tr.get(k, 0) for k in ("passed", "failed", "skipped", "errors")),
            "passed": tr.get("passed", 0),
            "failed": tr.get("failed", 0),
            "duration_seconds": result.get("duration_seconds", 0),
            "exit_code": result.get("pytest_exit_code", -1),
        }
        if not isinstance(ledger.get("history"), list):
            ledger["history"] = []
        ledger["history"].append(entry)

        # Update resume_state
        rs = ledger.setdefault("resume_state", {})
        rs["last_completed_shard"] = shard_num
        rs["last_run_date"] = entry["date"]
        rs["last_run_id"] = entry["run_id"]
        completed = set(rs.get("shards_completed") or [])
        completed.add(shard_num)
        rs["shards_completed"] = sorted(completed)
        all_shards = set(range(1, total_shards + 1))
        rs["shards_pending"] = sorted(all_shards - completed)
        if rs["shards_pending"]:
            rs["resume_from_shard"] = rs["shards_pending"][0]
        else:
            rs["resume_from_shard"] = None

        ledger["last_updated"] = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        SHARD_LEDGER_PATH.write_text(yaml.dump(ledger, default_flow_style=False, sort_keys=False),
                                     encoding="utf-8")
        print(f"  Shard ledger updated: shard {shard_num}/{total_shards}")
    except Exception as e:
        print(f"WARNING: could not update shard ledger: {e}", file=sys.stderr)


def main():
    # Pre-process: handle --list-layers before argparse (avoids breaking mutex group)
    if "--list-layers" in sys.argv:
        _handle_list_layers()
        return

    parser = argparse.ArgumentParser(
        description="Format Factory layered test runner",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--layer", type=int, choices=range(7), metavar="N",
        help="Explicit layer (0-6)",
    )
    group.add_argument(
        "--auto", action="store_true",
        help="Auto-detect layer from git diff",
    )
    parser.add_argument(
        "--base-ref", default="HEAD",
        help="Git ref for diff comparison (default: HEAD)",
    )
    parser.add_argument(
        "--format", dest="format_hint", metavar="FMT",
        help="Hint: specific format name (e.g., tsv)",
    )
    parser.add_argument(
        "--shard", metavar="M/N",
        help="Shard specification for layer 6 (e.g., 1/4)",
    )
    parser.add_argument(
        "--json-out", metavar="PATH",
        help="Write JSON results to file",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print command without running")
    parser.add_argument("--verbose", "-v", action="store_true", help="Pass -v to pytest")
    parser.add_argument(
        "--known-failures", metavar="PATH",
        help="Path to known-failure-ledger.yaml; compare current failures against it",
    )
    parser.add_argument(
        "--skip-arithmetic", action="store_true",
        help=(
            "Skip arithmetic-formula deepening tests (registry/arithmetic-deepening-tests.txt). "
            "Passed through to pytest via conftest --skip-arithmetic flag. "
            "Use for faster routine runs; full suite (layer6) always includes them."
        ),
    )
    parser.add_argument(
        "--no-cross-format", action="store_true",
        help=(
            "Suppress cross-format test inclusion in --auto mode. "
            "By default, --auto also includes cross-format tests from "
            "registry/cross-format-test-index.yaml for changed formats. "
            "Use this flag to get the previous (format-only) behavior."
        ),
    )

    args = parser.parse_args()

    manifest = load_manifest()

    # Determine layer
    formats: set[str] = set()
    cross_format_paths: list[str] = []
    if args.auto:
        changed = detect_changed_files(args.base_ref)
        layer, reason = compute_min_layer(changed, manifest)
        formats = resolve_formats_from_paths(changed)
    else:
        layer = args.layer
        reason = f"explicitly set to layer {layer}"

    # Apply format hint
    if args.format_hint:
        formats.add(args.format_hint)

    # Expand to family for layer 2
    if layer == 2 and formats:
        expanded = set()
        for fmt in formats:
            expanded.update(resolve_family(fmt, manifest))
        formats = expanded

    # Load cross-format index and resolve cross-format test paths (L1/L2 + auto mode)
    if formats and layer <= 2 and not getattr(args, "no_cross_format", False):
        cf_index = load_cross_format_index()
        if cf_index:
            cross_format_paths = resolve_cross_format_paths(formats, cf_index)
            if cross_format_paths:
                # Escalate layer to 4 (golden) when cross-format tests are included
                cf_resolution = manifest.get("cross_format_resolution", {})
                escalation_layer = cf_resolution.get("escalation_layer", 4)
                if layer < escalation_layer:
                    old_layer = layer
                    layer = escalation_layer
                    reason = (
                        f"{reason} [escalated L{old_layer}->L{layer}: "
                        f"{len(cross_format_paths)} cross-format test(s) detected]"
                    )

    # Parse shard
    shard = None
    if args.shard:
        parts = args.shard.split("/")
        if len(parts) == 2:
            shard = (int(parts[0]), int(parts[1]))

    # Build junitxml path
    junitxml_path = None
    if not args.dry_run:
        results_dir = REPO_ROOT / ".local" / "test-results"
        results_dir.mkdir(parents=True, exist_ok=True)
        ts = datetime.now().strftime("%Y%m%d-%H%M%S")
        shard_suffix = f"-shard{shard[0]}" if shard else ""
        junitxml_path = str(results_dir / f"layer{layer}{shard_suffix}-{ts}.xml")

    cmd = build_pytest_cmd(
        layer=layer,
        formats=formats if layer <= 2 else None,
        shard=shard,
        verbose=args.verbose,
        junitxml_path=junitxml_path,
        cross_format_paths=cross_format_paths if layer <= 2 else None,
        skip_arithmetic=getattr(args, "skip_arithmetic", False),
    )

    if args.dry_run:
        print(json.dumps({
            "layer": layer,
            "layer_name": LAYER_NAMES.get(layer, f"layer{layer}"),
            "layer_reason": reason,
            "formats_detected": sorted(formats),
            "cross_format_paths_included": cross_format_paths,
            "skip_arithmetic": getattr(args, "skip_arithmetic", False),
            "marker_expr": build_marker_expr(layer) or "(no filter - full suite)",
            "command": " ".join(cmd),
            "shard": f"{shard[0]}/{shard[1]}" if shard else None,
            "dry_run": True,
        }, indent=2))
        return

    result = run_and_collect(
        cmd=cmd,
        layer=layer,
        layer_reason=reason,
        formats=formats,
        shard=shard,
        json_out_path=args.json_out,
    )

    # TC-FSLAY02-SHARD-001: Update shard ledger after sharded runs
    if shard:
        _update_shard_ledger(shard[0], shard[1], result)

    # Known-failures comparison (if requested)
    if args.known_failures and not args.dry_run:
        # Find junitxml from command args
        xml_path = None
        for i, c in enumerate(cmd):
            if c == "--junitxml" and i + 1 < len(cmd):
                xml_path = cmd[i + 1]
                break
        pre_existing, new_failures = _compare_known_failures(
            result["test_results"], args.known_failures, xml_path
        )
        result["known_failures"] = pre_existing
        result["new_failures"] = new_failures
        result["regressions"] = new_failures  # alias for clarity
        if args.json_out:
            out_path = Path(args.json_out)
            with open(out_path, "w") as f:
                json.dump(result, f, indent=2)

    # Print summary
    tr = result["test_results"]
    status = "PASS" if tr["failed"] == 0 and tr["errors"] == 0 else "FAIL"
    print(f"\n[Layer {layer} ({result['layer_name']})] {status}")
    print(f"  Reason: {reason}")
    print(f"  Passed: {tr['passed']}, Failed: {tr['failed']}, "
          f"Skipped: {tr['skipped']}, Errors: {tr['errors']}")
    print(f"  Duration: {result['duration_seconds']}s")
    if args.json_out:
        print(f"  Results: {args.json_out}")
    if args.known_failures and "new_failures" in result:
        n_new = len(result["new_failures"])
        n_pre = len(result["known_failures"])
        print(f"  Known failures: {n_pre} pre-existing, {n_new} new")

    # TC-FSLAY02-KNOWN-001: Mask exit code when all failures are pre-existing.
    # Only mask when --known-failures was provided AND new_failures is empty list.
    exit_code = result["pytest_exit_code"]
    if (args.known_failures
            and result.get("new_failures") is not None
            and len(result["new_failures"]) == 0
            and exit_code != 0):
        result["exit_code_masked"] = True
        result["exit_code_mask_reason"] = "all_failures_pre_existing"
        exit_code = 0
        print(f"  Exit code masked: all {len(result.get('known_failures', []))} failures "
              "are pre-existing known failures. New failures: 0.")
        # Update JSON output if requested
        if args.json_out:
            result["pytest_exit_code"] = 0
            out_path = Path(args.json_out)
            with open(out_path, "w") as f:
                json.dump(result, f, indent=2)

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
