"""Exception coverage tests for tsv format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from tsv.exceptions import TsvWriteError
from tsv.exceptions import TsvError


def test_tsvwriteerror_is_raisable():
    with pytest.raises(TsvWriteError):
        raise TsvWriteError("test error message")


def test_tsvwriteerror_inherits_base():
    assert issubclass(TsvWriteError, TsvError)


def test_tsvwriteerror_message():
    exc = TsvWriteError("specific error")
    assert "specific error" in str(exc)
