"""Exception coverage tests for fodp format.

Ensures all exception classes are importable, raisable, and properly subclassed.
Generated by TC-CERT-H-EXC certification hardening.
"""
import pytest

from fodp.exceptions import FodpWriteError
from fodp.exceptions import FodpError


def test_fodpwriteerror_is_raisable():
    with pytest.raises(FodpWriteError):
        raise FodpWriteError("test error message")


def test_fodpwriteerror_inherits_base():
    assert issubclass(FodpWriteError, FodpError)


def test_fodpwriteerror_message():
    exc = FodpWriteError("specific error")
    assert "specific error" in str(exc)
