"""Generated UBL 2.2-to-2.3 migration-eligibility table. Do not edit by hand.

visibility: generated
generated_by: claude
"""

from __future__ import annotations

from typing import Final

AUTHORITY_SHA256_2_2: Final = "90f7ce34c57fc21cd5a88d7bcd4acdf3c89d59218ce00770a7949bf707e71346"
AUTHORITY_SHA256_2_3: Final = "623bef8310db4d979ff28000a96bcc56dbcdda4f6206cf094c0aa79b75817970"
TABLE_SHA256: Final = "4a866fea1923849d5a35070b9bb13cb6293dc747ffc4101a1afa70edd132524a"
SOURCE_VERSION: Final = "2.2"
TARGET_VERSION: Final = "2.3"
MIGRATABLE_2_2_ROOT_NAMES: Final[frozenset[str]] = frozenset({
    "ApplicationResponse",
    "AttachedDocument",
    "AwardedNotification",
    "BillOfLading",
    "BusinessCard",
    "CallForTenders",
    "Catalogue",
    "CatalogueDeletion",
    "CatalogueItemSpecificationUpdate",
    "CataloguePricingUpdate",
    "CatalogueRequest",
    "CertificateOfOrigin",
    "ContractAwardNotice",
    "ContractNotice",
    "CreditNote",
    "DebitNote",
    "DespatchAdvice",
    "DigitalAgreement",
    "DigitalCapability",
    "DocumentStatus",
    "DocumentStatusRequest",
    "Enquiry",
    "EnquiryResponse",
    "ExceptionCriteria",
    "ExceptionNotification",
    "ExpressionOfInterestRequest",
    "ExpressionOfInterestResponse",
    "Forecast",
    "ForecastRevision",
    "ForwardingInstructions",
    "FreightInvoice",
    "FulfilmentCancellation",
    "GoodsItemItinerary",
    "GuaranteeCertificate",
    "InstructionForReturns",
    "InventoryReport",
    "Invoice",
    "ItemInformationRequest",
    "Order",
    "OrderCancellation",
    "OrderChange",
    "OrderResponse",
    "OrderResponseSimple",
    "PackingList",
    "PriorInformationNotice",
    "ProductActivity",
    "QualificationApplicationRequest",
    "QualificationApplicationResponse",
    "Quotation",
    "ReceiptAdvice",
    "Reminder",
    "RemittanceAdvice",
    "RequestForQuotation",
    "RetailEvent",
    "SelfBilledCreditNote",
    "SelfBilledInvoice",
    "Statement",
    "StockAvailabilityReport",
    "Tender",
    "TenderContract",
    "TenderReceipt",
    "TenderStatus",
    "TenderStatusRequest",
    "TenderWithdrawal",
    "TendererQualification",
    "TendererQualificationResponse",
    "TradeItemLocationProfile",
    "TransportExecutionPlan",
    "TransportExecutionPlanRequest",
    "TransportProgressStatus",
    "TransportProgressStatusRequest",
    "TransportServiceDescription",
    "TransportServiceDescriptionRequest",
    "TransportationStatus",
    "TransportationStatusRequest",
    "UnawardedNotification",
    "UnsubscribeFromProcedureRequest",
    "UnsubscribeFromProcedureResponse",
    "UtilityStatement",
    "Waybill",
    "WeightStatement",
})
