"""LLM dry-run through deterministic gates — Lane F (LFI-6-F).

Simulates mock LLM output through the full deterministic gate chain:
  G1: py_compile (syntax check)
  G3: AST forbidden-call scanner
  ComposeVerifyLoop: queue-shaped dry-run with G3 embedded
  FreezeGateRunner: binding_roundtrip gate (optional post-verify)

LLM backend remains disabled (stub mode). These tests use deterministic
synthetic code strings as mock LLM output.

Sprint: FF-LIBFORGE-GUARDED-AUTONOMOUS-EXPANSION-001
Taskcard: LFI-6-F
Execution-method: AGENT_GOVERNED_DIRECT_EXECUTION
"""
from __future__ import annotations

import json
import py_compile
import sys
import tempfile
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO_ROOT))

from tools.supervisor.ast_forbidden_scanner import scan_source
from tools.supervisor.compose_verify_loop import ComposeVerifyLoop, LLMBackendStub
from tools.supervisor.freeze_gate_runner import FreezeGateRunner, GateStatus


# ---------------------------------------------------------------------------
# Mock LLM output samples
# ---------------------------------------------------------------------------

MOCK_LLM_SAFE_OUTPUT = '''"""Generated by mock LLM — safe output."""
from __future__ import annotations


def get_word_count(text: str) -> int:
    """Return the number of words in text."""
    return len(text.split())


def reverse_text(text: str) -> str:
    """Return text reversed."""
    return text[::-1]
'''

MOCK_LLM_FORBIDDEN_OUTPUT = '''"""Generated by mock LLM — contains forbidden call."""
import os


def dangerous_function(cmd: str) -> None:
    os.system(cmd)
'''

MOCK_LLM_ALIASED_FORBIDDEN_OUTPUT = '''"""Generated by mock LLM — aliased forbidden call (v2 detects this)."""
import subprocess as sp


def run_command(cmd: list) -> None:
    sp.run(cmd)
'''

MOCK_LLM_FROM_IMPORT_FORBIDDEN = '''"""Generated by mock LLM — from-import forbidden call."""
from subprocess import run


def execute(cmd: list) -> None:
    run(cmd)
'''

MOCK_LLM_SYNTAX_ERROR = '''"""Generated by mock LLM — syntax error."""
def broken(x:
    return x + 1
'''


# ---------------------------------------------------------------------------
# Gate 1: py_compile (syntax check)
# ---------------------------------------------------------------------------


class TestG1SyntaxGate:
    """Gate 1: py_compile validates syntax of mock LLM output."""

    def test_safe_output_passes_syntax(self, tmp_path):
        p = tmp_path / "gen.py"
        p.write_text(MOCK_LLM_SAFE_OUTPUT, encoding="utf-8")
        try:
            py_compile.compile(str(p), doraise=True)
            passed = True
        except py_compile.PyCompileError:
            passed = False
        assert passed

    def test_forbidden_output_still_valid_syntax(self, tmp_path):
        """Forbidden calls are syntactically valid — G3 catches them, not G1."""
        p = tmp_path / "gen.py"
        p.write_text(MOCK_LLM_FORBIDDEN_OUTPUT, encoding="utf-8")
        try:
            py_compile.compile(str(p), doraise=True)
            passed = True
        except py_compile.PyCompileError:
            passed = False
        assert passed  # valid syntax — G3 is needed

    def test_syntax_error_fails_g1(self, tmp_path):
        p = tmp_path / "gen.py"
        p.write_text(MOCK_LLM_SYNTAX_ERROR, encoding="utf-8")
        with pytest.raises(py_compile.PyCompileError):
            py_compile.compile(str(p), doraise=True)


# ---------------------------------------------------------------------------
# Gate 3: AST forbidden-call scanner
# ---------------------------------------------------------------------------


class TestG3Gate:
    """Gate 3: G3 AST scanner catches forbidden calls in mock LLM output."""

    def test_safe_output_passes_g3(self):
        result = scan_source(MOCK_LLM_SAFE_OUTPUT, "mock_safe.py")
        assert result.safe is True
        assert len(result.findings) == 0

    def test_forbidden_output_caught_by_g3(self):
        result = scan_source(MOCK_LLM_FORBIDDEN_OUTPUT, "mock_forbidden.py")
        assert result.safe is False
        assert result.findings[0].symbol == "os.system"

    def test_aliased_forbidden_caught_by_g3_v2(self):
        """v2 alias hardening: sp.run() is now detected."""
        result = scan_source(MOCK_LLM_ALIASED_FORBIDDEN_OUTPUT, "mock_alias.py")
        assert result.safe is False
        assert result.findings[0].symbol == "subprocess.run"

    def test_from_import_forbidden_caught_by_g3_v2(self):
        """v2 from-import hardening: from subprocess import run; run() is detected."""
        result = scan_source(MOCK_LLM_FROM_IMPORT_FORBIDDEN, "mock_from_import.py")
        assert result.safe is False
        assert result.findings[0].symbol == "subprocess.run"

    def test_g3_scan_result_is_json_serializable(self):
        result = scan_source(MOCK_LLM_FORBIDDEN_OUTPUT, "mock.py")
        parsed = json.loads(result.to_json())
        assert parsed["safe"] is False
        assert len(parsed["findings"]) > 0


# ---------------------------------------------------------------------------
# ComposeVerifyLoop dry-run with G3 integrated
# ---------------------------------------------------------------------------


class TestComposeVerifyDryRun:
    """ComposeVerifyLoop dry-run simulates full gate chain without writing files."""

    def test_safe_llm_output_passes_all_gates(self):
        loop = ComposeVerifyLoop()
        result = loop.run(
            feature_name="mock_llm_safe",
            template_content=MOCK_LLM_SAFE_OUTPUT,
            dry_run=True,
            queue_item_id="LLM-DRY-001",
            taskcard_id="LFI-6-F",
            target_format="ndjson",
        )
        assert result.ok is True
        assert result.dry_run is True
        assert result.g3_safe is True
        assert result.queue_item_id == "LLM-DRY-001"
        assert result.taskcard_id == "LFI-6-F"

    def test_forbidden_llm_output_blocked_by_g3(self):
        loop = ComposeVerifyLoop()
        result = loop.run(
            feature_name="mock_llm_forbidden",
            template_content=MOCK_LLM_FORBIDDEN_OUTPUT,
            dry_run=True,
        )
        assert result.ok is False
        assert result.g3_safe is False
        assert result.changed_files == []

    def test_aliased_forbidden_blocked_by_g3_v2(self):
        """v2 alias detection: sp.run() in mock LLM output is caught by gate."""
        loop = ComposeVerifyLoop()
        result = loop.run(
            feature_name="mock_llm_alias",
            template_content=MOCK_LLM_ALIASED_FORBIDDEN_OUTPUT,
            dry_run=True,
        )
        assert result.ok is False
        assert result.g3_safe is False

    def test_dry_run_result_is_json_serializable(self):
        loop = ComposeVerifyLoop()
        result = loop.run(
            feature_name="mock_dry_serial",
            template_content=MOCK_LLM_SAFE_OUTPUT,
            dry_run=True,
        )
        d = result.to_dict()
        json.dumps(d)  # must not raise
        assert d["dry_run"] is True
        assert d["g3_safe"] is True


# ---------------------------------------------------------------------------
# FreezeGate as post-verify gate
# ---------------------------------------------------------------------------


class TestFreezeGatePostVerify:
    """FreezeGateRunner used as post-verify deterministic gate."""

    def test_zst_freeze_gate_passes_for_safe_code(self):
        """After safe code verified, ZST freeze gate still PASS independently."""
        runner = FreezeGateRunner(repo_root=str(_REPO_ROOT))
        report = runner.run("zst", gate_kinds=["binding_roundtrip"])
        assert report.overall_status == GateStatus.PASS.value

    def test_ndjson_freeze_gate_passes_for_safe_code(self):
        """NDJSON freeze gate (second format) also passes."""
        runner = FreezeGateRunner(repo_root=str(_REPO_ROOT))
        report = runner.run("ndjson", gate_kinds=["binding_roundtrip"])
        assert report.overall_status == GateStatus.PASS.value

    def test_freeze_gate_report_is_json_serializable(self):
        runner = FreezeGateRunner(repo_root=str(_REPO_ROOT))
        report = runner.run("zst")
        json.dumps(report.to_dict())  # must not raise


# ---------------------------------------------------------------------------
# LLM stub remains disabled
# ---------------------------------------------------------------------------


class TestLLMStubDisabled:
    """LLM backend remains disabled throughout — all gates are deterministic."""

    def test_llm_stub_is_disabled(self):
        stub = LLMBackendStub()
        assert stub.enabled is False

    def test_llm_stub_raises_not_implemented(self):
        stub = LLMBackendStub()
        with pytest.raises(NotImplementedError):
            stub.compose("template", {})

    def test_compose_loop_uses_stub_by_default(self):
        loop = ComposeVerifyLoop()
        assert loop._llm.enabled is False
